### ISSUE TITLE
Microsoft Teams Connectors giving 503 - Something went wrong :'( 

### ISSUE THREAD

**Issue by apatils** [MicrosoftDocs/msteams-docs#1033] opened 2019-10-10 06:02 UTC
I am getting this error when I am trying to add new connector in Microsoft teams, also my pre-configured Incoming Webhooks are not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c2fa7fb-49bf-8c92-88b1-fe2e14c5edee
* Version Independent ID: ff62f069-6977-8e27-7301-d3e29df3abc7
* Content: [Office 365 Connectors - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/connectors/connectors#feedback)
* Content Source: [msteams-platform/concepts/connectors/connectors.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/connectors/connectors.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment] 2019-10-10 11:08
Duplicate of #1034

**Closed by Gousia-MSFT** 2019-10-10 11:08 UTC
