### ISSUE TITLE
How do I migrate data from any of my database to Teams?

### ISSUE THREAD

**Issue by prakharrke** [MicrosoftDocs/msteams-docs#294] opened 2018-10-22 09:40 UTC

**Comment by prakharrke** [comment] 2018-10-22 10:03
I wish to migrate data from any kind of database to MS Teams.
Is it possible?
Can I use connectors to accomplish this?

**Comment by Wajeed-msft** [comment] 2018-10-25 05:44
Duplicate of issue https://github.com/MicrosoftDocs/msteams-docs/issues/295

**Closed by Wajeed-msft** 2018-10-25 05:44 UTC
