### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by s-KaiNet** [MicrosoftDocs/msteams-docs#1374] opened 2020-02-18 17:41 UTC
Link [Tabs design(~/tabs/design/tabs.md) is broken (`]` is missing).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae27eac6-3289-3945-f3f1-fb9d811ff95c
* Version Independent ID: 720ebdd4-77fa-f0d4-d566-c8fff9afb08d
* Content: [Design Guidelines Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/personal-apps)
* Content Source: [msteams-platform/concepts/design/personal-apps.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/design/personal-apps.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment] 2020-02-19 03:23
Duplicate of #1375

**Comment by s-KaiNet** [comment] 2020-02-19 05:44
It's not duplicate, it's two different broken links...

**Comment by Gousia-MSFT** [comment] 2020-02-19 06:21
@s-KaiNet Sorry about it. Re-opening.

**Comment by PrasadKasireddy** [comment] 2020-02-19 08:59
Thanks for reporting this issue, I have corrected the broken link and waiting for merge

**Closed** 2020-02-19 23:52 UTC
