### ISSUE TITLE
List card is randomly showing icons on Teams v2

### ISSUE THREAD

**Issue by vbatr** [MicrosoftDocs/msteams-docs#9845] opened 2023-11-07 14:34 UTC
Hi 

After moving to Teams v2 we can see that icons on list view are randomly changing, so each item in a list has the same icon.

https://github.com/MicrosoftDocs/msteams-docs/assets/20244602/83dad9f1-a1c8-4aa5-a2b4-db14c926a00b

Regards
Volodymyr B.

**Comment by vhensorskyi** [comment] 2023-11-07 14:38
Hello team,

I am experiencing the same behavior on new desktop and web clients.

**Comment by Prasad-MSFT** [comment] 2023-11-08 05:57
Hi @vbatr & @vhensorskyi - Thanks for raising this. We will try to repro this at our end and will update in the thread

**Comment by Prasad-MSFT** [comment] 2023-11-08 07:39
We tried to repro this issue using List Card in New Teams. However in our case it is rendering correctly.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/f9d574c2-6107-4f5d-bf1f-b69130a5706e)

**Comment by vbatr** [comment] 2023-11-08 11:54
Hi @Prasad-MSFT 

We are using just items with  "type": "resultItem" in the list. 
Could you please try to reproduce it on the list with few result items with different icons?

Thanks,
Volodymyr B.

**Comment by Prasad-MSFT** [comment] 2023-11-08 13:27
Hi @vbatr - we again checked with `"type": "resultItem"` in the list and its working fine at our end.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/2fb766f3-c34b-4ba7-b388-ac8ef92bf0d5)

**Comment by vbatr** [comment] 2023-11-08 14:25
@Prasad-MSFT sending you the JSON of the card we are using (it was generated by C# app, so probably it needs to be a edited a bit):

[ListCardExample.json](https://github.com/MicrosoftDocs/msteams-docs/files/13297736/ListCardExample.json)

- Volodymyr

**Comment by Prasad-MSFT** [comment] 2023-11-10 10:11
@vbatr - we tried using [this](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-search/csharp) sample, but still couldn't repro. Do you have any deployed app/sample so that we can check and raise bug for the same?

**Comment by Prasad-MSFT** [comment] 2023-11-13 09:12
@vbatr - We tested again in New Teams using the card provided and were able to repro this issue. We have raised a bug for the same. We will inform you once we get any further update from engineering team. 
Thanks!

**Comment by Vena-Kanavi** [comment] 2024-03-06 04:57
@Prasad-MSFT Any Updates on this? We are also running into this issue.

**Comment by Prasad-MSFT** [comment] 2024-03-06 05:13
Hi @Vena-Kanavi - The bug fix has not been rolled out publicly. Once the fix is publicly available, we will notify in this thread.

Thanks!

**Comment by Vena-Kanavi** [comment] 2024-03-19 13:27
Hi @Prasad-MSFT Could you provide an update on when the bug fix will be made available to the public?

**Comment by Prasad-MSFT** [comment] 2024-07-08 07:31
@vbatr , @Vena-Kanavi - The issue is fixed now. Please do verify. 
We tested in both MS Teams desktop/web client and Mobile clients.
`Microsoft Teams version 24152.415.2975.367.`
`The client version is 49/24051622220.`
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/a43e16fb-04b8-461d-8f59-368327ebe708)

**Closed** 2024-07-09 13:58 UTC
Labels: teams-developer-support, bug, T2.1
