### ISSUE TITLE
Auth flow Teams Tab behaves differently for some users

### ISSUE THREAD

**Issue by FHeemskerk** [MicrosoftDocs/msteams-docs#4069] opened 2021-08-27 11:14 UTC
Some users are unable to log in on a teams tab page from the teams client, using Azure AD auth flow. The workaround is to pop out the tab and then the flow does run. Web users are unaffected and it is not for all users. However, the users that are affected, seem to have this issue consistently.

We use 
microsoftTeams.authentication.authenticate...
which pops up a window. There we respond with a challengeresult.
Azure Ad auth screen and a callback to our own page.

From this point we noticed differences in behavior
Client A:
`microsoftTeams.initialize(callback)` -> callback is fired
`microsoftTeams.authentication.notifySuccess` -> triggers the success callback of the authenticate call

Client B (Teams client, tab)
`microsoftTeams.initialize(callback)` -> callback is NOT fired (which is not a problem perse, but i think it is worth to mention), the initialize call DOES actually execute, as removing this call makes the next call error out with a message initialize should be called first.
`microsoftTeams.authentication.notifySuccess` -> triggers the FAILED callback of the authenticate call, mentioning CancelledByUser.

Client B (Teams client, tab popped OUT / web client)
like Client A.

We have not been able to discover some connection between the clients that do succeed, or don't.

**Comment by FHeemskerk** [comment] 2021-09-02 07:38
Hi, any news on this?

**Comment by v-chetsh** [comment] 2021-09-02 08:53
@FHeemskerk  - Could you please try to downgrade your version of teams and let the app upgrade itself this clears whatever the issue is and the calls may start working again.

https://microsoft-teams.en.uptodown.com/windows/versions
That's one place that has an archive of older versions, install one of them & check

**Comment by v-chetsh** [comment] 2021-09-06 17:32
@FHeemskerk - Could you please use the version which is working fine for now.
There will definitely a fix will come in upcoming days.

Could you please close the issue if you think your issue is resolved.

**Comment by v-chetsh** [comment] 2021-09-15 05:05
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2021-09-15 05:05 UTC
Labels: teams-developer-support, needs-triage :mag:

**Comment by saravijkum** [comment] 2021-10-11 11:10
Hey @v-chetsh,

Couple of our customer are not able to login to Assembly from MS Teams desktop client. When they click on the SSO button, the pop up opens and authenticates the user but the pop closes and send us CancelledByUser error. This issue is happening only for 2-3 users and not for everyone. Since it is happening for high profile users, we need to get this fixed ASAP.

Assembly app link: https://appsource.microsoft.com/en-us/product/office/wa200002271?tab=overview

**Comment by v-chetsh** [comment] 2021-12-01 07:39
We have got feedback from a customer that after updating the Teams desktop client to the latest the issue is no longer persists. Could you please try updating the Teams desktop client and check it once?
Please let us know if you are still facing the issue.

Thanks
