### ISSUE TITLE
Layout error in message extensions in personal and group chat scope

### ISSUE THREAD

**Issue by sortegamartin** [MicrosoftDocs/msteams-docs#4874] opened 2021-12-20 09:03 UTC
Hi,

Message extensions in the personal and group chat scope looks like this:

![image](https://user-images.githubusercontent.com/33054287/146740435-876d7ea2-651e-4035-a8eb-04e6723aec10.png)

On the other hand, in the team scope it is displayed correctly:

![image](https://user-images.githubusercontent.com/33054287/146740708-0dd88a3e-9ef8-4bd2-a759-50d1e89ccda1.png)

**Comment by sayali-MSFT** [comment] 2021-12-21 04:31
@sortegamartin - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment] 2021-12-22 11:13
@sortegamartin - Could you please elaborate your requirement and share the repro steps, so that we can try it from our end.

**Comment by sortegamartin** [comment] 2021-12-22 12:28
I share the manifest of the Teams application:

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "manifestVersion": "1.11",
  "id": "{{APPLICATION_ID}}",
  "version": "1.0.0",
  "packageName": "{{PACKAGE_NAME}}",
  "developer": {
    "name": "sortegam",
    "websiteUrl": "https://{{PUBLIC_HOSTNAME}}",
    "privacyUrl": "https://{{PUBLIC_HOSTNAME}}/privacy.html",
    "termsOfUseUrl": "https://{{PUBLIC_HOSTNAME}}/tou.html"
  },
  "name": {
    "short": "Sortegam App",
    "full": "Sortegam App for Test"
  },
  "description": {
    "short": "TODO: add short description here",
    "full": "TODO: add full description here"
  },
  "icons": {
    "outline": "icon-outline.png",
    "color": "icon-color.png"
  },
  "accentColor": "#D85028",
  "configurableTabs": [
    {
      "configurationUrl": "https://{{PUBLIC_HOSTNAME}}/teamsAppTab/config.html?name={loginHint}&tenant={tid}&group={groupId}&theme={theme}",
      "canUpdateConfiguration": true,
      "scopes": ["team", "groupchat"],
      "sharePointPreviewImage": "https://{{PUBLIC_HOSTNAME}}/assets/teamsAppTab-preview.png",
      "supportedSharePointHosts": ["sharePointFullPage", "sharePointWebPart"]
    }
  ],
  "staticTabs": [],
  "bots": [
    {
      "botId": "{{MICROSOFT_APP_ID}}",
      "needsChannelSelector": true,
      "isNotificationOnly": false,
      "scopes": ["team", "personal", "groupchat"],
      "commandLists": [
        {
          "scopes": ["team", "personal"],
          "commands": [
            {
              "title": "Help",
              "description": "Shows help information"
            },
            {
              "title": "Who am I?",
              "description": "Shows information about your Teams user"
            },
            {
              "title": "Mention me",
              "description": "Let the bot @mention you"
            }
          ]
        }
      ],
      "supportsFiles": true,
      "supportsCalling": true,
      "supportsVideo": true
    }
  ],
  "connectors": [],
  "composeExtensions": [
    {
      "botId": "{{MICROSOFT_APP_ID}}",
      "canUpdateConfiguration": true,
      "commands": [
        {
          "id": "teamsAppMessageExtension",
          "title": "TeamsApp Message Extension",
          "description": "Description of TeamsApp Message Extension",
          "initialRun": true,
          "parameters": [
            {
              "name": "parameter",
              "description": "Description of the parameter",
              "title": "Parameter"
            }
          ],
          "type": "query"
        },
        {
          "id": "SearchNewsExtension",
          "title": "News",
          "description": "Search News",
          "initialRun": true,
          "parameters": [
            {
              "name": "Parameter Name 2",
              "description": "Search News",
              "title": "Parameter Title 2"
            }
          ],
          "type": "query"
        },
        {
          "id": "SearchApplicationsExtension",
          "title": "Applications",
          "description": "Search Applications",
          "initialRun": true,
          "parameters": [
            {
              "name": "Parameter Name 2",
              "description": "Search Applications",
              "title": "Parameter Title 2"
            }
          ],
          "type": "query"
        },
        {
          "id": "SearchDocumentsExtension",
          "title": "Documents",
          "description": "Search Documents",
          "initialRun": true,
          "parameters": [
            {
              "name": "Parameter Name 2",
              "description": "Search Documents",
              "title": "Parameter Title 2"
            }
          ],
          "type": "query"
        },
        {
          "id": "SearchCommunitiesExtension",
          "title": "Communities",
          "description": "Search Communities",
          "initialRun": true,
          "parameters": [
            {
              "name": "Parameter Name 2",
              "description": "Search Communities",
              "title": "Parameter Title 2"
            }
          ],
          "type": "query"
        },
        {
          "id": "advancedSearch",
          "type": "action",
          "title": "Advanced search",
          "description": "Advanced search",
          "initialRun": false,
          "fetchTask": false,
          "context": ["commandBox", "compose"],
          "taskInfo": {
            "title": "Advanced search",
            "width": "1100",
            "height": "665",
            "url": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamstaskhostedapp.aspx%3Fteams%26personal%26componentId=e5f635ea-5cf5-40d0-9186-a90f52d5a415%26forceLocale={locale}"
          }
        },
        {
          "id": "executeActions",
          "type": "action",
          "title": "Execute an action",
          "description": "Execute an action",
          "initialRun": false,
          "fetchTask": false,
          "context": ["commandBox", "compose"],
          "taskInfo": {
            "title": "Execute an action",
            "width": "415",
            "url": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamstaskhostedapp.aspx%3Fteams%26personal%26componentId=dee33d3d-f845-4be0-8cdd-6a53ab867259%26forceLocale={locale}"
          }
        }
      ]
    }
  ],
  "permissions": ["identity", "messageTeamMembers"],
  "validDomains": ["{{PUBLIC_HOSTNAME}}"],
  "showLoadingIndicator": true,
  "webApplicationInfo": {
    "resource": "https://{teamSiteDomain}",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  },
  "localizationInfo": {
    "defaultLanguageTag": "en-us",
    "additionalLanguages": [
      {
        "languageTag": "es-es",
        "file": "es-es.json"
      }
    ]
  }
}

**Comment by sayali-MSFT** [comment] 2021-12-27 10:13
@sortegamartin - We are able to repro that issue ,We are checking it internally and let you know if we get any updates.

**Comment by sayali-MSFT** [comment] 2021-12-29 09:50
@sortegamartin -  We have raised bug for your scenario and concerned team is looking into it. We will inform you once we get any update.

**Comment by v-chetsh** [comment] 2022-01-20 06:46
@sortegamartin - We have confirmed this with engineering team and it's the by design behavior for Messaging Extension in different scopes.

**Comment by v-chetsh** [comment] 2022-01-20 06:47
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2022-01-20 06:47 UTC
Labels: teams-developer-support
