### ISSUE TITLE
Windows 10 desktop app always restarts on close

### ISSUE THREAD

**Issue by jmacdonald01** [MicrosoftDocs/msteams-docs#1310] opened 2020-01-29 15:49 UTC
I am running the Windows desktop app on Windows 10. The first time I attempt to close the app, every time, the app will immediately restart. The splash screen that appears while the app is booting displays the message "There was a glitch, and we're recovering". Once the app boots, a pop-down message appears at the top of the chat window, reading "There was a glitch, and we had to restart the app. It's good to go now." Please see screenshots of each [here](https://imgur.com/a/V0lToZh).

The second time I close the app, it will close successfully.

I have the "On close, keep the application running" option unchecked in general settings.

**Comment by Subhasish-msft** [comment] 2020-01-30 10:58
Could you please share the Teams log by pressing (Ctrl+Shift+Alt+1)? Logs will be downloaded to your default Downloads folder. Can you share it on email [Microsoft Teams Developer Support](mailto:microsoftteamsdev@microsoft.com)

**Comment by jmacdonald01** [comment] 2020-01-30 14:13
[MSTeams Diagnostics Log 1_30_2020__9_12_39_AM_calling.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4134319/MSTeams.Diagnostics.Log.1_30_2020__9_12_39_AM_calling.txt)
[MSTeams Diagnostics Log 1_30_2020__9_12_39_AM_cdl.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4134320/MSTeams.Diagnostics.Log.1_30_2020__9_12_39_AM_cdl.txt)
[MSTeams Diagnostics Log 1_30_2020__9_12_39_AM_cdlWorker.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4134321/MSTeams.Diagnostics.Log.1_30_2020__9_12_39_AM_cdlWorker.txt)
[MSTeams Diagnostics Log 1_30_2020__9_12_39_AM_chatListData.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4134322/MSTeams.Diagnostics.Log.1_30_2020__9_12_39_AM_chatListData.txt)
[MSTeams Diagnostics Log 1_30_2020__9_12_39_AM_sync.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4134323/MSTeams.Diagnostics.Log.1_30_2020__9_12_39_AM_sync.txt)
[MSTeams Diagnostics Log 1_30_2020__9_12_38_AM.txt](https://github.com/MicrosoftDocs/msteams-docs/files/4134324/MSTeams.Diagnostics.Log.1_30_2020__9_12_38_AM.txt)

I've attached the files here Subhasish. I reproduced the double-close bug directly before downloading the logs, at about 9:12am Eastern time (UTC−05:00) Jan 30.

**Comment by Subhasish-msft** [comment] 2020-03-11 07:31
@jmacdonald01 ,
 I have created an ICM ticket for this. Will track it internally and will get back to you if more info is needed.

**Comment by jmacdonald01** [comment] 2020-03-11 12:50
Hi @Subhasish-msft, The issue has vanished as of last week. A recent update must have cleared it up.

**Comment by Subhasish-msft** [comment] 2020-03-12 05:54
@jmacdonald01, As the issue is resolved now. I am closing it. Please reopen, if you face it again.

**Closed** 2020-03-12 08:08 UTC
Labels: teams-developer-support
