### ISSUE TITLE
[MsTeams][Desktop/Mobile] [Input box and drop down box style not similar across all platform]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4665] opened 2021-11-22 21:40 UTC
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/3993 

**Details from original post:**
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android
* iOS
* JavaScript

# Author or host

MsTeams

# Details

HI ,

As we notice that we are getting different style of input box across different platform

**For Desktop:**
Input box style is rounded corner and with gray color 
Drop down style is similar to input box style

![Screenshot (8)](https://user-images.githubusercontent.com/60354515/81319512-66ffbf00-90ad-11ea-8a6b-388942043570.png)

**For Android:**
Input box style is rectangular with border and no gray color 
![Android](https://user-images.githubusercontent.com/60354515/81320807-649e6480-90af-11ea-838b-ca5ec4921071.png)

**For Iphone:**
Input box style is underline with no border and no gray color 

![Iphone](https://user-images.githubusercontent.com/60354515/81320910-85ff5080-90af-11ea-9237-736f2798d640.png)

Can it be similar across all platform like desktop???
---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by v-chetsh** [comment] 2021-11-23 08:29
Hello @Sujit-Gaikwad - Could you please share the platform versions and Teams version as well so that we can check it from our end.

**Comment by Nivedipa-MSFT** [comment] 2021-11-24 15:49
@Sujit-Gaikwad - We have confirmed with our engineering team that this is by design.The designs of Adaptive Cards are specific to the platform.

**Comment by v-chetsh** [comment] 2021-12-11 13:29
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2021-12-11 13:29 UTC
Labels: teams-developer-support, needs-triage :mag:
