### ISSUE TITLE
adaptive card not working in teams (unable to reach app)

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4058] opened 2021-08-26 20:22 UTC
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6239 

**Details from original post:**
### Target Platforms

Other

### SDK Version

4

### Application Name

Microsoft teams

### Problem Description

im developed my bot in ms bot framework python ,
bot is working fine in web test and in emulator but in teams the adaptive card is not working  

### Screenshots

![test](https://user-images.githubusercontent.com/61972140/130622277-7458d95d-d56a-4150-a007-20f3ab0cdccb.png)

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "actions": [
        {
            
            "type": "Action.Submit",
            "title": "Service Request",
            "data": "Service Request"
        },
        {
            
            "type": "Action.Submit",
            "title": "Incident",
            "data": "Incident"
        }
    ],
    "body": [
        {
            "type": "TextBlock",
            "wrap": true,
            "text": "Thank you for contacting support, do you want to report and incident or do you have a request?"
        }
    ]
}
```

### Sample Code Language

python

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by robinmalik** [comment] 2022-07-25 13:38
@Wajeed-msft @ChetanSharma-msft @Prithvi-MSFT When searching this repository for "unable to reach app" this old issue comes up, but there are some newer issues with people replying in them. Could this issue without any helpful information be closed, possibly?

**Comment by ChetanSharma-msft** [comment] 2022-07-25 13:49
@robinmalik - We can close this issue as a duplicate via linking other issues with this one.

**Comment by ChetanSharma-msft** [comment] 2022-07-25 15:57
@robinmalik - Can you please share the similar new issues, so that I can link and close this issue?

**Comment by robinmalik** [comment] 2022-07-25 17:06
@ChetanSharma-msft I just went by this: https://github.com/MicrosoftDocs/msteams-docs/issues?q=is%3Aissue+is%3Aopen+unable+to+reach+app

Possibly these:
#6529
#6497
#6461

**Comment by ChetanSharma-msft** [comment] 2022-07-26 04:30
We are closing this issue as a duplicate of this: https://github.com/MicrosoftDocs/msteams-docs/issues/6461

**Closed by ChetanSharma-msft** 2022-07-26 04:30 UTC
Labels: teams-developer-support
