### ISSUE TITLE
Link Unfurling - URL is not getting unfurled in iOS when sent as a new post in channel (Working in all other scenarios))

### ISSUE THREAD

**Issue by Abhiram219** [MicrosoftDocs/msteams-docs#9662] opened 2023-10-12 11:29 UTC
We've implemented link unfurling for the links in Microsoft Teams. When the links are pasted as a new post in iOS, the URL is not getting unfurled. The same is working when replying to a post as a message and when it is sent on a Direct chat.

The issue is iOS is working as expected in Android, and PC as well.

 Attached are the image references for the same.
![iOS_sent_as_post](https://github.com/MicrosoftDocs/msteams-docs/assets/60126553/0e32b62d-7dbf-4ffe-ba2d-318e34c82bd7)
![iOS_sending_as_post](https://github.com/MicrosoftDocs/msteams-docs/assets/60126553/716f4936-eedd-411b-9592-e2c5ba011c61)
![Android_sending_as_post](https://github.com/MicrosoftDocs/msteams-docs/assets/60126553/74d87f43-0b0a-4c73-9dc8-c0725c3588ce)

**Comment by Prasad-MSFT** [comment] 2023-10-13 05:35
@Abhiram219 - We are able to repro this issue. We have raised a bug for the same. We will inform you once we get any further update from engineering team. 
Thanks!

**Comment by ChetanSharma-msft** [comment] 2024-04-23 12:14
Hello @Abhiram219 - Sorry for delay in response.
We got an update from engineering team that this is by design behavior

Kindly raise your feature request here: [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by ChetanSharma-msft** [comment] 2024-04-23 12:16
We are closing this issue for now, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2024-04-23 12:16 UTC
Labels: teams-developer-support, feature-request, bug
