### ISSUE TITLE
Link new transactable SaaS offer to existing teams app not working

### ISSUE THREAD

**Issue by SRRepswal** [MicrosoftDocs/msteams-docs#5941] opened 2022-05-21 13:47 UTC
I am trying to link existing Teams app with new SaaS offer but it is not working. I have tried below two ways:

1. Link via Teams Developer Portal: I put publisherid.offerId in manifest file. I tried like below:
   a. 
 ```
  "subscriptionOffer": { 
		"offerId": "leafletcorporation165254955xxxx.leafletformicrosoftteams" 
      }
```
"Buy a Subscription" button is not there while adding app
   b. 

```
 "subscriptionOffer": { 
		"offerId": "leafletcorporation165254955xxxx.leafletformicrosoftteams-preview" 
      }
```
"Buy a Subscription" button is there but on click it is displaying "We couldn't load subscription plans"
2. Link via Partner Center: in Offer Setup section, I selected "Yes, I have published Teams apps, Office add-ins, or SharePoint Framework solutions that I would like to link to this SaaS offer" and in app source link input, I put app source product URL(App is already published in the app source). In this case also while I am adding app from app source, "Buy a Subscription" button is not there

**Comment by Nivedipa-MSFT** [comment] 2022-05-23 05:27
@SRRepswal - Could you please share repro steps to try at our end?

**Comment by SRRepswal** [comment] 2022-05-23 08:03
@Nivedipa-MSFT - We have already published an app in app source and now are are looking that to bind with SaaS offer(App Monetization). I did below steps:

1. Created an SaaS offer on Partner Center  
2. On Partner Center >> Offer Setup >> Selected "Yes, I have published Teams apps, Office add-ins, or SharePoint Framework solutions that I would like to link to this SaaS offer" and configured published app source app URL --> While adding app to Teams from app source, "Buy a Subscription" button is not there so went to step 3
3. Configured <<publisherId>>.<<offerId>> in Teams app manifest file like: "subscriptionOffer": { 
   	"offerId": "leafletcorporation165254955xxxx.leafletformicrosoftteams" 
     }
In step 3 also "Buy a Subscription" button is not there while adding app from App Source

**Comment by Nivedipa-MSFT** [comment] 2022-05-23 12:28
@SRRepswal - 'Buy a Subscription' feature is only confined to US region. Its not enabled for any other region.

**Comment by SRRepswal** [comment] 2022-05-23 14:24
@Nivedipa-MSFT  - I checked for USA region also. There also 'Buy a Subscription' button is not visible.

**Comment by Nivedipa-MSFT** [comment] 2022-05-24 10:18
@SRRepswal - Could you please refer below thread for this issue.
https://techcommunity.microsoft.com/t5/teams-developer/link-new-transactable-saas-offer-to-existing-teams-app-not/m-p/3409459#M5579

**Comment by SRRepswal** [comment] 2022-05-24 10:22
@Nivedipa-MSFT - That is still open.

**Comment by Prasad-MSFT** [comment] 2022-05-26 11:53
Hope, the issue is resolved now in [this](https://techcommunity.microsoft.com/t5/teams-developer/link-new-transactable-saas-offer-to-existing-teams-app-not/m-p/3409459#M5579) thread.
Developers can test end to end flows using preview SaaS offers, not live ones. We have also updated docs to highlight this part so that other developers don't face this issue. 

![image](https://user-images.githubusercontent.com/62237649/170482854-fd34d790-f811-42de-b008-8f9363afc1b0.png)

Doc Reference: [Test the offer | Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/appsource/prepare/include-saas-offer#test-the-offer)

We are closing the issue for now. Please feel free to reopen if required

**Closed by Prasad-MSFT** 2022-05-26 11:53 UTC
Labels: teams-developer-support, needs-attention
