### ISSUE TITLE
[Bug] MS Teams inconsistent behaviour of images in adaptive cards

### ISSUE THREAD

**Issue by joschi27** [MicrosoftDocs/msteams-docs#4998] opened 2022-01-13 10:59 UTC
Hello,

This isssue is about the weird behaviour of images in adaptivecards in teams, depending on platform.

Reproduce:
Send this per bot to teams:
`{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.5",
    "body": [
        {
        "type": "TextBlock",
            "text": "Image",
            "weight": "bolder",
            "size": "large"
        },
        {
        "type": "Image",
            "url": "https://adaptivecards.io/content/cats/1.png",
            "size": "small"
        }
    ]
}`

Issue:
On desktop, the image is static, non-clickable except when there is an adaptivecard action on it.
On web, the image is clickable (mouse hover indicator) and when clicked, a boatload of errors occur on the console.
On mobile, the image is clickable and opens in a separate window. 

I think the correct way would for the image in the reproduce example to just not be clickable / openable at all. There is an selectAction attribute on the image that, per default, does nothing.

If you for example create a column that has the Action.OpenUrl and the image is a child of that column, on desktop it opens the webpage properly, as it should. On mobile it completely ignores the openurl action and opens the image (????) in a new window.

Thank you.

**Comment by sayali-MSFT** [comment] 2022-01-13 11:26
@joschi27  - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment] 2022-01-13 11:58
@joschi27 - We are tried to repro the scenario, But as you mention in issue 
On mobile, the image is clickable and opens in a separate window -this is happen with all type of images.
if you click on the image(profile photo) which are on this adaptive card. which is also open in new Window.
![adptive](https://user-images.githubusercontent.com/93527375/149323937-9ba8ba92-9098-4fa6-8086-e9dfb5d53544.png)

we are also tried with `selectAction `. It's working fine with (Web, Desktop, Mobile).Could you please check it once or Could you please share steps you followed so that we can repro it at our end.
`{ 
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json", 
"type": "AdaptiveCard", 
"version": "1.4", 
"body": [
     { "type": "TextBlock", 
       "text": "Image", 
       "weight": "bolder", 
       "size": "large"
     }, 
     {
       "type": "Image", 
       "url": "https://adaptivecards.io/content/cats/1.png", 
        "size": "small",
        "selectAction": {
        "type": "Action.OpenUrl",
        "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
      }
     } 
       ] 
}`

**Comment by sayali-MSFT** [comment] 2022-01-18 04:35
@joschi27 - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Closed** 2022-01-24 13:00 UTC
Labels: teams-developer-support, needs-author-feedback, status-no-recent-activity

**Comment by joschi27** [comment] 2022-01-31 08:08
Hi,

Sorry for the late reply. I just wanted to show you that there is inconsistent behaviour across different platforms - teams behaves differently on mobile than on web for images. There is a workaround, yes, but I think all platforms should implement the adaptive cards correctly.

**Comment by v-chetsh** [comment] 2022-02-06 19:07
@joschi27 - I think, this is by design currently.
Could you please raise a user voice here: https://microsoftteams.uservoice.com/forums/555103-public/filters/new

**Comment by joschi27** [comment] 2022-02-22 09:29
On future bugs that I find should I just raise a uservoice instead of writing a github issue?

**Comment by v-chetsh** [comment] 2022-02-22 09:32
@joschi27 - If your issue is known and by design, you can raise the user voice.
For other issues, you can raise GitHub issue.
