### ISSUE TITLE
Issue with deep link to group chat

### ISSUE THREAD

**Issue by shivajivarma** [MicrosoftDocs/msteams-docs#2180] opened 2020-10-12 10:27 UTC
Actual: If one of the users in deep link, does not have account in teams, then deep does not work, it simply opens teams chat window.

Expecting: If one of the users does not have account, omit him, and initial chat for other users.

Example URL:
https://teams.microsoft.com/l/chat/0/0?users=vishal@hydwizards.onmicrosoft.com,admin@hydwizards.onmicrosoft.com,itil@hydwizards.onmicrosoft.com,invalid@hydwizards.onmicrosoft.com&topicName=hello

Here invalid@hydwizards.onmicrosoft.com does not have an account.

**Comment by Trinetra-MSFT** [comment] 2020-10-13 06:07
@shivajivarma, We can repro this at our end when user don't have account deep linking to chat goes to default new chat.

**Comment by shivajivarma** [comment] 2020-10-13 12:12
@Trinetra-MSFT thanks for confirming. Was expecting deep link to initiate a chat by omitting invalid ids. 

Opening default new chat is creating bad user experience.

**Comment by Trinetra-MSFT** [comment] 2020-10-13 12:44
@shivajivarma , Yes let me confirm this with our engineering team if it is by design or if it requires a fix I will file a Bug for this

**Comment by Trinetra-MSFT** [comment] 2020-11-12 09:32
@shivajivarma , We are working on this issue, There is feature raised to handle this scenario which is fixed in ring R0 we will let you know once this will be deployed to GA. Please feel free to reopen if you have further query on this

**Closed by Trinetra-MSFT** 2020-11-12 09:32 UTC
Labels: needs-triage :mag:, teams-developer-support

**Comment by Nikitha-MSFT** [comment] 2021-06-25 07:51
Bug is Resolved now, we have tested this at our end, could you please also check and confirm?
