### ISSUE TITLE
Customise (Disable) adaptive card messages in teams

### ISSUE THREAD

**Issue by astuj** [MicrosoftDocs/msteams-docs#5788] opened 2022-04-26 06:44 UTC
Hi, Is there a way to customise this default message or disable it in teams.

<img width="522" alt="Screenshot 2022-04-26 at 12 12 47 PM" src="https://user-images.githubusercontent.com/20801184/165237995-856872e3-b75c-4937-96d4-d891393a6432.png">

**Comment by Prasad-MSFT** [comment] 2022-04-26 07:20
@astuj - There doesn't seem to be any way to disable it. This is by design

**Comment by astuj** [comment] 2022-04-26 07:22
@Prasad-MSFT - Is there a way to customise the message or change the language of the message?

**Comment by Prasad-MSFT** [comment] 2022-04-26 08:39
@astuj - There is no way to customize this message

**Comment by astuj** [comment] 2022-04-28 10:04
@Prasad-MSFT - After changing the teams app language I receive the message in that language. 
<img width="519" alt="Screenshot 2022-04-28 at 3 32 48 PM" src="https://user-images.githubusercontent.com/20801184/165729124-f142bfbb-35a0-4d5e-9429-c3e98360caff.png">

Is there a way I can change the language of the card message without changing the teams language?

**Comment by v-chetsh** [comment] 2022-05-05 17:00
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2022-05-05 17:00 UTC
Labels: teams-developer-support
