### ISSUE TITLE
Hey folks, 

### ISSUE THREAD

**Issue by UpulieHan** [MicrosoftDocs/msteams-docs#2257] opened 2020-10-31 03:21 UTC
Can we have any apps to refer the video feed in video calls? Is there any available apps that has used the feature? 

Cheers,

Upulie.

**Comment by Abhijit-MSFT** [comment] 2020-11-01 18:26
Duplicate of [this](https://github.com/MicrosoftDocs/msteams-docs/issues/2256)
closing this.

**Closed by Abhijit-MSFT** 2020-11-01 18:26 UTC
Labels: needs-triage :mag:, teams-developer-support
