### ISSUE TITLE
No animation or effect when clicking container with selectAction in adaptive card

### ISSUE THREAD

**Issue by qjkobe** [MicrosoftDocs/msteams-docs#9259] opened 2023-08-18 08:58 UTC
Let'use adaptive card json to reproduce:
```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.5",
    "body": [
        {
            "type": "Container",
            "items": [
                {
                    "type": "TextBlock",
                    "text": "Click",
                    "wrap": true
                }
            ],
            "selectAction": {
                "type": "Action.Submit"
            }
        }
    ]
}
```
In https://adaptivecards.io/designer/, it will show a shadow when I hover on it or click it:
<img width="513" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/28c70992-3caa-49e4-9c67-57d6aa43634b">
But in teams, it will show no animation or css style when I hover on it or click it:
<img width="438" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/16449598/19373fad-e671-4f2a-84cf-f1111018d471">

You can try yourself to reproduce this problem. Thank you.

**Comment by Nivedipa-MSFT** [comment] 2023-08-18 09:45
@qjkobe - We have tested this at our end and able to repro your issue. We have raised a bug for the same.
We will let you know once we get any updates on it.

Teams:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/9d17f439-916f-4f1e-935f-c23e658be423)

Adaptive card designer:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/92150070/c53deb31-1ce5-44e6-9227-962b11a9ac78)

**Comment by Nivedipa-MSFT** [comment] 2023-09-14 11:55
@qjkobe - We received confirmation from the engineering team stating that this behavior is by design. Hovering effects are not currently supported.

**Comment by Nivedipa-MSFT** [comment] 2023-09-14 11:55
@qjkobe - We are closing this issue for now. Please feel free to reopen if required.

**Closed by Nivedipa-MSFT** 2023-09-14 11:55 UTC
Labels: teams-developer-support, bug
