### ISSUE TITLE
VS2019? Or maybe something else...

### ISSUE THREAD

**Issue by stratospheres** [MicrosoftDocs/msteams-docs#697] opened 2019-05-30 23:03 UTC
I get no further than cloning the repo and pressing F5. When I do, I immediately get the following (on a machine with VS2019 only, and the project cloned on the D: drive):
```
[DirectoryNotFoundException: Could not find a part of the path 'D:\dev\sandboxes\MicrosoftTeamsSandbox\msteams-samples-hello-world-csharp\Microsoft.Teams.Samples.HelloWorld.Web\bin\roslyn\csc.exe'.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +219
   System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +776
   System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share) +65
   Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.get_CompilerName() +91
   Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.FromFileBatch(CompilerParameters options, String[] fileNames) +656
   Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.CompileAssemblyFromFileBatch(CompilerParameters options, String[] fileNames) +187
   System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromFile(CompilerParameters options, String[] fileNames) +24
   System.Web.Compilation.AssemblyBuilder.Compile() +950
   System.Web.Compilation.BuildProvidersCompiler.PerformBuild() +10201809
   System.Web.Compilation.ApplicationBuildProvider.GetGlobalAsaxBuildResult(Boolean isPrecompiledApp) +10106756
   System.Web.Compilation.BuildManager.CompileGlobalAsax() +44
   System.Web.Compilation.BuildManager.EnsureTopLevelFilesCompiled() +260

[HttpException (0x80004005): Could not find a part of the path 'D:\dev\sandboxes\MicrosoftTeamsSandbox\msteams-samples-hello-world-csharp\Microsoft.Teams.Samples.HelloWorld.Web\bin\roslyn\csc.exe'.]
   System.Web.Compilation.BuildManager.ReportTopLevelCompilationException() +62
   System.Web.Compilation.BuildManager.EnsureTopLevelFilesCompiled() +435
   System.Web.Compilation.BuildManager.CallAppInitializeMethod() +33
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +563

[HttpException (0x80004005): Could not find a part of the path 'D:\dev\sandboxes\MicrosoftTeamsSandbox\msteams-samples-hello-world-csharp\Microsoft.Teams.Samples.HelloWorld.Web\bin\roslyn\csc.exe'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +10075108
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +95
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254
```

![image](https://user-images.githubusercontent.com/1381129/58670652-abf37100-82f4-11e9-8a04-052c0e001111.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cd21c7-e87c-3c5b-7574-998a355f9f08
* Version Independent ID: 5e312707-facc-03fc-af59-90267d0c7b8a
* Content: [Get started with C#/.NET - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/get-started-dotnet-app-studio#feedback)
* Content Source: [msteams-platform/get-started/get-started-dotnet-app-studio.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/get-started/get-started-dotnet-app-studio.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment] 2019-05-31 06:25
Could you please delete your packages folder and restore packages one more time? Duplicate of https://github.com/MicrosoftDocs/msteams-docs/issues/257#issuecomment-428655232

**Comment by stratospheres** [comment] 2019-05-31 15:34
Didn't work by just deleting packages and trying again.

However, deleting packages and then doing this in package manager console...

```
update-package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r
```

...and then running again works. Thanks!

**Closed** 2019-06-03 04:10 UTC
