### ISSUE TITLE
O365 GCC customers need an extra step

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/msteams-docs#4517] opened 2021-11-04 15:23 UTC
In GCC, there is an additional step needed to make an incoming webhook work. Connectors are disabled by default, so you will have to enable them in the tenant first: https://pscons.de/teams/ms-teams-enabling-incoming-webhook/

For Office 365 Government (GCC) customers, you must first enable connectors using the [Exchange Online cmdlets](https://docs.microsoft.com/en-us/powershell/module/exchange/set-organizationconfig?view=exchange-ps):

`Set-OrganizationConfig -ConnectorsEnabled $True`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff2a84-a8bc-9259-d37d-622b102df75b
* Version Independent ID: e3b53e27-2946-189c-623b-9df704ea8f12
* Content: [Create an Incoming Webhook - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment] 2021-11-05 06:10
We are looking into it, I will get back to you soon

Thanks

**Comment by HunaidHanfee-MSFT** [comment] 2021-11-09 04:06
The steps to enable and disable is mention here -  
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating#commands-to-enable-or-disable-connectors

I am confirming with the internal team, about this behavior if this is by design and we will act on the docs accordingly.

Thanks

**Comment by HunaidHanfee-MSFT** [comment] 2021-11-09 05:30
This is already mention in the document for connectors - 
Please check here - 
https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-creating#enable-or-disable-connectors-in-teams
![image](https://user-images.githubusercontent.com/64194049/140867837-817a59bb-fc14-4d41-8061-df1b8bef12dc.png)

Please let us know if you have any query. Else we will close it. 
Thanks

**Comment by HunaidHanfee-MSFT** [comment] 2021-11-09 17:29
We are closing this is issue as it is already mention in the documentation.
Feel free to reopen the issue, if you have any query.

**Closed by HunaidHanfee-MSFT** 2021-11-09 17:29 UTC
Labels: teams-developer-support, needs-triage :mag:
