### ISSUE TITLE
Unable open taskmodule popup in ms teams bot

### ISSUE THREAD

**Issue by Raveendra123** [MicrosoftDocs/msteams-docs#841] opened 2019-07-29 09:36 UTC
Hello ,
I am running with issue we are using task module with deep link for upload link in adaptive card .once click that link it will open upload popup in teams bot but it is not opening in web browser teams and desktop teams app.
the below URL used to redirecting on upload link click.
https://teams.microsoft.com/l/task/6132add7-9049-472d-a329-de6290441c00?url=https%3A%2F%2Ficebreaker-y5l22i4ytireq.azurewebsites.net%2FUpload%2FUpload&height=450&width=510&title=Upload&completionBotId=6132add7-9049-472d-a329-de6290441c00
Note : it is working for some of the users but not for all.

can you please help me to get the resolution .Is it issue with users or teams app access related permissions. if you need more details please let me know
Thanks
Raveendra

**Comment by Wajeed-msft** [comment] 2019-07-29 13:16
Duplicate of https://github.com/MicrosoftDocs/msteams-docs/issues/840

**Closed by Wajeed-msft** 2019-07-29 13:16 UTC
