### ISSUE TITLE
[MS Teams][Adaptive Cards Action.ToggleVisibility in Dark Theme] [Other action buttons turns white when Action.ToggleVisibility is clicked in Dark Theme MS Teams]

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4777] opened 2021-12-02 21:43 UTC
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/4883 

**Details from original post:**
[MS Teams][Desktop App]
[Adaptive Cards 1.2]

# Platform
Javascript

# Version of SDK
* AdaptiveCards 2.1.0
* AdaptiveCards.Templating 1.1.0
* AdaptiveExpressions 4.10.3
* Microsoft.Bot.Builder 4.10.3

# Details

When in Dark Theme, clicking a button Action.ToggleVisibility turns the background for other buttons to semitransparent white.

![image](https://user-images.githubusercontent.com/72416404/95133635-33c47780-0794-11eb-8654-8eec79f8d13d.png)

Here my card template:
```
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "Container",
            "style": "default",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.ToggleVisibility",
                            "title": "Reply",
                            "targetElements": [
                                "replyContainer",
                                {
                                    "elementId": "changeStatusContainer",
                                    "isVisible": false
                                }
                                
                            ]
                        },
                        {
                            "type": "Action.ToggleVisibility",
                            "title": "Change Status",
                            "targetElements": [
                                {
                                    "elementId": "replyContainer",
                                    "isVisible": false
                                },
                                {
                                    "elementId": "changeStatusContainer",
                                    "isVisible": true
                                }
                            ]
                        },
                        {
                            "type": "Action.OpenUrl",
                            "title": "Open",
                            "url": "${uri}"
                        }
                    ]
                },
                {
                    "type": "Container",
                    "style": "default",
                    "items": [
                        {
                            "type": "Container",
                            "id": "replyContainer",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "Reply to Thread",
                                    "weight": "Bolder",
                                    "wrap": true
                                },
                                {
                                    "type": "Input.Text",
                                    "id": "comment",
                                    "placeholder": "Add a comment",
                                    "isMultiline": true
                                },
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.Submit",
                                            "title": "OK",
                                            "id": "AddComment",
                                            "data": {
                                                "thread": "${id}",
                                                "commandId": "AddComment"
                                            }
                                        }
                                    ]
                                }
                            ],
                            "bleed": "${bleedActionForm}",
                            "style": "emphasis",
                            "isVisible": "${initVisiblityReplyForm}"
                        },
                        {
                            "type": "Container",
                            "id": "changeStatusContainer",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "Change Status",
                                    "weight": "Bolder",
                                    "wrap": true
                                },
                                {
                                    "type": "Input.ChoiceSet",
                                    "choices": [
                                        {
                                            "$data": "${statusOptions}",
                                            "title": "${Value}",
                                            "value": "${Id}"
                                        }
                                    ],
                                    "value": "${statusId}",
                                    "id": "changeStatusOptions",
                                    "style": "compact"
                                },
                                {
                                    "type": "ActionSet",
                                    "actions": [
                                        {
                                            "type": "Action.Submit",
                                            "title": "OK",
                                            "id": "ChangeStatus",
                                            "data": {
                                                "thread": "${id}",
                                                "commandId": "ChangeStatus"
                                            }
                                        }
                                    ]
                                }
                            ],
                            "bleed": true,
                            "style": "emphasis",
                            "isVisible": false
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}
```---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment] 2021-12-03 11:09
@ccdev1205 - Are you still facing the issue?

**Comment by ccdev1205** [comment] 2021-12-06 14:03
Hi, 
Sorry for the late response. 
I cannot reproduce this issue anymore. 
Thanks, Christine 


 
 
  On Mon, 6 Dec 2021 at 10:00 pm, ***@***.***> wrote:   


This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for 3 days. It will be closed if no further activity occurs within 3 days of this comment.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Prasad-MSFT** [comment] 2021-12-06 14:07
@ccdev1205 - Thanks for your confirmation. We are closing this issue. Please feel free to re-open if needed.

**Closed by Prasad-MSFT** 2021-12-06 14:07 UTC
Labels: teams-developer-support, needs-author-feedback
