### ISSUE TITLE
Can't start calls in chrome 

### ISSUE THREAD

**Issue by MahmoudAbdAlKareem** [MicrosoftDocs/msteams-docs#520] opened 2019-03-24 14:13 UTC
I'm using chrome browser to open my Microsoft teams account, when I click to make a call with a contact, it shows a popup that I should use chrome or any supported browser while I'm using chrome. 
Screenshot attached. 

![image](https://user-images.githubusercontent.com/16404421/54880651-ab031680-4e4f-11e9-893e-82b5ec63ddb0.png)

**Comment by Wajeed-msft** [comment] 2019-03-25 06:37
Duplicate of https://github.com/MicrosoftDocs/msteams-docs/issues/500

The error message is wrong, but the feature actually isn't yet available in Chrome. It should work in Chrome in the very near future.

**Closed by Wajeed-msft** 2019-03-25 06:37 UTC
