### ISSUE TITLE
[Rendering] Action.ToggleVisibility is not working on teams web or desktop

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8245] opened 2023-03-06 19:17 UTC
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/8344 

**Details from original post:**
### Target Platforms

WPF

### SDK Version

1.4

### Application Name

Microsoft Teams

### Problem Description

When clicked on Image to process Action.ToggleVisibility the chevron does not expand.
But when clicked on the chevron and then clicking on another actionSet action.submit in this case, triggers the toggle.

Please see schema, schema was copied from https://adaptivecards.io/samples/ExpenseReport.html

The same schema works well in designer. But fails in Microsoft team desktop client as well as Web client

**_NOTE:_** the same schema worked a week or ~12 days ago. Facing this issue from last week.

### Screenshots

![adaptive_card_issue](https://user-images.githubusercontent.com/36010645/223088173-a2d7a353-b9ed-47a4-adbf-e32838f7fc90.gif)

### Card JSON

```JSON
{
            "type": "Container",
            "items": [
                {
                    "type": "ColumnSet",
                    "columns": [
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "06-21",
                                    "wrap": true
                                }
                            ],
                            "width": "auto"
                        },
                        {
                            "type": "Column",
                            "spacing": "Medium",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "Excess Baggage Cost",
                                    "wrap": true
                                }
                            ],
                            "width": "stretch"
                        },
                        {
                            "type": "Column",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "$50.38",
                                    "wrap": true
                                }
                            ],
                            "width": "auto"
                        },
                        {
                            "type": "Column",
                            "spacing": "Small",
                            "selectAction": {
                                "type": "Action.ToggleVisibility",
                                "title": "expand",
                                "targetElements": [
                                    "cardContent2",
                                    "chevronDown2",
                                    "chevronUp2"
                                ]
                            },
                            "verticalContentAlignment": "Center",
                            "items": [
                                {
                                    "type": "Image",
                                    "id": "chevronDown2",
                                    "url": "https://adaptivecards.io/content/down.png",
                                    "width": "20px",
                                    "altText": "Details collapsed"
                                },
                                {
                                    "type": "Image",
                                    "id": "chevronUp2",
                                    "url": "https://adaptivecards.io/content/up.png",
                                    "width": "20px",
                                    "altText": "Details expanded",
                                    "isVisible": false
                                }
                            ],
                            "width": "auto"
                        }
                    ]
                },
                {
                    "type": "Container",
                    "id": "cardContent2",
                    "isVisible": false,
                    "items": [
                        {
                            "type": "Container",
                            "items": [
                                {
                                    "type": "Container",
                                    "items": [
                                        {
                                            "type": "Input.Text",
                                            "id": "comment2",
                                            "label": "Add your comment here"
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "type": "Container",
                            "items": [
                                {
                                    "type": "ColumnSet",
                                    "columns": [
                                        {
                                            "type": "Column",
                                            "items": [
                                                {
                                                    "type": "ActionSet",
                                                    "actions": [
                                                        {
                                                            "type": "Action.Submit",
                                                            "title": "Send",
                                                            "data": {
                                                                "id": "_qkQW8dJlUeLVi7ZMEzYVw",
                                                                "action": "comment",
                                                                "lineItem": 1
                                                            }
                                                        }
                                                    ]
                                                }
                                            ],
                                            "width": "auto"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by zeroshell09** [comment] 2023-03-07 15:02
Hello , 

I'm facing the same issue. Any update on that ? 

Thanks

**Comment by Wajeed-msft** [comment] 2023-03-07 15:23
@zeroshell09 - we will try to repro this at our end and let you know the updates.

**Comment by duncan-at-hicksons** [comment] 2023-03-07 23:46
Same here.

**Comment by zaclimon** [comment] 2023-03-22 17:30
Can confirm it's also happening on my side with a form with only one action:

https://user-images.githubusercontent.com/1891861/226988893-b737f21b-6c02-4f79-85f2-0692567e5b08.mp4



```json
{
    "type": "AdaptiveCard",
    "version": "1.3",
    "backgroundImage": {
        "url": ""
    },
    "body": [
        {
            "type": "TextBlock",
            "text": "**Test title**",
            "wrap": true
        },
        {
            "type": "Container",
            "minHeight": "16px"
        },
        {
            "type": "Container",
            "items": [
                {
                    "type": "Container",
                    "items": [
                        {
                            "type": "ColumnSet",
                            "columns": [
                                {
                                    "type": "Column",
                                    "width": "auto",
                                    "items": [
                                        {
                                            "type": "TextBlock",
                                            "weight": "Bolder",
                                            "text": "Action Title"
                                        }
                                    ],
                                    "verticalContentAlignment": "Center"
                                },
                                {
                                    "id": "chevronDown0",
                                    "type": "Column",
                                    "width": "stretch",
                                    "items": [
                                        {
                                            "type": "Image",
                                            "url": "https://cdn.icon-icons.com/icons2/933/PNG/512/round-info-button_icon-icons.com_72584.png",
                                            "selectAction": {
                                                "type": "Action.ToggleVisibility",
                                                "targetElements": [
                                                    "cardContent0",
                                                    "chevronUp0",
                                                    "chevronDown0"
                                                ],
                                                "title": "collapse"
                                            },
                                            "altText": "collapsed",
                                            "width": "16px"
                                        }
                                    ],
                                    "verticalContentAlignment": "Center"
                                },
                                {
                                    "id": "chevronUp0",
                                    "type": "Column",
                                    "width": "stretch",
                                    "items": [
                                        {
                                            "type": "Image",
                                            "url": "https://cdn.icon-icons.com/icons2/2248/PNG/512/chevron_up_icon_136782.png",
                                            "selectAction": {
                                                "type": "Action.ToggleVisibility",
                                                "targetElements": [
                                                    "cardContent0",
                                                    "chevronUp0",
                                                    "chevronDown0"
                                                ],
                                                "title": "expand"
                                            },
                                            "altText": "expanded",
                                            "width": "16px"
                                        }
                                    ],
                                    "verticalContentAlignment": "Center",
                                    "isVisible": false
                                },
                                {
                                    "type": "Column",
                                    "width": "100px",
                                    "items": [
                                        {
                                            "type": "ActionSet",
                                            "actions": [
                                                {
                                                    "type": "Action.Submit",
                                                    "data": {
                                                        "Token": "test123"
                                                    },
                                                    "title": "Action",
                                                    "associatedInputs": "none"
                                                }
                                            ]
                                        }
                                    ],
                                    "verticalContentAlignment": "Center"
                                }
                            ]
                        },
                        {
                            "type": "Container",
                            "id": "cardContent0",
                            "items": [
                                {
                                    "type": "TextBlock",
                                    "text": "Description",
                                    "wrap": true
                                }
                            ],
                            "isVisible": false
                        }
                    ]
                }
            ]
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
```

**Comment by Meghana-MSFT** [comment] 2023-06-26 07:38
Fix is rolled out as part of Teams client version 1.6.00.6754. This should be available globally. Could you please update the Teams client and let me know if you are still experiencing this issue. Thanks

**Comment by zaclimon** [comment] 2023-06-26 20:04
Can confirm that the issue is fixed on my end with Teams version 1.6.00.16472.

However, it is still happening with Teams on the Web. It's possible that the update is rolling out there as well.

**Comment by Meghana-MSFT** [comment] 2023-06-27 06:59
@zaclimon - We checked this in web and it is working fine on web as well, could you please share JSON of the card where you see the issue.


https://github.com/MicrosoftDocs/msteams-docs/assets/81138249/1c1c2246-1315-416e-93c2-714bfebbbadc

**Comment by zaclimon** [comment] 2023-06-27 17:37
@Meghana-MSFT Actually I just retried this morning on the web and it works fine. Probably there was a rollout happening. For the info, I used the [JSON I posted above](https://github.com/MicrosoftDocs/msteams-docs/issues/8245#issuecomment-1479985837).

In that case, please disregard my comment above! 🙂

**Closed** 2023-07-04 01:01 UTC
Labels: teams-developer-support, bug, needs-author-feedback, status-no-recent-activity
