### ISSUE TITLE
Chat created with graph api is opening random chat in Microsoft teams (web)

### ISSUE THREAD

**Issue by kaursimransidhu1** [MicrosoftDocs/msteams-docs#5510] opened 2022-03-22 08:55 UTC
When we create a Microsoft Teams chat with 'Create Chat api' we get Chat URL in response. When we open the URL it opens a random chat in teams rather than newly created chat.  Below is the recording

https://user-images.githubusercontent.com/102144967/159443375-17f2b5e4-7929-47e8-a865-3cf45eb520bb.mp4

**Comment by Meghana-MSFT** [comment] 2022-03-22 10:59
We are looking into this issue, we will update you.

**Comment by Meghana-MSFT** [comment] 2022-03-22 17:08
We have tried this issue on Windows machine, and it is working fine. It is opening the correct group chat. Attaching a video for your reference. Have you tried this in Mac Machine?

https://user-images.githubusercontent.com/81138249/159536259-c72719cc-a3d6-4826-8522-8c146ee2f159.mp4

**Comment by Meghana-MSFT** [comment] 2022-03-24 14:17
@kaursimransidhu1 - Could you please provide the above asked details?

**Comment by kaursimransidhu1** [comment] 2022-03-29 09:37
Hi, 
I tried in Mac OS.

Please try when no other teams tab is open, and teams is opened for the first time when you go to webUrl of chat. If Teams is already opened in any other tabs then it works fine, the issue is for the very first opening of teams only.

**Comment by Meghana-MSFT** [comment] 2022-03-30 06:30
@kaursimransidhu1 - We tried this in Mac OS, it is working fine in Mac OS as well. We checked in this version -  Version: 12.3(21E230).

Could you please confirm if you are getting this issue in other Mac machines as well? Also please share the version details.

**Comment by s1mran** [comment] 2022-04-01 15:32
Hi @Meghana-MSFT , 

as i mentioned pls try to close all teams open tabs and open the URL such that it is the first tab of teams opening in the chrome window, then issue will happen, if there are already 1-2 or more tabs open of teams web client then it will open correct chat, issue is happening when we are opening teams as well for the first time with the web URL

**Comment by kaursimransidhu1** [comment] 2022-04-01 15:35
Hi @Meghana-MSFT ,

as i mentioned pls try to close all teams open tabs and open the URL such that it is the first tab of teams opening in the chrome window, then issue will happen, if there are already 1-2 or more tabs open of teams web client then it will open correct chat, issue is happening when we are opening teams as well for the first time with the web URL

**Comment by Meghana-MSFT** [comment] 2022-04-01 18:11
As I have already mentioned in my previous comment, we closed all Teams tabs and kept only graph explorer tab open.

**Comment by kaursimransidhu1** [comment] 2022-04-02 05:55
Hi,

As you can see in the recording, I am facing the issue clearly. So if you can reproduce and help, that will be great.

My mac version is 11.6.4

Thanks
Simran

**Comment by Meghana-MSFT** [comment] 2022-04-05 13:29
We are checking this internally, we will update you.

**Comment by s1mran** [comment] 2022-04-27 09:17
Hi, any update on this ?

**Comment by Meghana-MSFT** [comment] 2022-04-27 13:13
I will check with team and get back to you.

**Comment by Meghana-MSFT** [comment] 2022-04-28 13:25
We have raised a bug for this, currently we do not have any updates. We will let you know if there is any.

**Comment by Meghana-MSFT** [comment] 2022-05-31 08:40
@s1mran - Could you please let us know if you are still facing this issue? As this seems to be a client error.

**Closed** 2022-06-06 19:01 UTC
Labels: teams-developer-support, needs-author-feedback, status-no-recent-activity

**Comment by ChetanSharma-msft** [comment] 2022-07-22 05:51
@s1mran - We have confirmed with engineering team and looks like it is the Teams client issue.
Can you please try updating the Teams client and check it once?
