### ISSUE TITLE
rawLocalTimestamp time zone is not updated on time zone change

### ISSUE THREAD

**Issue by clearab** [MicrosoftDocs/msteams-docs#1950] opened 2020-08-05 18:06 UTC
From SiarheiKuchukBelitsoft:

Hello

I have an issue with extracting time zone from rawLocalTimestamp for Node BotFramework SDK 4.9.3
For example I'm in Minsk.
That code
(context.activity).rawLocalTimestamp
shows
...19:00+03:00

If i change the time zone in Windows Clock to UTC+01
and then send message to Bot, it will get from TurnContext
...19:01+03:00

But if i restart Teams Desktop app, it works fine, i.e. it will show
...19:01+01:00

Can you please adjust time zone on each message in Teams Desktop app.

Another big issue with rawLocalTimestamp - that after update Bot to SDK with that feature, users have to relogin to Teams so bot will start getting on backend that field. Please fix it,because noone from customers is going to relogin on bot update!

**Comment by Nikitha-MSFT** [comment] 2020-08-06 06:55
We could able to reproduce the issue on our side raised a bug.

**Comment by Nikitha-MSFT** [comment] 2020-11-03 11:29
Restart of Teams is required after timezone is changed. Please ensure Teams was restarted. This is by design

**Comment by ChetanSharma-msft** [comment] 2023-05-10 11:42
We are closing this issue for now, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2023-05-10 11:42 UTC
Labels: teams-developer-support, bug
