### ISSUE TITLE
Teams Bot 1-1 ConversationUpdate Events

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/msteams-docs#1354] opened 2020-02-12 07:59 UTC
I'm struggling with the same situation in a few different Teams bots I've written, and trying to determine if I've just misunderstood the docs. When the bot is side-loaded to a test tenant, and then added to a 1-1 conversation, I'm getting two conversationUpdate/MemberAdded events. However, BOTH events contain BOTH user (i.e. end user and bot). I would have expected either one event, with both Members, or two events, one with each user, but not the SAME event 100% duplicated. Is this what is meant above by "It also receives an update when it has been added for the first time specifically for personal conversations."? If so, how do I deal with this scenario, as there's no way to differentiate the two duplicated events. I've posted more on SO, but with no responses: https://stackoverflow.com/questions/60140079/microsoft-teams-side-loaded-app-multiple-conversationupdate-events-firing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da6a6eb-8756-fffd-ecc3-07cde897e709
* Version Independent ID: 72686dc8-d677-9b8d-2405-7684d537a100
* Content: [Handle bot events - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-notifications#team-member-or-bot-addition)
* Content Source: [msteams-platform/resources/bot-v3/bots-notifications.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/resources/bot-v3/bots-notifications.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment] 2020-02-13 06:23
Duplicate of #1355

**Closed by Gousia-MSFT** 2020-02-13 06:23 UTC
