### ISSUE TITLE
Must be signed in to Teams for this to work on website?

### ISSUE THREAD

**Issue by jkipk** [MicrosoftDocs/msteams-docs#1318] opened 2020-01-31 18:26 UTC
Running a WordPress site, using New Edge Stable, and I have the basics of the sharing button working, but only if I"m signed in via the web to Teams. IE - no sharing button if I sign out of Teams and then hard refresh the browser. Is this correct?
I'm just getting started with this and haven't dug in too deep, but as many ppl use the Teams app, we won't be able to offer the chance to share if they're not logged in via the browser :(
Apologies in advance if I"m missing something.

**Comment by jkipk** [comment] 2020-02-03 18:16
Still working through this, but it's a make or break issue for us: I have the Share to Teams icon showing and working correctly, however if either a) I sign out of Teams on the web, and then refresh the browser, or b) click on the icon to open the Share to Teams dialog, the icon then disappears. I can apparently get it back by refreshing, but it's not an experience (Teams icon sometimes there, sometimes not) that I want to introduce.
Is there a way to implement Share to Teams where the icon is always present?

**Comment by Subhasish-msft** [comment] 2020-02-05 03:20
@jkipk, Are you using teams icon image in your WordPress page, on click it should redirect to MS Teams? If yes, then can you please share some screenshots and how you are implementing it.

**Comment by jkipk** [comment] 2020-02-05 16:02
Thanks, I think I have this worked out. I am using the Teams icon (by including the Teams script in the WordPress header and then adding this line to my social media unordered list:
           <li class = "teams-share"><a class="teams-share-button social-icon ms-depth-4" data-msg-text = "From OnMSFT.com" data-href = "'.$onmsftTeams.'" target="_blank" title="Share to Teams" data-icon-px-size="48"></a></li>

I think the issue has been mainly with this being a staging site, behind a “down for maintenance” wall (must be signed in to see).

The problem still exists though in non-compatible browsers, specifically as I am applying css borders to my social media icons.

[A close up of text on a white background  Description automatically generated]

In IE, for example (although your documentation doesn’t mention it, the experience seems to work fine in Firefox), I get this:

[cid:image002.jpg@01D5DBFA.8CF87DE0]

(this is also the experience I was getting when the icon didn’t load in Edge/Chrome).

However I have added a media query:
li.teams-share {display:none !important;}
@media screen and (-webkit-min-device-pixel-ratio:0) {
  li.teams-share {display:inline-block !important;}
}
to set the li to display:none unless a Chrome-like browser is detected. This seems to work.

Thanks,
kip



kip

**Comment by Subhasish-msft** [comment] 2020-02-06 17:02
@jkipk, Thanks for your explanation. As the issue is resolved, I am closing this thread. If you get any issue related to Teams, you can re-open this or create a new one. 

Thanks,
Subhasish

**Closed** 2020-02-06 18:40 UTC
