### ISSUE TITLE
404 not found documentation URL issue

### ISSUE THREAD

**Issue by Trinetra-MSFT** [MicrosoftDocs/msteams-docs#2509] opened 2020-12-24 08:59 UTC
Please fix the hyperlinks issue for below cases:

**1. Install for user:**
![image](https://user-images.githubusercontent.com/50989436/103076738-6e4fea80-45f4-11eb-9f73-923948035680.png)
**_Link needs to added:_**[https://docs.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-1.0&tabs=http]( https://docs.microsoft.com/en-us/graph/api/userteamwork-post-installedapps?view=graph-rest-1.0&tabs=http)

**2.List Apps Installed for User**
![image](https://user-images.githubusercontent.com/50989436/103076417-b3bfe800-45f3-11eb-89ff-2838b978ce40.png)
**_Link needs to added:_**: [https://docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-1.0&tabs=http](https://docs.microsoft.com/en-us/graph/api/userteamwork-get-installedapps?view=graph-rest-1.0&tabs=http)
**3. List Apps in Teams**
![image](https://user-images.githubusercontent.com/50989436/103076561-04cfdc00-45f4-11eb-8329-0db7b5424ea1.png)
 _**Link need to be added:**_:[https://docs.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&tabs=http]( https://docs.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&tabs=http 
)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893c2c9e-10e1-dd4e-1eb4-b4e9a46a9f8d
* Version Independent ID: 5f41c382-377c-6c9b-4932-65853675c4ad
* Content: [Use Microsoft Graph to enable proactive bot installation and messaging in Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=csharp)
* Content Source: [msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment] 2020-12-24 09:05
duplicate of https://github.com/MicrosoftDocs/msteams-docs/issues/2503

**Comment by KirtiPereira** [comment] 2020-12-28 05:15
Closed the issue through:
https://github.com/MicrosoftDocs/msteams-docs/pull/2504

**Closed by KirtiPereira** 2020-12-28 05:15 UTC
Labels: doc-bug, teams-developer-support
