### ISSUE TITLE
Fetching list of channels in a private chat

### ISSUE THREAD

**Issue by Manish-Ghumnani** [MicrosoftDocs/msteams-docs#1594] opened 2020-04-27 04:53 UTC
Is there a way to get the list of channels the user belongs to when the bot is initially installed in a private chat ?
The scenario is that - the user installs the bot to the private chat and then after performing some steps wants the bot to send a message to one of the teams channels, but there doesn't seem to be a way to fetch the team Id when the bot is in the private chat, maybe I missed something ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca47e045-6669-e130-c75a-df31ab2fa3e8
* Version Independent ID: de5e719f-c97a-0fee-c83d-f6ca176191b2
* Content: [Get Team's specific context for your bot - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=json#get-single-member-details)
* Content Source: [msteams-platform/bots/how-to/get-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/get-teams-context.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Gousia-MSFT** [comment] 2020-09-24 10:31
Duplicate of #1593

**Closed by Gousia-MSFT** 2020-09-24 10:31 UTC
Labels: needs-triage :mag:, teams-developer-support
