### ISSUE TITLE
Read and delivery receipts missing for external chats in desktop client

### ISSUE THREAD

**Issue by larsons-swt** [MicrosoftDocs/msteams-docs#1753] opened 2020-06-10 15:08 UTC
Read and delivery receipts do not show in the Windows desktop client for external chats. They do show in the iOS app for the same chat thread.

**Comment by Abhijit-MSFT** [comment] 2020-06-11 15:07
@larsons-swt, This is by design. 
You can for to [UserVoice](https://microsoftteams.uservoice.com/) and raise/vote this feature request.

**Comment by Abhijit-MSFT** [comment] 2020-06-11 15:27
@larsons-swt , Sorry, I read it wrong. Let me just cross verify.

**Comment by larsons-swt** [comment] 2020-07-15 18:25
To add on to this, pop-out chat _does_ show read receipts in the Windows desktop client

**Comment by ChetanSharma-msft** [comment] 2023-05-05 13:44
We are closing this issue, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2023-05-05 13:44 UTC
Labels: feature-request, needs-attention
