### ISSUE TITLE
Given App Manifest Is Not Working For Teams Tab In Share Point

### ISSUE THREAD

**Issue by Mohammed-MSFT** [MicrosoftDocs/msteams-docs#10674] opened 2024-04-04 17:21 UTC
### Type of issue

Feature doesn't work (bug)

### Feedback

We have followed the given document for "Teams Tab in share point", and found some part of the given document is not working as expected.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/73a775db-21b7-4a42-9604-3c7e3b1bbe23)

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/tabs/how-to/tabs-in-sharepoint.md

### Author

@surbhigupta

### Document Id

afcc83c4-12c0-bab6-1cec-61ac463b4f60

**Comment by Meghana-MSFT** [comment] 2024-04-05 07:43
Thank you for reporting this, we will check this and get back to you.

**Comment by ydogandjiev** [comment] 2024-04-13 01:15
@Mohammed-MSFT, can you please share your app manifest and also the code you are using the initialize the team-js library? If you are using a recent version of team-js, you will need to explicitly specify the SharePoint origins that you want your tab to work in when initializing the SDK.

For v1, that would look something like this:
```
import microsoftTeams from "@microsoft/teams-js";
microsoftTeams.initialize(() => {
  console.log("SDK initialization complete");
}, ["https://microsoft.sharepoint.com"]);
```

For v2, that would look something like this:
```
import { app } from "@microsoft/teams-js";
await app.initialize(["https://microsoft.sharepoint.com"]);
console.log("SDK initialization complete");
```

**Comment by Mohammed-MSFT** [comment] 2024-04-15 10:58
Hi @ydogandjiev 
I have tested the sample by using demo-manifest and added the following properties in the manifest under **ConfigireableTabs** section.

` "sharePointPreviewImage": "Relative path to a tab preview image for use in SharePoint — 1024px X 768",
      "supportedSharePointHosts": [
          "sharePointFullPage",
          "sharePointWebPart"
      ]`
      
<img width="722" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/302b8eaa-0bb5-4228-b845-58128deb305c">


This is the overall app manifest which is attached below.
[manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/14977848/manifest.zip)

**Regarding Code Part :** Tested using demo-manifest which code was already deployed, will check locally and update as you have suggested to use for v1 and v2 versions on above comment.

**Comment by Mohammed-MSFT** [comment] 2024-04-23 07:42
Hi @ydogandjiev 
Kindly please provide inputs on given app manifest.

**Thanks!!**

**Comment by ydogandjiev** [comment] 2024-04-24 07:23
Hey @Mohammed-MSFT, I'm able to get your app mostly working inside of SharePoint except I can't get past the config screen:
<img width="1544" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3357245/0f807f34-04c5-4e21-ab9a-9dad02601855">

I think that's because your app only relies on the getAuthToken API which doesn't work in SharePoint (and hangs indefinitely):
<img width="605" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/3357245/4737bcf7-f673-4ca3-9802-3052491f41ee">

You need to implement popup auth using the authenticate API instead. I saw your app had code for that but it seemed unused (the teamsFallbackAuth API). You can find documentation for this auth flow here:
https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-flow-tab

**Comment by Mohammed-MSFT** [comment] 2024-05-08 07:17
Hi @ydogandjiev 
Thanks for providing your input, will check this and update accordingly.

**Comment by Mohammed-MSFT** [comment] 2024-05-09 08:49
Hi @ydogandjiev

We tried as per your suggestions.

Updating teams app initialization with Share-Piont
<img width="305" alt="Test1" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/f8e26980-02ce-4fe5-8b65-3634db6b1385">

Instead of getTeamsToken, we used teamsFallbackAuth
<img width="479" alt="Test2" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/99b29748-700f-4bfb-a15f-79aa9e52a1c0">

But still unable to get the expected output.
![Screenshot 2024-05-09 124429](https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/70b1175a-7055-4671-8349-bd6abe6eb4a9)

Also tried uploading **app hello world sample** demo-manifest (which is not having any authentication)
still did not worked as expected.
 
**Please provide your suggestions** 
 
Thanks!!
 
**Demo Manifest for app hello world.**
[manifest.zip](https://github.com/MicrosoftDocs/msteams-docs/files/15259970/manifest.zip)

**Comment by Mohammed-MSFT** [comment] 2024-05-14 10:54
Hi @ydogandjiev 
Did you get a chance to check above manifest's ?

Please provide your inputs.

Thanks!!

**Comment by ydogandjiev** [comment] 2024-05-15 06:50
Hey @Mohammed-MSFT, I was able to add the Hello World sample you shared without any issue:
https://github.com/MicrosoftDocs/msteams-docs/assets/3357245/bde08f4d-683c-44ed-9bda-e39073f6601b

**Comment by Mohammed-MSFT** [comment] 2024-05-16 18:18
Hi @ydogandjiev 

App is working fine, the way you have shown in video, our concern is to work as per the document, but it is not working as expected.

**Following steps as per document**
From settings icon, select **add a page**
<img width="956" alt="1" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/44a13f24-3c03-4f23-8e76-1ac93190fe0e">

Once we hover on page it gives **plus +** icon to add an app
<img width="938" alt="2" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/6625d0d8-8393-419f-bfa0-3eba5e6d948d">
<img width="958" alt="3" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/d7850914-5c3f-4355-8ba0-b5efaa6f9f00">
App Is selected and there is no output as expected as documented.
<img width="959" alt="4" src="https://github.com/MicrosoftDocs/msteams-docs/assets/109147706/1ef450b9-3a49-4c89-a796-4993f8b8a400">

So, can you please try this at your end and provide your inputs.

**Doc Link : ** https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/tabs-in-sharepoint#use-teams-tab-in-sharepoint

**Thanks !!**

**Comment by ydogandjiev** [comment] 2024-05-21 00:34
@lucabandMSFT found a possible regression in SharePoint that is responsible for this issue. We are following up with the code owners on the fix.

**Comment by ydogandjiev** [comment] 2024-05-22 21:53
Hey @Mohammed-MSFT, we identified the regression responsible for the issue you're seeing and checked in a fix for it. The ETA for the worldwide rollout of the fix is June 3rd.

**Closed** 2024-07-11 11:54 UTC
Labels: teams-developer-support, bug, needs-attention
