### ISSUE TITLE
Loading indicator in Teams personal bot

### ISSUE THREAD

**Issue by StevieBleeds** [MicrosoftDocs/msteams-docs#4499] opened 2021-10-31 11:49 UTC
Similar to [Issue #4249](https://github.com/MicrosoftDocs/msteams-docs/issues/4249), we are seeing an issue in Teams with personal bots where the loading indicator persists and doesn't disappear. 

We've tested on four bots on two tenants and the indicator appears on all of the bots when used via the Teams desktop client. This issue doesn't present itself when used via the web version of Teams.

![spinning_wheel](https://user-images.githubusercontent.com/39305886/139581478-7f35609d-1f44-47ef-9044-d6cde7772e15.gif)

**Comment by Nivedipa-MSFT** [comment] 2021-11-01 04:57
@StevieBleeds - Could you please update the teams desktop client version and check again? If you are still facing this issue please share your Teams desktop client version.

**Comment by StevieBleeds** [comment] 2021-11-01 08:12
Sure, it's 1.4.00.26376 (64-bit) and is the latest installed version.

**Comment by Nivedipa-MSFT** [comment] 2021-11-01 10:25
@StevieBleeds - Could you please share the repro steps to try at our end?

**Comment by StevieBleeds** [comment] 2021-11-02 08:52
The issue just started happening to our bots. We haven't changed anything. I did notice that when using the _pop out app_ option in the client, the issue doesn't persist, it just appears in the main window in the teams desktop client.

We're using a mix of 1.7, 1.9 and 1.11 for our bot manifests and it's happening on all of them.

**Comment by Nivedipa-MSFT** [comment] 2021-11-03 03:47
@StevieBleeds - We will try at our end to repro this issue and update you accordingly.

**Comment by Kevbo-Kev** [comment] 2021-11-03 14:47
Thanks Stevie for starting this, I have the same exact issue and it just started yesterday. Naturally we just rolled out a custom chatbot to the company through Teams yesterday :(  The issue was not present during the dev and pilot testing of this bot. 

I just updated to the latest version but the issue remains and is affecting everyone in our company that I've spoken to. Same as Stevie, the issue only occurs when clicking the chatbot pinned on the left side of Teams. The issue is **not** present when using the chatbot from the 'Chat' section of Teams, or when using a pop-out, or when using the chatbot in the browser.

I have opened a MS support ticket for this as well:
Case #: 28239336

**Comment by StevieBleeds** [comment] 2021-11-04 06:20
The teams client is on the latest version 1.4.00.26376 (64-bit) and the issue persists. It's a conversational bot built on the Bot Framework.

**Comment by Nivedipa-MSFT** [comment] 2021-11-05 09:26
@StevieBleeds - The latest Microsoft Teams Version is 1.4.00.30066 (64-bit).Could you please try to update it.

**Comment by StevieBleeds** [comment] 2021-11-05 09:42
@Nivedipa-MSFT - I've update the client and the latest one it's installed is 1.4.00.29469 (64-bit) and the issue persists.

**Comment by huailut** [comment] 2021-11-05 13:47
Similar issue for my bot app. Perhaps it's not Teams desktop client issue. My bot app released a month ago and always kept normal. From Nov 1st, loading indicator persists in chat bot if click app icon pinned on the left side of Teams, and same issue in 'Who' app.  
My Microsoft Teams Version 1.4.00.19572 (64-bit). It was last updated on 2021/8/10.
 I have opened a MS support ticket for this as well: #28254292

**Comment by jonathanwagnerjambit** [comment] 2021-11-09 10:27
same problem... since a few days in the personal bot.
reinstall and all the other suggestions in the thread do not help. hope, that it will be fixed soon.

**Comment by StevieBleeds** [comment] 2021-11-17 18:00
This appears to be resolved in the tenants I've been using.

**Comment by Kevbo-Kev** [comment] 2021-11-17 19:01
The issue seems removed for me and others I have checked with as well. I had them update to the latest Teams client if the issue persisted and so far that seems good. Hoping this time the issue is gone for good  :)

**Comment by v-chetsh** [comment] 2021-12-22 15:13
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2021-12-22 15:13 UTC
Labels: teams-developer-support, needs-triage :mag:
