### ISSUE TITLE
Get vertical scroll bar in task module but not able to scroll the page using that.

### ISSUE THREAD

**Issue by xieofxie** [MicrosoftDocs/msteams-docs#1627] opened 2020-05-07 08:33 UTC
It looks like
![img](https://user-images.githubusercontent.com/60354515/80090247-d5586380-857c-11ea-95af-f86c74988086.png)
See issue https://github.com/microsoft/botframework-skills/issues/162

@Sujit-Gaikwad I manually created one here since I don't have the permission to transfer it.
Hope Teams's people will help you solve this.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 501d3295-997c-d252-d458-534673b36a52
* Version Independent ID: c90dcc98-df65-b45b-4f78-64d2cab91852
* Content: [What are task modules? - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/what-are-task-modules)
* Content Source: [msteams-platform/task-modules-and-cards/what-are-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/what-are-task-modules.md)
* Product: **msteams**
* GitHub Login: @clearab
* Microsoft Alias: **anclear**

**Comment by Nikitha-MSFT** [comment] 2020-05-07 09:37
I could not reproduce the issue from our side. Could you please share your manifest?

**Comment by Sujit-Gaikwad** [comment] 2020-05-07 10:05
@xieofxie thanks for your help

**Comment by Sujit-Gaikwad** [comment] 2020-05-07 10:22
@Nikitha-MSFT 
PFA 

**Bot manifest file**

[manifest .txt](https://github.com/MicrosoftDocs/msteams-docs/files/4592333/manifest.txt)

**Comment by Nikitha-MSFT** [comment] 2020-05-11 11:27
Could you please share your Bot-ID?

**Comment by Sujit-Gaikwad** [comment] 2020-05-14 21:28
@Nikitha-MSFT sorry am not able to share bot id 

but we used following solution for reference that might help you to analysis issue :
https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/54.teams-task-module

**Comment by Nikitha-MSFT** [comment] 2020-05-18 07:01
We could able to reproduce the issue on our side. Raised a bug.

**Comment by Sujit-Gaikwad** [comment] 2020-05-21 07:02
>>We could able to reproduce the issue on our side. Raised a bug.

Thanks @Nikitha-MSFT

**Comment by Sujit-Gaikwad** [comment] 2020-06-20 12:52
Any Update on this?

**Comment by Sujit-Gaikwad** [comment] 2020-07-08 09:50
Any progress on this ??

**Comment by Nikitha-MSFT** [comment] 2020-07-08 10:10
We are tracking it internally but we don't have ETA to share when it will be fixed

**Comment by Sujit-Gaikwad** [comment] 2020-07-08 16:39
@Nikitha-MSFT thanks for your comment, please do update me on the same once get fixed as it is required to be worked in our bot as soon as possible.

**Comment by Wajeed-msft** [comment] 2020-10-05 07:35
**Internal Tracker:**  [Bug 930868](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/930868): Get vertical scroll bar in task module but not able to scroll the card using that.

**Comment by Manish-MSFT** [comment] 2020-12-14 13:57
@Sujit-Gaikwad , This bug has been fixed. Please check at your end. Thanks.

**Closed** 2021-01-27 03:42 UTC
Labels: bug, needs-attention, teams-developer-support
