### ISSUE TITLE
Teams Bot notification click goes to Feed, not the bot chat page

### ISSUE THREAD

**Issue by pooranoayaw** [MicrosoftDocs/msteams-docs#5657] opened 2022-04-02 16:52 UTC
When a Teams bot notification is clicked, it is supposed to take the user to the bot chat page, but it takes the user to the feed page. The user has to click the chat on the left menu bar and click the bot chat to see the message. 

How to fix this?

**Comment by pooranoayaw** [comment] 2022-04-04 18:33
The goal of a push notification is to take the user to the right resource when prompted. The current flow makes the user go to feed, click on the chat tab, then choose correct the bot channel to see the message -- 3 extra clicks, to see what the push notification was about. 

In the entire flow, the user can be distracted by a feed message or other chat in the chat list, before seeing the bot message - we might lose the audience before they reach the intended message.

**Comment by pooranoayaw** [comment] 2022-04-07 16:51
I just checked, and our bot notifications are not coming on the feed for some reason. How to make sure that our bot notifications appear on feeds also? What setting needs to be set for bot message?

**Comment by Meghana-MSFT** [comment] 2022-04-07 16:53
Please check this thread - https://stackoverflow.com/questions/54770102/how-do-i-get-notifications-when-a-bot-sends-a-message-in-teams

**Comment by GauravES** [comment] 2022-05-14 03:05
IMO, The insistence that this by design is then bad design.  User expectation is that chat messages from any source (1-1 user, group chat or when sent by a bot in the chat pane) should work identically.   When a user clicks on the notification, then it should take the user to the chat pane of the sender and not have inconsistent behavior.   Bots are used in customer service chats; in this case if a user is on a different tab and they get a notification they should not have to click 2-3 times to return to the customer service chat mediated by the bot.

The comment that even if the focus shifts to the Activity Feed but the right side shows the chat pane of the bot is also incorrect.   This only happens if that conversation was the last used conversation.  If the user is in another conversation and they get a notification of a chat message from a bot, the Teams client *attempts* to return to the chat pane with the bot, fails, and then leaves the focus on whatever the last active conversation (in focus) window was.  You can repro this by changing focus to another conversation (not with the bot), and the click on a notification from the target bot, and observe where the focus go.

Same issue was reported here, https://stackoverflow.com/questions/68788197/how-to-fix-broken-focus-when-clicking-on-notifications-in-teams-client-from-11/68842407?noredirect=1#comment123717956_68842407  with the same response from Microsoft.

Please refer this back to the design team as the "design" frustrates the implementation of good interactive bots.

**Comment by Meghana-MSFT** [comment] 2022-06-07 16:54
We forwarded the feedback to the engineering team.

**Comment by Meghana-MSFT** [comment] 2022-12-05 08:41
We are closing this issue for now, please feel free to reach out to us if you have further questions.

**Closed by Meghana-MSFT** 2022-12-05 08:41 UTC
Labels: teams-developer-support, needs-attention
