### ISSUE TITLE
Deep link jump back to main screen

### ISSUE THREAD

**Issue by DaniilSemenchenko** [MicrosoftDocs/msteams-docs#8753] opened 2023-05-30 19:32 UTC
Hi, I have an application in microsoft teams, and when I open it as pop out app and use deep link, it redirect me back to main ms teams window, I use microsoft/teams-js library
And I have to assumptions:
1) I have an incorrect deep link
2) The problem with the method that I use for deep link (I use app.openLink() )
It would be great if you will provide some information
Thanks in advance

**Comment by ChetanSharma-msft** [comment] 2023-05-31 10:44
Hello @DaniilSemenchenko - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by DaniilSemenchenko** [comment] 2023-05-31 10:59
Hi, the repro steps is
1) Find LMS365 in Teams in left-hand side menu and click right-mouse button and select "Pop out app"
2) Navigate to Dashboard or Catalog tab (tabs of ms-teams app) and select any course there (when you select course you use deep link) 
3) You should be brought back to main window and not stay in the pop-up
Deep link url - "https://teams.microsoft.com/l/entity/5cb9e567-f05d-40be-8fb7-219cdbf22212/lms365-training-qa?context=%7B%22subEntityId%22%3A%22JTdCJTIydmlldyUyMiUzQSUyMmNvdXJzZSUyMiUyQyUyMndlYlVybCUyMiUzQSUyMmh0dHBzJTNBJTJGJTJGbG1zMzY1cWEuc2hhcmVwb2ludC5jb20lMkZzaXRlcyUyRk1vZGVybkthdGVzJTJGVFAyd2l0aHByZXJpcXVzaXRlc0xNYXBwcm92YWwxJTIyJTdE%22%7D&entityWebUrl=https%3A%2F%2Flms365qa.sharepoint.com%2Fsites%2FModernKates%2FTP2withpreriqusitesLMapproval1

**Comment by DaniilSemenchenko** [comment] 2023-05-31 11:53
I'm facing this issue on desktop, cause only desktop has this functionality(pop out app)
and library is @microsoft/teams-js": "^2.9.1"

**Comment by Nivedipa-MSFT** [comment] 2023-05-31 12:31
@DaniilSemenchenko - We will test this using @microsoft/teams-js": "^2.9.1" and update you soon.

**Comment by Nivedipa-MSFT** [comment] 2023-06-01 06:56
@DaniilSemenchenko - We got an update from engineering team saying that this is by design behaviour. Deeplinks open in main Teams client window rather than popped out window.

**Comment by Nivedipa-MSFT** [comment] 2023-06-01 13:42
@DaniilSemenchenko - Thanks for the confirmation. Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.

**Comment by ChetanSharma-msft** [comment] 2023-06-01 18:14
We are closing this issue for now, please feel free to reopen it, if required.

**Closed by ChetanSharma-msft** 2023-06-01 18:14 UTC
Labels: teams-developer-support, needs-attention
