### ISSUE TITLE
Buttons are not getting disabled in MS Teams

### ISSUE THREAD

**Issue by Ashwathi-Nair** [MicrosoftDocs/msteams-docs#8698] opened 2023-05-23 12:46 UTC
{
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
          "type": "AdaptiveCard",
          "version": "1.5",
          "body": [],
          "actions": [
            {
              "type": "Action.Submit",
              "title": "JAVA",
              "isEnabled": false
            },
            {
              "type": "Action.Submit",
              "title": "PYTHON",
              "isEnabled": false
            }
          ]
        }
      }

**Comment by Prasad-MSFT** [comment] 2023-05-23 13:34
@Ashwathi-Nair - Thanks for raising this issue. We tried to repro this issue using the card JSON provided
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.5",
  "body": [],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "JAVA",
      "isEnabled": false
    },
    {
      "type": "Action.Submit",
      "title": "PYTHON",
      "isEnabled": false
    }
  ]
}
```

 and observed that, Adaptive card action buttons are not getting disabled using **"isEnabled": false** property.
 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/b6bab050-0786-4a7e-a2b9-79cda88bd87b)



We have raised a bug for the same. We will inform you once we get any further update from engineering team.
Thanks!

**Comment by Ashwathi-Nair** [comment] 2023-06-07 14:37
Do we have an ETA for the same?

**Comment by kaneg** [comment] 2023-06-20 09:02
Is it a bug or Teams doesn't support the disabled button?

**Comment by Ashwathi-Nair** [comment] 2023-06-20 10:07
Not sure of that, in adaptive cards the feature is there. But the same when we try to implement in teams, it is not happening.

**Comment by omikader** [comment] 2023-08-24 19:15
Hello! Are there any updates on the plan to support disabling adaptive card actions in microsoft teams?

**Comment by Prasad-MSFT** [comment] 2023-09-12 14:00
We got update from engineering team that, "The payload received for rendering seems to be neglect `isEnabled` prop, hence causing this behaviour. This is expected behaviour as the prop is yet to be honoured by Teams."

**Comment by Prasad-MSFT** [comment] 2023-09-14 06:49
We are closing this issue for now. Please feel free to reopen if required. Thanks!

**Closed by Prasad-MSFT** 2023-09-14 06:49 UTC
Labels: teams-developer-support, bug
