### ISSUE TITLE
ShareToTeams script no option to share to person while this is mentioned in the docs.

### ISSUE THREAD

**Issue by milandebuck** [MicrosoftDocs/msteams-docs#3519] opened 2021-05-31 09:43 UTC
Hi,

While creating a ShareToTeams button we noticed a discrepancy between the docs and the actual functionality.
In the docs it is clearly stated it can be used to share something directly with a person.
See [Create Share-to-Teams button](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/share-to-teams) first paragraph

> Third-party websites can use the launcher script to embed Share-to-Teams buttons on their webpages. When you select, it launches the Share-to-Teams experience in a pop-up window. **This allows you to share a link directly to any person or Microsoft Teams channel without switching the context.** This document guides you on how to create, and embed a Share-to-Teams button for your website, craft your website preview, and extend Share-to-Teams for Education.

While testing a ShareToTeams button we were only allowed to share a link in a team or channel and not directly to another person.

Is this an error in the documentation or something related to the teams setup on our end?

**Comment by Ravindra-MSFT** [comment] 2021-06-01 05:29
Hi @milandebuck Thanks for reaching out to us. We are checking this issue internally and get back to you.

**Comment by Ravindra-MSFT** [comment] 2021-06-01 09:16
@milandebuck We are able to repro the issue with public version. We have raised a bug and our Engineering team will work on it.

**Comment by Jagadeesh-MSFT** [comment] 2021-06-08 20:14
The people and group chats selector wasn't yet enabled in R4 when this bug was opened. It has since then been enabled and the functionality should now be available for all users worldwide: 
![image](https://user-images.githubusercontent.com/73812940/121251041-0fd9a880-c8c4-11eb-98b5-9bec08334c7d.png)

For now we are closing this issue, feel free to reopen the bug if you are still facing the issue.

**Comment by milandebuck** [comment] 2021-06-10 09:16
@Jagadeesh-MSFT  I am still able to reproduce this issue. Seems like it is not yet out there for all users.
![image](https://user-images.githubusercontent.com/17318991/121498966-3b03eb00-c9dd-11eb-925b-f7e20a84828c.png)

**Comment by tegenterter** [comment] 2021-06-10 09:23
Doesn't work for me either ➕

**Comment by KhrystynaHalak** [comment] 2021-06-10 09:25
The issue is still reproducible for me for both accounts that I've tried

**Comment by andrei88c** [comment] 2021-06-10 09:35
Still reproduces, 2 different accounts
![Untitled](https://user-images.githubusercontent.com/4559333/121501891-50cadd80-c9e8-11eb-81aa-3f6b72b49f0a.png)
![Untitled 2png](https://user-images.githubusercontent.com/4559333/121501911-558f9180-c9e8-11eb-843d-df28c9255703.png)

**Comment by Ravindra-MSFT** [comment] 2021-06-10 10:07
Hi we took this issue to our Engineering team we will let you know once issue is fixed.

**Comment by cecil-jolley** [comment] 2021-07-19 19:49
I am having this issue as well. What's strange in our case, is that we have at least one user who CAN search for users using this implementation, yet myself and several other developers are not able to search for users; only Teams/Channels.

I take it this has not been resolved?

**Comment by Wajeed-msft** [comment] 2021-07-20 07:28
@cecil-jolley - could you please share sceenshot of what you see in Share To Microsoft Teams UI? Also share for the users who are able to do it.

**Comment by cecil-jolley** [comment] 2021-07-20 12:06
> @cecil-jolley - could you please share sceenshot of what you see in Share To Microsoft Teams UI? Also share for the users who are able to do it.

Absolutely, the first two are screen shots of what we see. We are only able to search for Teams/Channels, and the placeholder text even states 'Search for a Team or Channel'
![atlas-teams01](https://user-images.githubusercontent.com/87671835/126320767-4c53d8ba-3242-4651-baad-c9031c4a72dd.PNG)
![atlas-teams02](https://user-images.githubusercontent.com/87671835/126320769-952c3f27-c134-460b-a91e-45a40dc5e091.PNG)

Here is a screenshot from one of our developers where he IS able to search for users:
![atlas-teams03](https://user-images.githubusercontent.com/87671835/126320917-da087924-2bd4-48d9-9669-bee7ada6a493.PNG)

**Comment by Wajeed-msft** [comment] 2021-08-09 05:16
@cecil-jolley -  This feature would be enabled in public rings in next few weeks.

**Comment by Wajeed-msft** [comment] 2021-09-19 10:51
@cecil-jolley - This feature is enabled. Please feel free to re-open this issue if you are still facing the issue.

**Closed by Wajeed-msft** 2021-09-19 10:51 UTC
Labels: teams-developer-support, bug
