### ISSUE TITLE
Typeahead search in Adaptive Cards - submit button doesn't work

### ISSUE THREAD

**Issue by TsarenkoEugene** [MicrosoftDocs/msteams-docs#9066] opened 2023-07-17 12:50 UTC
Hello everyone! I'm trying to add [typeahead search](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/dynamic-search?tabs=desktop%2Cjson) to my bot,
**1) I've copied this adaptive card**
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/57068641/0a79b391-c43c-4541-8c41-06caadb6901b)

**2) Added this code to add a response for dynamic search**
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/57068641/ce8d9971-e208-46fc-baba-2046ddaf3d30)

**Result:**
If you use a search and select a nonstatic option - 'Request Purchase' button - doesn't work, the button doesn't get submitted, doesn't get grey
![typeahead-search](https://github.com/MicrosoftDocs/msteams-docs/assets/57068641/8f808d47-b10a-496c-822c-defa23291cc6)

**But if you select a static option -  'Request Purchase' button works**

![static-typeahead-search](https://github.com/MicrosoftDocs/msteams-docs/assets/57068641/bd1ad32a-ab17-46df-b580-f9635e40571c)

**Comment by Nivedipa-MSFT** [comment] 2023-07-18 05:29
@TsarenkoEugene - Thanks for reporting your issue. We will test this and update you soon.

**Comment by TsarenkoEugene** [comment] 2023-07-24 10:38
@Nivedipa-MSFT Hi, did you have a chance to look into this? Were you able to reproduce it?

**Comment by Nivedipa-MSFT** [comment] 2023-07-24 10:51
@TsarenkoEugene - Yes, we were able to reproduce this issue, and we have raised a bug for it. We will keep you informed if there are any updates regarding the bug fix.

**Comment by CodeABao** [comment] 2023-08-16 02:07
any update？

**Comment by Nivedipa-MSFT** [comment] 2023-08-16 06:28
@CodeABao - Engineering team is working on the bug fix. Currently we don't have any ETA to share. We will let you know once we get any updates on it.

**Comment by EGInsider** [comment] 2023-08-17 11:04
Even I'm working on something similar and whenever we select a dynamic option the submit action doesn't trigger.

Use case : My Search box searches from a list of dynamic options which I'm fetching from a json file and when I hit the submit button it should return an adaptive card populated with response object properties.

Issue: When I select a dynamic option and hit submit the action doesn't get triggered !!

**Comment by 01** [comment] 2023-08-17 19:02
@Nivedipa-MSFT this is a critical issue that has suddenly appeared. We had a individual involved in QA have it occurring but no one else and wrote it off, in the past few days it has now been occurring for everyone. Root cause must be related to teams update. Please advise how to escalate

**Comment by Nivedipa-MSFT** [comment] 2023-08-18 05:13
@01 - We are checking this with engineering team and update you soon.

**Comment by CodeABao** [comment] 2023-08-18 06:43
> @CodeABao - Engineering team is working on the bug fix. Currently we don't have any ETA to share. We will let you know once we get any updates on it.

thanks, i added 400+ items to adaptivecard as static options, it's running well, but i still hope it can be fix quikly.

**Comment by CodeABao** [comment] 2023-08-18 07:40
> > thanks, i added 400+ items to adaptivecard as static options, it's running well, but i still hope it can be fix quickly.
> 
> @CodeABao lucky you, I can't pre-load all options there are about 200 adaptive card has other content except the search and I'm facing 'entity too large' issue

did you try to set the option value to number? i set the value to number like {"title":"xxxxx","value": 1 } and make a mapping between number the real value,  it will reduce the adaptivecard size.

**Comment by TsarenkoEugene** [comment] 2023-08-18 08:17
> did you try to set the option value to number? i set the value to number like {"title":"xxxxx","value": 1 } and make a mapping between number the real value, it will reduce the adaptivecard size.

okay, that's weird, I just tried to load all 200 options without mapping - and it worked, maybe they've changed the size of the message recently? thank you! another form with 2k+ options still doesn't work, I guess that form has to wait for a fix

**Comment by Nivedipa-MSFT** [comment] 2023-08-23 08:17
@TsarenkoEugene - Engineering team is actively working on the bug fix. We will let you know once we get any updates on it.

**Comment by aregnet** [comment] 2023-09-07 05:15
With my bot I've exactly the same problem. In our company this behavior started with a small amount of users even if they had the same teams version as others.

In my case the search field is required. If the user selects an item the required validation failes.
I tried the dataset "graph.microsoft.com/users" then everything is working as expected. So I think the bug attemps only with custom datasets.

**Comment by 01** [comment] 2023-09-08 10:44
@Nivedipa-MSFT you stated that engineering team was working on bug fix over 2 weeks ago.  This bug wad been reported nearly a month ago now. Is there any timeline whatsoever that can be given?

**Comment by Nivedipa-MSFT** [comment] 2023-09-08 12:51
@01 - We will check the ETA with engineering team and update you soon.

**Comment by 01** [comment] 2023-09-13 03:20
@Nivedipa-MSFT Please advise any kind of ETA or if there is a more appropriate avenue to be escalate this.

**Comment by oleksiirud** [comment] 2023-10-09 08:23
@Nivedipa-MSFT any updates on this one?

**Comment by jvrasa** [comment] 2023-10-17 14:53
@Nivedipa-MSFT hi, any update for this bug? It's been 3 months and it's a critical bug as the typeahead search doesn't work anymore.

**Comment by Nivedipa-MSFT** [comment] 2023-10-19 12:53
@TsarenkoEugene - The bug has been fixed now. We have tested this on the Teams web client. Could you please test this and confirm it?

**Comment by TsarenkoEugene** [comment] 2023-10-19 14:36
@Nivedipa-MSFT yes, it works, thank you!

**Comment by Nivedipa-MSFT** [comment] 2023-10-19 15:37
@TsarenkoEugene - Thanks for the confirmation. Could you please share your valuable feedback via [Microsoft Teams Developer Feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u) link.

**Comment by CodeABao** [comment] 2024-03-04 06:22
this issue comes back to my tentant.

**Comment by aregnet** [comment] 2024-03-04 09:14
for me also with the current new teams version

**Comment by ChetanSharma-msft** [comment] 2024-03-07 10:48
Hello Everyone,
Thanks for reporting it.
Please confirm if you are facing this issue in Classic or New Teams Web/Desktop clients?

Meanwhile, We will check this with engineering team and let you know the updates.

**Closed** 2024-04-25 11:44 UTC
Labels: teams-developer-support, bug, needs-author-feedback, status-no-recent-activity
