### ISSUE TITLE
Unknown error when sending message 

### ISSUE THREAD

**Issue by MajaEffenberg** [MicrosoftDocs/msteams-docs#6140] opened 2022-06-08 12:16 UTC
Hi there,

We sometimes get a strange error when we try to send a message as adaprive card in MS Teams:
```json
{
    "error": {
        "code": "ServiceError",
        "message": "Unknown"
    }
}
```
Error message `Unknown` gives us no information regarding the error. So why can we get this error and why is it `Unknown`?

Request info:

- Url: `https://smba.trafficmanager.net/ch/v3/conversations/{conversationId}/activities/{activityId}`
- Method: PUT
- Body: 

```json
{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "type": "AdaptiveCard",
        "body": [
          {
            "type": "TextBlock",
            "text": "Hi, willkommen zurück!",
            "wrap": true
          }
        ],
        "actions": [
          {
            "type": "Action.Submit",
            "title": "Lernsession starten",
            "style": "positive",
            "data": {
              "msteams": {
                "type": "messageBack",
                "displayText": "Lernsession starten",
                "value": {
                  "action": "startNewLearningSession"
                }
              }
            }
          }
        ],
        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
        "version": "1.4"
      }
    }
  ]
}

```

**Comment by MajaEffenberg** [comment] 2022-06-13 13:12
Is there any update on this issue?

**Comment by v-chetsh** [comment] 2022-06-14 10:01
@MajaEffenberg - We will investigate on it and get back to you.

**Comment by Prasad-MSFT** [comment] 2022-06-14 12:54
@MajaEffenberg - Tried to send the card json provided as message using Incoming webhook and it worked fine. How are you sending the message to MS Teams?
![image](https://user-images.githubusercontent.com/62237649/173581792-467682cf-1da4-4ca1-b081-3ae9c920d595.png)

Result:
![image](https://user-images.githubusercontent.com/62237649/173581881-bd4b049a-666b-40bc-a98e-5cc717ce311b.png)

**Comment by sueess** [comment] 2022-06-16 09:14
Hi Prasad,

I work together with Maja. 

The problem is exactly that it is working normally fine. It is not a deterministic error. It happens from time to time. For this reason it would be very important to know, when you are returning an error like this:

`{
    "error": {
        "code": "ServiceError",
        "message": "Unknown"
    }
}`

Unknown does not help us to find a way avoid the bug, because we are sending this kind of cards all the time and it works fine. Can you give us any information about that? Thank you!

**Comment by Prasad-MSFT** [comment] 2022-06-16 09:23
@sueess - Is there any console error you are getting?

**Comment by sueess** [comment] 2022-06-16 10:30
What you mean with a "console error"? 

The error is thrown, when we call `TurnContext.sendActivity()` using the botbuilder library.

**Comment by sueess** [comment] 2022-06-16 11:12
@Prasad-MSFT I think you did not understand the problem. This has nothing to do with the frontend. We are calling `TurnContext.sendActivity()` in the backend and it gives us this error. The developer tools are for the frontend.

**Comment by Prasad-MSFT** [comment] 2022-06-16 11:22
@sueess - We are checking it with engineering team what could be the root cause. We will inform you once we get any update. Thanks!

**Comment by MajaEffenberg** [comment] 2022-06-30 07:24
This problem reappeared in our app. This time for one user. When we send any **AdaptiveCard** to this person using `TurnContext.sendActivity()`, we get this error:
```json
{
    "error": {
        "code": "ServiceError",
        "message": "Unknown"
    }
}
```
As a result, the user cannot have a conversation and use our application.

**Comment by MajaEffenberg** [comment] 2022-06-30 08:27
@Prasad-MSFT 

Request information: 

- timestamp in UTC: `29.6.2022 - 15:39:45`
- method: `POST`
- url: `https://smba.trafficmanager.net/ch/v3/conversations/a%3A1DeAvUOJu6xpNa3kqbcyFvI7zQSoq1jD-MC10wuG6E7ep-fM32TrYXOuwuE1aXDNre37khBP8XjYk-W4VYltzH3auQFCPDXJYMayypwpIVRfs-vgkRW2alKNOqKkXZFWC/activities/f%3A29c5b723-47b4-64e0-0da0-5e4e6c94c219`
- conversationId: `a:1DeAvUOJu6xpNa3kqbcyFvI7zQSoq1jD-MC10wuG6E7ep-fM32TrYXOuwuE1aXDNre37khBP8XjYk-W4VYltzH3auQFCPDXJYMayypwpIVRfs-vgkRW2alKNOqKkXZFWC`
- activityId: `f:29c5b723-47b4-64e0-0da0-5e4e6c94c219`

Our botId: `4112cc9a-d683-4ffd-b0bc-2013af7c7497`

**Comment by sayali-MSFT** [comment] 2022-06-30 09:28
@MajaEffenberg - We are able to check the log and got this error-
"Unable to read feature value from ECS: 'Feature.MsgApiDarkWriteEnabled.CreateActivity.Message.Card.Plain', using fallback. enabled:False"

We will check with engineering team and get back to you.

**Comment by MajaEffenberg** [comment] 2022-07-04 14:33
In recent days we have received `Unknown` error again. 
``` JSON
{
    "error": {
        "code": "ServiceError",
        "message": "Unknown"
    }
}
```

Requests information:

1. - timestamp in UTC: `2.7.2022 - 12:45:32`
   - method: `POST`
   - url: `https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}`
   - conversationId: `a:1mZcE75ZaWbEl6nhudGPj21MrHgUlDUi2b97f_OYDgthVby7q7vU5LPSiE7HrismrMUy5FDQLBqTMeG7kh0CQR4vrtfnKXlkOmIpIsIB5DvR SADIocIB5DvR`



2. - timestamp in UTC: `3.7.2022 - 9:36:32`
   - method: `POST`
   - url: `https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}`
   - conversationId: `a:1mZcE75ZaWbEl6nhudGPj21MrHgUlDUi2b97f_OYDgthVby7q7vU5LPSiE7HrismrMUy5FDQLBqTMeG7kh0CQR4vrtfnKXlkOmIpIsIB5DvR SADIocIB5DvR`



3. - timestamp in UTC: `4.7.2022 - 7:35:47`
   - method: `POST`
   - url: `https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}`
   - conversationId: `a:1mZcE75ZaWbEl6nhudGPj21MrHgUlDUi2b97f_OYDgthVby7q7vU5LPSiE7HrismrMUy5FDQLBqTMeG7kh0CQR4vrtfnKXlkOmIpIsIB5DvR SADIocIB5DvR`

Our botId: `4112cc9a-d683-4ffd-b0bc-2013af7c7497`

Can you confirm that these are the same errors as before?

**Comment by MajaEffenberg** [comment] 2022-07-06 07:32
@sayali-MSFT 
Another `Unknown` errors appears for the next user by sending different messages using `TurnContext.sendActivity()`.

- method: `POST`
- url: `https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}`
- conversationId: `a:1zCN6CN689nAwdca1BNniUDItrHNv9ALInOlSDjduOvnQEiI2CGnjyLS3_yQCYGOzqk6bqOAKX0gm21aZ4N62GO2i07HOpomtlxVwJPnH0djmAlW5wIdr0DwDUreBGeu9`
- timestamps in UTC list for this user errors: 
   - `5.7.2022 - 17:58:27`
   - `5.7.2022 - 18:16:51`
   - `5.7.2022 - 18:19:17`
   - `5.7.2022 - 19:37:43`
   - `5.7.2022 - 20:45:59`

Our botId: `4112cc9a-d683-4ffd-b0bc-2013af7c7497`

Several users are now unable to have conversation in our app due to this error. So what is the status of this bug? Did you figured out what `Unable to read feature value from ECS: 'Feature.MsgApiDarkWriteEnabled.CreateActivity.Message.Card.Plain', using fallback. enabled:False` means and what the error is related to?

**Comment by Prasad-MSFT** [comment] 2022-07-06 08:56
@MajaEffenberg - We have informed engineering team about frequent occurrence this issue and team is looking for the root cause. We will inform you once we get further update. Thanks!

**Comment by MajaEffenberg** [comment] 2022-07-15 10:58
Is there any update on this issue?

**Comment by Prasad-MSFT** [comment] 2022-07-29 10:36
> In recent days we have received `Unknown` error again.
> 
> ```json
> {
>     "error": {
>         "code": "ServiceError",
>         "message": "Unknown"
>     }
> }
> ```
> 
> Requests information:
> 
> 1. * timestamp in UTC: `2.7.2022 - 12:45:32`
>    * method: `POST`
>    * url: `https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}`
>    * conversationId: `a:1mZcE75ZaWbEl6nhudGPj21MrHgUlDUi2b97f_OYDgthVby7q7vU5LPSiE7HrismrMUy5FDQLBqTMeG7kh0CQR4vrtfnKXlkOmIpIsIB5DvR SADIocIB5DvR`
> 2. * timestamp in UTC: `3.7.2022 - 9:36:32`
>    * method: `POST`
>    * url: `https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}`
>    * conversationId: `a:1mZcE75ZaWbEl6nhudGPj21MrHgUlDUi2b97f_OYDgthVby7q7vU5LPSiE7HrismrMUy5FDQLBqTMeG7kh0CQR4vrtfnKXlkOmIpIsIB5DvR SADIocIB5DvR`
> 3. * timestamp in UTC: `4.7.2022 - 7:35:47`
>    * method: `POST`
>    * url: `https://smba.trafficmanager.net/chv3/conversations/{conversationId}/activities/{activityId}`
>    * conversationId: `a:1mZcE75ZaWbEl6nhudGPj21MrHgUlDUi2b97f_OYDgthVby7q7vU5LPSiE7HrismrMUy5FDQLBqTMeG7kh0CQR4vrtfnKXlkOmIpIsIB5DvR SADIocIB5DvR`
> 
> Our botId: `4112cc9a-d683-4ffd-b0bc-2013af7c7497`
> 
> Can you confirm that these are the same errors as before?


We shared these details to engineering team ,but No errors can be found for that particular conversation id within that timestamp, or more broadly across all traffic from the bot.
<img width="215" alt="bd6ac9de-bdef-471b-9d64-a671d980408b" src="https://user-images.githubusercontent.com/62237649/181741543-5f11bf15-57af-481b-b3c8-3aa1cbac12ff.png">
 They are also not able to repro the same error with the adaptive card that was shared.
<img width="958" alt="c9f0ebc8-7d81-4e6b-adcd-8087020b526b" src="https://user-images.githubusercontent.com/62237649/181741357-a647450a-94fe-47ed-96f2-e331a7e0105a.png">

Are you still able to repro the issue on your end? Please provide latest details if any.

**Comment by MajaEffenberg** [comment] 2022-08-02 15:51
@Prasad-MSFT Thank you for the information.
Unfortunately, we are unable to reproduce this error on our part. We may provide more information when this error reapears.

**Comment by Prasad-MSFT** [comment] 2022-08-08 06:38
@MajaEffenberg - We are closing this issue for now. Please feel free to reopen if required.

**Closed by Prasad-MSFT** 2022-08-08 06:38 UTC
Labels: teams-developer-support, bug, needs-attention
