### ISSUE TITLE
Full width adaptive cards that have @mentions 

### ISSUE THREAD

**Issue by z3019494** [MicrosoftDocs/msteams-docs#3782] opened 2021-07-06 05:58 UTC
Looks like there's a potential problem with full width adaptive cards and the @mention features: if there is an @mention in the full width adaptive card, the card won't go full width.

https://twitter.com/mofumofu_dance/status/1412281864212008961?s=20

https://powerusers.microsoft.com/t5/Using-Flows/Full-width-adaptive-cards-on-quot-Post-an-Adaptive-Card-and-wait/m-p/972793#M24085

![image](https://user-images.githubusercontent.com/60587625/124549886-2ba87e00-de73-11eb-853c-e0bd5d567373.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 001a12ea-30fa-d626-18a9-02a518bfb37f
* Version Independent ID: e5f5f69e-66e9-d1b2-e19a-485d0ffcd6fa
* Content: [Text formatting in cards - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#full-width-adaptive-card)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-format.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-format.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment] 2021-07-12 06:30
@z3019494 - We are looking into this. We will try to repro this at our end and raise bug if requried.

**Comment by Wajeed-msft** [comment] 2021-07-12 17:49
@z3019494 - I am able to repro this issue with Power Automate. Most probably JSON value is overriding full width property. I have raise bug for this.  I'll let you know when I have updates on this. 


**Note:** sending Adaptive card directly from Bot  works fine. 

![image](https://user-images.githubusercontent.com/31851992/125332815-21045200-e367-11eb-8741-2d443a85a938.png)

![image](https://user-images.githubusercontent.com/31851992/125332725-04681a00-e367-11eb-8462-aefc566a83ae.png)

**Comment by aliquid** [comment] 2022-01-24 12:47
Either this is fixed or workaround is putting width property after entities. Probably it is fixed.

![image](https://user-images.githubusercontent.com/1115080/150785510-df389a95-0227-49ea-a1c8-b43c9fdbc4e6.png)

**Comment by v-chetsh** [comment] 2022-02-08 17:45
@z3019494 - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by z3019494** [comment] 2022-02-10 00:07
Hi @v-chetsh 

Unfortunately this is still an issue. 
![image](https://user-images.githubusercontent.com/60587625/153311528-78450181-8b69-417b-886c-4d9c437ec838.png)

@aliquid : In terms of putting the width property after the entities: would you be able to give me an example? Unfortunately I'm no developer myself :( Many thanks!

**Comment by v-chetsh** [comment] 2022-02-11 12:30
@z3019494 - We will check on it with engineering team and let you know the updates.

**Comment by AhmedBoustani** [comment] 2022-05-31 18:24
@v-chetsh - Any updates on this issue?

**Comment by Prasad-MSFT** [comment] 2022-06-07 06:54
Yes @AhmedBoustani - the issue is still reproable. We have informed engineering team about the same. We will update you if we get further info. Thanks!

**Comment by Prasad-MSFT** [comment] 2022-07-20 12:49
Hi @AhmedBoustani , @z3019494 - This issue seems to be resolved now. Please do verify.
Attaching the screenshot for reference:
![image](https://user-images.githubusercontent.com/62237649/179986095-cf7c4c57-6a76-48be-b617-1b5fb4690218.png)

**Comment by Prasad-MSFT** [comment] 2022-07-21 10:01
We are closing the issue for now. Please feel free to reopen if required.

**Comment by ChetanSharma-msft** [comment] 2023-01-24 05:02
Hello @z3019494, @aliquid, @AhmedBoustani -
Hope you are doing well!!

Could you please confirm whether you are still facing this issue, or it is resolved for you?

**Comment by Prasad-MSFT** [comment] 2023-01-24 06:03
@z3019494 , @AhmedBoustani - We tried to repro this issue again using MS Teams desktop `(Microsoft Teams Version 1.6.00.1579 )` and web client sending adaptive card having @mention via PowerAutomate and got the results as below:
**Using default width:**
![image](https://user-images.githubusercontent.com/62237649/214222672-fbdacee5-35a8-4469-853c-9518433bbffd.png)

**Using full width:**
![image](https://user-images.githubusercontent.com/62237649/214222704-33f2cd21-305e-4cfb-9cca-3a75e6800390.png)


Could you please confirm if you are also getting similar result or not?

**Comment by z3019494** [comment] 2023-01-25 03:22
It looks like we're all good now - the cards on the Teams desktop are now full width with @mentions :) 

<img width="479" alt="image" src="https://user-images.githubusercontent.com/60587625/214473035-caa5241f-edb2-4765-9e69-92e16a1f9bf1.png">

**Comment by Prasad-MSFT** [comment] 2023-02-02 11:15
This is working fine now.
Full width **without** at mention:
![image](https://user-images.githubusercontent.com/62237649/216309491-8d643ff0-0322-40bb-9160-5e92166e8e72.png)
Full width **with** at mention:
![image](https://user-images.githubusercontent.com/62237649/216310195-f9ab867a-103b-43be-9133-dbe1d7a1c998.png)

**Comment by Prasad-MSFT** [comment] 2023-02-02 11:38
We are closing this issue for now. Please feel free to reopen if required.

**Closed by Prasad-MSFT** 2023-02-02 11:38 UTC
Labels: teams-developer-support, bug
