### ISSUE TITLE
"Store" has changed to "Apps"

### ISSUE THREAD

**Issue by softwarecraft** [MicrosoftDocs/msteams-docs#974] opened 2019-09-26 10:21 UTC
In Teams desktop and web clients, as of today.

Refer to section https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload#upload-your-package-into-a-team-or-conversation-using-the-store.

Refer to related issue, https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3066.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328c86a9-1384-3f07-0b68-947f5ad9b5ab
* Version Independent ID: 9a8e000a-87ed-1357-0b28-feee59311149
* Content: [Upload your custom app in Microsoft Teams - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload#upload-your-package-into-a-team-or-conversation-using-the-store)
* Content Source: [msteams-platform/concepts/apps/apps-upload.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/apps/apps-upload.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment] 2019-09-30 11:33
Duplicate of #964

**Closed by Gousia-MSFT** 2019-09-30 11:33 UTC

**Comment by softwarecraft** [comment] 2019-10-01 02:03
This is not a duplicate as it refers to a different page in the MS docs site. Both doc pages need to be updated and other report doesn't reference the same page. You should re-open this issue and fix the doc page.
