### ISSUE TITLE
Number of sections in a webhook connector message

### ISSUE THREAD

**Issue by roiedominitz** [MicrosoftDocs/msteams-docs#4266] opened 2021-10-04 11:25 UTC
Hi, 
my name is Roie, I'm a developer and my company uses MS teams connector message to send alerts to our clients. We have a need to send many images, each in a specific location in the message. As far as I understand the only way for me to manage the location of each picture is to put it in a different section. The only problem now is that it seems the MS teams receives only 10 sections and ignores the rest. Is there a way around this?

thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28316a67-22fa-8a05-1ae0-fbe1c5720ef9
* Version Independent ID: 8a250e46-2a30-af86-839d-9f83a8b48041
* Content: [Create and send messages - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/connectors-using?tabs=cURL)
* Content Source: [msteams-platform/webhooks-and-connectors/how-to/connectors-using.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/webhooks-and-connectors/how-to/connectors-using.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by HunaidHanfee-MSFT** [comment] 2021-10-04 18:46
It is by design and the only workaround can be to send remaining sections in another card. 
Follow this link to learn more about connector card - [link](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#additional-information-on-the-office-365-connector-card)

> Each connector card can display a maximum of ten sections, and each section can contain a maximum of five images and five actions.

Let us know if you have any query.

**Comment by v-chetsh** [comment] 2021-10-05 05:15
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by v-chetsh** 2021-10-05 05:15 UTC
Labels: teams-developer-support, needs-triage :mag:
