### ISSUE TITLE
App Studio import failing

### ISSUE THREAD

**Issue by DanielLevy0705** [MicrosoftDocs/msteams-docs#5783] opened 2022-04-25 09:23 UTC
Hi,
I've been importing a chatbot from the same zip file for over a year, and it worked great.
Today suddenly when I tried to import the same zip file, I got the Fix validation errors pop up, and no errors were displayed.
What is the possible cause for this error? And how can I fix this / 
Adding a screenshot, Thanks in advance!
![image](https://user-images.githubusercontent.com/45950605/165057838-4f05e3b3-7bc3-4f9d-a84b-877b7563cb73.png)

**Comment by Prasad-MSFT** [comment] 2022-04-25 09:42
@DanielLevy0705 - Could you please check in Manifest Validator, if there is any error? If not please share your zip package, so that we can check once from our end

**Comment by DanielLevy0705** [comment] 2022-04-25 11:10
@Prasad-MSFT , Manifest Validator passed all tests. 0 errors and warnings.
here's the zip
[microsoft-teams-manifest (2).zip](https://github.com/MicrosoftDocs/msteams-docs/files/8553961/microsoft-teams-manifest.2.zip)

**Comment by Prasad-MSFT** [comment] 2022-04-25 12:20
@DanielLevy0705 -We tried to import the zip provided in the App Studio and were able to do so without any error.

![image](https://user-images.githubusercontent.com/62237649/165087544-6dae2768-5b40-4c5f-88ad-c058806a4e3d.png)

**Comment by DanielLevy0705** [comment] 2022-04-25 16:31
@Prasad-MSFT That's really weird. Since I'm trying now with that zip file, and also tried to restart my ms-teams client and my computer.
This is also happening to other people in my organization.

**Comment by DanielLevy0705** [comment] 2022-04-27 04:24
@Prasad-MSFT is there any update?

**Comment by Prasad-MSFT** [comment] 2022-04-27 08:29
@DanielLevy0705 - It might be the issue due to duplication. As when i tried to re-import the package again, i am getting the same error
![image](https://user-images.githubusercontent.com/62237649/165475964-721d79a4-bdd5-4948-9e96-47aff89b97d4.png)

**Comment by DanielLevy0705** [comment] 2022-04-27 08:33
Thanks, I tried to delete the app and reimport it when I have no apps in the app studio, but still getting this error. is there any solution/workaround?

**Comment by Prasad-MSFT** [comment] 2022-04-27 12:04
I deleted the app from app studio and re-imported and it worked fine
![image](https://user-images.githubusercontent.com/62237649/165514131-2bd15f29-b332-4559-a1ee-180950b2b114.png)
Please try importing from dev portal. That might help

**Comment by DanielLevy0705** [comment] 2022-05-01 13:30
Hi, Prasad. I tried to delete and import again and it's still not working.
importing from the dev portal doesn't seem like a valid solution, since I'm having issues configuring the bot as I'd like with an endpoint.

**Comment by Prasad-MSFT** [comment] 2022-05-05 07:06
Could you please try to update MS Teams app version and also upgrade the manifest version and check if it helps in any way?

**Comment by DanielLevy0705** [comment] 2022-05-12 08:12
@Prasad-MSFT hi Prasad, sorry for the late response.
Upgrading both ms-teams version and Manifest version didn't help.

**Comment by Prasad-MSFT** [comment] 2022-05-12 08:24
@DanielLevy0705 - Is it happening for this particular app manifest or for every manifest you are trying to import?

**Comment by DanielLevy0705** [comment] 2022-05-12 12:02
I created a brand new application and deleted it and managed to add its manifest.
but still can't manage to add my manifest.

**Comment by Prasad-MSFT** [comment] 2022-05-12 12:05
> I created a brand new application and deleted it and managed to add its manifest. but still can't manage to add my manifest.

I am bit not clear here
You are able to add new app manifest ,but not this particular manifest , right?

**Comment by DanielLevy0705** [comment] 2022-05-12 12:38
Hi Prasad, That's correct, I've managed to create a sample manifest and import it and it worked.

But then I went even further and tried to create a new app manifest using the data from my old manifest.
(created a new app and added all of the data to the relevant fields)
It gave me the same validation error.
adding both new manifests. the one that worked is called NewApp and the other is called algobot.

**Comment by Prasad-MSFT** [comment] 2022-05-12 12:50
Its bit strange, because i tried to import both the apps shared and both got added successfully.
1.
![image](https://user-images.githubusercontent.com/62237649/168078350-377e2c7c-0eae-44cf-95d4-e82ce8be9823.png)

2.
![image](https://user-images.githubusercontent.com/62237649/168078193-1b78c5e6-f5b0-466d-bba3-4bbe6c82af28.png)


`Microsoft Teams Version 1.5.00.11865 (64-bit). It was last updated on 5/11/2022.`

**Comment by Prasad-MSFT** [comment] 2022-05-12 14:43
Oh, great. Glad that you find the root cause. Thanks for the update
We are closing the issue for now. Please feel free to reopen if required

**Comment by DanielLevy0705** [comment] 2022-05-25 07:59
@Prasad-MSFT hi Prasad, please re-open this issue.
our QA tried to test the new manifest, but it gets the same error on his client, he tried to upgrade the client to last version, but same results. he even tried to test it on other QA clients.
on my client on the other hand, the old manifest is still getting this error, but the new client doesn't.
I'll try to find a work-around for our customers if they get the same error, but still it looks like a bug that should be fixed. (even though it's hard to reproduce it on your clients).

**Comment by DanielLevy0705** [comment] 2022-05-25 13:57
> 

hi Prasad, by console logs do you mean the error in the popup window or are there any other logs that I can collect?
if you mean only the popup it's the same message as in the original post.

the client's version is: Microsoft Teams Version 1.5.00.11163 (64-bit)

**Comment by Prasad-MSFT** [comment] 2022-05-26 06:16
@DanielLevy0705 - Please refer this to get console log:https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/developer-tools#access-devtools-on-the-desktop

**Comment by DanielLevy0705** [comment] 2022-05-26 10:28
Thanks @Prasad-MSFT , I'm waiting for the logs from our QA.
in the meantime, I've managed to find a workaround, I figured that since I've managed to solve the issue locally by changing the App Id, maybe if the QA will generate a new App ID and copy it to the Manifest.json, it would solve the issue for him as well. and in fact, it did.

So first of all it may help you with understanding the issue.
Secondly, my question is - can I offer such a workaround until the issue is solved globally? what are the consequences of changing the App Id of a distributed manifest zip?

**Comment by Prasad-MSFT** [comment] 2022-05-26 10:41
Okay great. But if the App Id is being used somewhere for deeplinking or anything, it will impact the functionality.

**Comment by DanielLevy0705** [comment] 2022-05-26 13:35
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/45950605/170498357-a1c9cdd6-04f2-42b1-94d6-bb93409d0785.png)
@Prasad-MSFT these are the console logs when trying to import the manifest from the ms-teams web application.

**Comment by Prasad-MSFT** [comment] 2022-05-26 13:50
@DanielLevy0705 - We have raised a bug for this issue and engineering team is looking into it. We will inform you once we get further update. Thanks!

**Comment by DanielLevy0705** [comment] 2022-06-14 08:38
any update regarding this bug?

**Comment by Prasad-MSFT** [comment] 2022-06-24 13:40
@DanielLevy0705 - We got update from engineering team saying that  "This is due to an app of the same ID is already in the app studio. Its highly recommend to use the developer portal instead as we are deprecating app studio in the near future. Please use the developer portal [Developer Portal (microsoft.com)](https://dev.teams.microsoft.com/home)"

**Comment by Prasad-MSFT** [comment] 2022-06-25 07:56
We are closing the issue for now. Please feel free to reopen if required.

**Closed by Prasad-MSFT** 2022-06-25 07:56 UTC
Labels: teams-developer-support
