### ISSUE TITLE
Error while reading manifest.json: App definition with message handler must have command.

### ISSUE THREAD

**Issue by preetichand** [MicrosoftDocs/msteams-docs#8435] opened 2023-04-05 15:18 UTC
We created a custom application on teams and added link unfurling to the app manifest. Added messageHandlers array to the composeExtensions section of  app manifest JSON with no commands.Earlier we used **manifest version 1.7** and found no issue while uploading manifest.After switching to **manifest** **version 1.16** we are facing error for empty list of **commands** in composeExtension - "**Error while reading manifest.json:  App definition with message handler must have command**. "

Checked this page - [Add link unfurling](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/link-unfurling?tabs=mobile%2Cdotnet%2Cadvantages#:~:text=Messaging%20extension%20commands%20aren%27t%20required%20for%20Link%20unfurling.%20However%2C%20there%20must%20be%20at%20least%20one%20command%20in%20manifest%20as%20it%20is%20a%20mandatory%20property%20in%20messaging%20extensions.%20For%20more%20information%2C%20see%20compose%20extensions.) which mentions that minimum one command is needed . Why it is mandatory to have at least one command though it is not required ? Do we have any other way to make it work without having commands ??

**Comment by Prasad-MSFT** [comment] 2023-04-06 05:23
@preetichand - We also tried in similar way without adding any command in composeExtensions section of app manifest JSON and got the same error . According to the documentation it seems like it is by design behaviour and we have to add at least one command in manifest as it is a mandatory property in messaging extensions.
![image](https://user-images.githubusercontent.com/62237649/230279205-d10318bb-31a7-42f0-806c-ca65e336e9da.png)

**Comment by preetichand** [comment] 2023-04-06 10:11
@Prasad-MSFT This was not mandatory in 1.7 version which we are using currently.And we are using only link unfurling.Even in the link unfurling documentation it's not mentioned to add commands.

**Comment by Prasad-MSFT** [comment] 2023-04-06 10:52
@preetichand - When we used manifest version 1.7 also, we were getting` Error while reading manifest.json: composeExtensions[0] | Required properties are missing from object: ["commands"].`
Attaching manifest json:
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.7/MicrosoftTeams.schema.json",
  "manifestVersion": "1.7",
  "version": "1.0",
  "id": "f04ac95c-6e7a-4434-994a-24da20a3757e",
  "packageName": "com.teams.sample.linkunfurling",
  "developer": {
    "name": "Link Unfurling",
    "websiteUrl": "https://www.microsoft.com",
    "privacyUrl": "https://www.teams.com/privacy",
    "termsOfUseUrl": "https://www.teams.com/termsofuser"
  },
  "icons": {
    "color": "icon-color.png",
    "outline": "icon-outline.png"
  },
  "name": {
    "short": "Link Unfurling",
    "full": "Link Unfurling Sample"
  },
  "description": {
    "short": "Link Unfurling sample",
    "full": "This sample demonstrates Link Unfurling for *.BotFramework.com urls."
  },
  "accentColor": "#FFFFFF",
  "composeExtensions": [
    {
      "botId": "448ec85c-4395-4f80-b5a1-cd3bdefd1f5b",
      "messageHandlers": [
        {
          "type": "link",
          "value": {
            "domains": [
              "*.botframework.com",
              "*.ngrok.io"
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by preetichand** [comment] 2023-04-06 11:25
In our case we have property "commands" as an empty array so it didn't give this error.
"commands" : []

**Comment by Prasad-MSFT** [comment] 2023-04-06 12:06
@preetichand - Right, on using empty array like `"commands" : [],` it doesn't give any error and can upload the app. There doesn't seem to be any other way to make it work without having commands using  manifest version 1.16 which you used.

**Comment by preetichand** [comment] 2023-04-07 06:14
Hello @Prasad-MSFT   **Customers are facing issue , we are looking for a resolution only for link unfurling.This issue has a large impact on our customers.**We need a fix for it.
Thanks

**Comment by Prasad-MSFT** [comment] 2023-04-10 10:35
Okay @preetichand - We will check this with engineering team regarding further action and will update you accordingly.

**Comment by preetichand** [comment] 2023-04-10 11:14
Yes please @Prasad-MSFT .

**Comment by raguravindran** [comment] 2023-06-07 12:36
@Prasad-MSFT Is there an update on this issue? if you could share a timeline of when you can get back to us, it will help.

**Comment by raguravindran** [comment] 2023-06-07 14:58
@Prasad-MSFT  Thanks, we will await your response. 
We need to deliver our feature to our customers. it will greatly help if we have a concrete answer from MSFT side sooner.

**Comment by raguravindran** [comment] 2023-06-22 03:22
@Prasad-MSFT  its been two months, anything on this item? this is affecting our customers and we would really like some resolution/action for this

**Comment by Prasad-MSFT** [comment] 2023-06-23 07:54
Apologies @raguravindran Currently there is no ETA to share. We are constantly following up with engineering team about this issue and updated priority. We will update this thread once we hear from them. Thanks!

**Comment by raguravindran** [comment] 2023-07-11 05:30
@Prasad-MSFT reaching out again to follow up, kindly please give us an update. Thanks

**Comment by Prasad-MSFT** [comment] 2023-07-12 06:59
Hi @raguravindran - As we have updated the priority last time, engineering team has started investigating the issue. We will update this thread as soon as we get any update. I understand the concern and following up closely with them to get any update.

**Comment by Prasad-MSFT** [comment] 2023-07-13 05:12
Hi @preetichand , @raguravindran - We got update from engineering team that "Messaging extension can have no commands if it has message handler defined.  Engineering team will make the validation logic change."

Thanks!

**Comment by preetichand** [comment] 2023-07-17 04:44
Thanks @Prasad-MSFT ,do we know when this change will be available?

**Comment by Prasad-MSFT** [comment] 2023-07-17 07:29
@preetichand - Currently there is no information when the validation logic is going to be changed. We will update this thread once we get any information from engineering team regarding the availability of change.

**Comment by preetichand** [comment] 2023-07-17 17:03
yes @Prasad-MSFT that would be helpful as it is needed for us to understand when can we provide the fix to our customers and will impact our upcoming developments.

**Comment by Prasad-MSFT** [comment] 2023-08-03 09:37
@preetichand - Currently there is no exact ETA to share. We have followed up with engineering team regarding the same and got update that it will be rolled out publicly real soon. So as soon as it gets rolled out, we will update the thread.

**Comment by Prasad-MSFT** [comment] 2023-09-13 13:15
@preetichand , @raguravindran - This issue is fixed now and is rolled out publicly. Using manifest version 1.16, we are able to upload the app without any error. Please do verify.
Thanks!

**Comment by preetichand** [comment] 2023-09-13 13:39
Thanks @Prasad-MSFT .Really appreciate it.I will update the thread after verifying the fix once.

**Comment by Prasad-MSFT** [comment] 2023-09-14 06:51
Glad to hear that it is working now. We are closing this issue for now. Please feel free to reopen if required. 
Thanks!

**Closed by Prasad-MSFT** 2023-09-14 06:51 UTC
Labels: teams-developer-support, bug
