### ISSUE TITLE
@ndileep , You can fetch the user principle name from the context itself . Please follow the below the steps to get the `UPN`.

### ISSUE THREAD

**Issue by liangchr** [MicrosoftDocs/msteams-docs#1581] opened 2020-04-24 02:19 UTC
@ndileep , You can fetch the user principle name from the context itself . Please follow the below the steps to get the `UPN`.
1. [Get Access Token  ](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-4.0#get-token)
![image](https://user-images.githubusercontent.com/50989436/80070885-599ced80-8561-11ea-9d30-78b9a5789afd.png)

2. Calling the given endpoint `{{serviceUrl}/v3/conversations/{conversationID}/members}`
![image](https://user-images.githubusercontent.com/50989436/80070857-4ab63b00-8561-11ea-86a5-966e83a57b1c.png)

_Originally posted by @Trinetra-MSFT in https://github.com/MicrosoftDocs/msteams-docs/issues/1574#issuecomment-618229033_

New Comment:
but what if the bot is not installed on the team? The user got the aadId +tenentId from a globally installed messaging extension. When I use.{{serviceUrl}/v3/conversations/{conversationID}/members} it says I can't get the information because the bot is not installed in the conversation.

**Comment by liangchr** [comment] 2020-04-24 02:20
but what if the bot is not installed on the team? The user got the aadId +tenentId from a globally installed messaging extension. When I use.{{serviceUrl}/v3/conversations/{conversationID}/members} it says I can't get the information because the bot is not installed in the conversation.

**Comment by Nikitha-MSFT** [comment] 2020-04-24 12:23
You can fetch user profile using graph [API](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http). You can also fetch user profile through passing aadObject id in GetMemberAsync function as documented [here](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#get-single-member-details)

**Comment by Trinetra-MSFT** [comment] 2020-04-27 12:10
This is an duplicate of #1574

**Closed by Trinetra-MSFT** 2020-04-27 12:10 UTC
