### ISSUE TITLE
[Authoring] Input.Date Card does not work for Global Applications

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4251] opened 2021-09-30 20:21 UTC
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6441 

**Details from original post:**
### Target Application

Microsoft Teams

### Application Operating System

Windows

### Schema Version

1.3

### Problem Description

We have a Teams application using the Input.Date Adaptive card. This application is used by Global Users all in different Local Timezones... When the raw input from the card is sent to our application, it sets the date by sending Local TZ -> GMT 00:00:00. For example,

Ireland Standard Time (GMT+1):
Inputs 09/30/2021 @ 5pm
Output 09/29/2021 @ 5pm

Pacific Standard Time (GMT-7):
Inputs 09/30/2021 @ 5pm
Output 09/30/2021 @ 5pm

### Expected Outcome

The backend should be using the date/time to determine the output GMT date.

### Actual Outcome

Since the adaptive card backend seems to be only using input the date to determine the output GMT date, this causes issues for a Global use case..

### Card JSON

```JSON
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "TextBlock",
      "text": "Date Input"
    },
    {
      "type": "Input.Date",
      "id": "date",
      "placeholder": "Enter a date",
      "value": "2017-10-12"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "OK"
    }
  ]
}
```

### Repro Steps

1. Create an adaptive card receiving date/time input field
2. Have a user in IST test this versus a user in PST or EST
3. Observe that for users in TZ where it is GMT+# the previous date will be returned, but for users in TZ where it is GMT-# the correct date will be returned.---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment] 2021-10-05 09:46
We are checking this internally. Will get back to you once we get any update

**Comment by nikolamus** [comment] 2021-10-05 09:54
Thank you.

We are one of the users experiencing this problem in production.
It's a really frustrating issue since our product is a leave tracker which integrates with Microsoft Teams, and as such it really depends on correct behavior of a date picker.

As far as I can tell, who experiences the issue is related to the specific instance of the Teams app. So one person can have it on Mac app, but not on web app.
Some kind of canary deployment or A/B testing in progress?

**Comment by Prasad-MSFT** [comment] 2021-10-06 08:57
@nikolamus , We have raised a bug for this issue and engineering team is looking into it. We will inform you once we get any update.

**Comment by Xomyhoc** [comment] 2021-10-15 11:20
We also have this problem, has any solution been found?

**Comment by susanshen96** [comment] 2021-10-29 18:41
Hi - we've checked in the fix for this issue on Oct 21, and it should be rolling through the rings, so the change should manifest in public clients in a couple of weeks.

**Comment by koaskas** [comment] 2021-11-09 09:15
This problem has now appeared in the browser!
When will the update?

**Comment by Prasad-MSFT** [comment] 2021-11-13 05:04
@koaskas , We tried to repro and can confirm that its working fine at our end both in Desktop client and web client. Please try to update your Teams version and check if it helps. Attaching screenshot below for reference:
Desktop:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/62237649/141606356-5124082e-54ef-4cfe-b7ec-b3580b9c815a.png)
Web:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/62237649/141606362-0fb55ad7-a39b-4103-8147-9a72a3248de9.png)

**Comment by matthiasdilger** [comment] 2021-11-15 09:53
@Prasad-MSFT Thanks for fixing this issue.

**Comment by koaskas** [comment] 2021-11-15 10:39
@Prasad-MSFT yes, updates have started to come in, thanks

**Comment by Prasad-MSFT** [comment] 2021-11-15 11:44
@koaskas ,Thanks for confirming. Closing the issue for now. Please feel free to re-open if needed.

**Closed by Prasad-MSFT** 2021-11-15 11:44 UTC
Labels: teams-developer-support, needs-triage :mag:

**Comment by brokkolifever** [comment] 2021-11-25 12:22
@Prasad-MSFT 
The problem has resumed
Please look

![image](https://user-images.githubusercontent.com/95029620/143440750-d212036c-7574-445e-af89-085edeb2916d.png)

**Comment by Prasad-MSFT** [comment] 2021-11-25 14:27
@brokkolifever - which teams version are you using? Could you please try to update it once and check?

**Comment by brokkolifever** [comment] 2021-11-25 14:33
@Prasad-MSFT version is 1.4.00.22976

**Comment by Prasad-MSFT** [comment] 2021-11-25 14:45
Could you please try to update it to `Microsoft Teams Version 1.4.00.32167` and check once ?

**Comment by brokkolifever** [comment] 2021-11-26 06:28
@Prasad-MSFT i can only update to 1.4.00.29469. 
![image](https://user-images.githubusercontent.com/95029620/143536846-dbf598f1-a4ed-4442-ae35-98a107c6cd86.png)
and i see the same problem in web version

**Comment by Prasad-MSFT** [comment] 2021-11-26 08:15
@brokkolifever - Its quite strange. Now we checked this again in both Teams Desktop`(Microsoft Teams Version 1.4.00.32167)` and Teams web ,and at both the places its working fine. 
We suggest you to update your Teams version and check.
https://microsoft-teams.en.uptodown.com/windows/versions

**Comment by brokkolifever** [comment] 2021-11-30 14:45
Hello. Automatically I can only update to 1.4.00.29469

I can't find link to version 1.4.00.32167 here:
https://microsoft-teams.en.uptodown.com/

![image](https://user-images.githubusercontent.com/95029620/144068579-41d5f864-bdd2-4d41-af0d-7274a94e151e.png)
![image](https://user-images.githubusercontent.com/95029620/144068631-f39933ba-8452-4975-9fd5-a1c6f5698cda.png)

Can you send a link?

**Comment by matthiasdilger** [comment] 2021-12-01 02:41
@Prasad-MSFT The issue is also back on Mac desktop. I tried to update to the latest version but all I get is this:


<img width="459" alt="Screen Shot 2021-12-01 at 10 38 55" src="https://user-images.githubusercontent.com/5625718/144162087-2ac54f28-dbda-4413-8925-a1e92b4ddb50.png">

I think this issue should be re-opened.

**Comment by matthiasdilger** [comment] 2021-12-09 00:19
@Prasad-MSFT I have now been able to update Teams on Mac to a version that fixes the issue. Thanks!

**Comment by brokkolifever** [comment] 2021-12-23 13:15
@Prasad-MSFT My version is 1.4.00.32771 now but i still but I still get the same problem (in the web version too)

**Comment by Prasad-MSFT** [comment] 2021-12-31 12:19
@brokkolifever - We have informed the concerned team about the issue. We will inform you once we get any update. Thanks!
