### ISSUE TITLE
The bot does not display a popup message box responding to submitAction

### ISSUE THREAD

**Issue by maxon-adc** [MicrosoftDocs/msteams-docs#618] opened 2019-05-03 09:50 UTC
When I receive a submitAction request, my bot responds with:

{
"task": {
"value": "Hello there",
"type": "message"
},
"responseType": "task"
}

However, instead of displaying a popup message box, task module displays an error: "Something went wrong, please try again later.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28710a9a-332d-6f67-e4cc-9681a1798e0f
* Version Independent ID: 116d97a4-dabd-036e-630b-7cf080b87099
* Content: [Using Task Modules in Microsoft Teams bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/task-modules/task-modules-bots#feedback)
* Content Source: [msteams-platform/concepts/task-modules/task-modules-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/task-modules/task-modules-bots.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Wajeed-msft** [comment] 2019-05-06 06:55
Duplicate of https://github.com/MicrosoftDocs/msteams-docs/issues/617.

**Closed by Wajeed-msft** 2019-05-06 06:55 UTC
