### ISSUE TITLE
Fixed width for Adaptive Cards but not O365 Connector Cards

### ISSUE THREAD

**Issue by 01** [MicrosoftDocs/msteams-docs#681] opened 2019-05-26 00:24 UTC
Is this by design? It seems that adaptive cards are forced to not take max width that a text message or 0365 Card can take. This results in a pretty limited ability to use adaptive cards. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8a3bcf2-332a-8d24-a8d1-7e3816897745
* Version Independent ID: 68fb9551-ce95-0112-2703-721a1af01f23
* Content: [Cards Reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference)
* Content Source: [msteams-platform/concepts/Cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/Cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Gousia-MSFT** [comment] 2019-05-27 07:02
Duplicate of:https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/issues/193

**Comment by Wajeed-msft** [comment] 2019-06-27 10:17
This is by design.

**Closed by Wajeed-msft** 2019-06-27 10:17 UTC
Labels: teams-developer-support

**Comment by stpeteparadox** [comment] 2020-03-02 10:39
Seriously? 

C'mon Microsoft. You do realize most of Team's users are paying customers right? 

Don't you think they deserve more than just a "it's by design" response to something that doesn't make any sense to those not involved in Teams development, and while Slack apparently manages this without issue?
