### ISSUE TITLE
notified edited message 

### ISSUE THREAD

**Issue by luserwu** [MicrosoftDocs/msteams-docs#4616] opened 2021-11-17 09:45 UTC
Bot receives callback event when a personal message is sent to it. However, when a message is edited, it's not notified. Is that intended behaviour?

**Comment by HunaidHanfee-MSFT** [comment] 2021-11-17 16:17
Thanks for bringing this out. I will confirm internally and let you know.

**Comment by HunaidHanfee-MSFT** [comment] 2021-11-17 17:57
Confirmed with the team that it is intended and bot doesn't get any activity when message is edited or updated.

I am closing this issue as of now, feel free to open if you have any query.

Thanks

**Closed by HunaidHanfee-MSFT** 2021-11-17 17:57 UTC
Labels: teams-developer-support, needs-triage :mag:
