### ISSUE TITLE
HTML page through Android or IOs app does not run javascript

### ISSUE THREAD

**Issue by MLEGIsilog** [MicrosoftDocs/msteams-docs#7411] opened 2022-11-04 16:32 UTC
Hi

We've developped a Team message extension so as to create tickets into a database.
To do so, we have a first page that does authenticate using Azure token then access our "auth" endpoint to ensure the current user is allowed in our database.

In the PC version, everything is ok !
In tactile devices, the external page is not closed automatically, we are obliged to provide end-user with a custom HTML page to inform that he can close the page manually...

Will you have some idea to make our authentication process with tactile apps as great as the PC version ?

**Comment by sayali-MSFT** [comment] 2022-11-06 17:17
@MLEGIsilog - Thanks for reporting your issue.
We will try it from our end and get back to you.

**Comment by ChetanSharma-msft** [comment] 2022-11-08 06:51
Hello @MLEGIsilog - Have you implemented the Authentication via following below documentation for your Messaging extension or any other custom auth?
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication

Could you please share more information.

**Comment by MLEGIsilog** [comment] 2022-11-08 08:06
Hello,

We used MSAL for the authent using this doc : https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/manage-teams-identity?pivots=programming-language-javascript

It seems that js script is run using default browser for desktop versions but it is not the same for tactile devices : is it a feature that could be implemented soon ?

Regards

De : ChetanSharma-MSFT ***@***.***>
Envoyé : mardi 8 novembre 2022 07:52
À : MicrosoftDocs/msteams-docs ***@***.***>
Cc : Michaël LEGER ***@***.***>; Mention ***@***.***>
Objet : Re: [MicrosoftDocs/msteams-docs] HTML page through Android or IOs app does not run javascript (Issue #7411)


Hello @MLEGIsilog<https://github.com/MLEGIsilog> - Have you implemented the Authentication via following below documentation for your Messaging extension or any other custom auth?
https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/add-authentication

Could you please share more information.

**Comment by sayali-MSFT** [comment] 2022-11-08 13:52
@MLEGIsilog -We will confirm with the engineering team and let you know once we get any update.

**Comment by sayali-MSFT** [comment] 2022-11-15 07:11
Teams Clients use different browsers to run our apps - In Windows Desktop Client we use the Electron webview (which is based on Chromium), in iOS we use the WebKit webview, etc. This issue is causes due to you doesn't  implemented authentication correctly for your app
Please follow the document- https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/manage-teams-identity?pivots=programming-language-javascript

**Comment by ydogandjiev** [comment] 2022-11-15 16:58
Actually, this is the correct link that should be followed when implementing authentication for your Teams App:
https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/authentication/authentication

**Comment by sayali-MSFT** [comment] 2022-11-18 07:45
@MLEGIsilog - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by sayali-MSFT** [comment] 2022-11-18 08:50
@MLEGIsilog -
[#6091](https://github.com/MicrosoftDocs/msteams-docs/issues/6091)-We are checking the status of the fix release with the engineering team. We will let you know once we have any updates on it. 
[#6142](https://github.com/MicrosoftDocs/msteams-docs/issues/6142)-This is by design a difference between chat (react) and channel (angular)

**Closed** 2022-11-28 01:01 UTC
Labels: teams-developer-support, needs-author-feedback, status-no-recent-activity
