### ISSUE TITLE
Does Teams Notification Bot need MS Graph Permissions? 

### ISSUE THREAD

**Issue by AaronSchwarz0176** [MicrosoftDocs/msteams-docs#7920] opened 2023-01-18 15:27 UTC
I just completed the below tutorial on notification bots. 
One question on this one when it comes to authorizations:

When I deploy my app to Azure - do I need to grant MS graph permissions to the bot so it can send chat messages?

If yes, is there a list of permissions which is needed for the below tutorial?
In my case its a daemon application, so I'm thinking about application permission like 'Chat.ReadWrite.WhereInstalled'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4680d8ea-8210-67e0-7a1f-f24e94d58985
* Version Independent ID: 4680d8ea-8210-67e0-7a1f-f24e94d58985
* Content: [Build notification bot with JavaScript - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-notificationbot?tabs=vscode&tutorial-step=6)
* Content Source: [msteams-platform/sbs-gs-notificationbot.yml](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/sbs-gs-notificationbot.yml)
* Service: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment] 2023-01-19 05:53
@AaronSchwarz0176 - No, you don't need to grant any MS graph permissions to the bot. Just need to follow this step-by-step guide.

**Comment by AaronSchwarz0176** [comment] 2023-01-19 09:12
Okay thanks. Unfortunately my bot is not sending any notifications when deployed. Locally with sideloading I got it already working.

What would be the recommended way to debug it remotely? Where can I see logs?

**Comment by AaronSchwarz0176** [comment] 2023-01-19 12:01
Sounds good, but unfortunately my bot is not sending notifications in the deployed state.

So I'm trying to debug it with sideloading. But when starting the Debug session in VSC I get the following error:
× AadCreateAppError: Failed to create an app in Azure Active Directory.
But actually I want to reuse an existing AAD app.

I tried with the following config:

1.    in config.dev.json & config.local.json I added the following:

```
"bot": {
        "appId":  clientID
        "appPassword": clientSecret
        "objectId": objectID
    },
    "auth": {
        "clientId": clientID
        "clientSecret": clientSecret,
        "objectId": objectID
        }
```

2.  In provision parameters I added this:

```
 "provisionParameters": {
      "value": {
        "botAadAppClientId": clientID
        "botAadAppClientSecret":  clientSecret,
        "teamsAppTenantId": "tenantID"
...
      }
```

But it still seems to be trying to register a new AAD app... Any ideas?

**Comment by Prasad-MSFT** [comment] 2023-01-20 12:10
@AaronSchwarz0176 - It will create a new AAD app by its own. 
In Azure AD, [app provisioning](https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/user-provisioning) refers to automatically creating copies of user identities in the applications that users need access to, for applications that have their own data store, distinct from Azure AD or Active Directory.

**Comment by AaronSchwarz0176** [comment] 2023-01-20 12:51
But when deploying to Azure I was able to reuse my AAD app. Why is it not possible while sideloading? 

One other thing I don't understand yet:
I'm deploying my bot to Azure, but I can publish my bot as well to Teams.
How are these two deployments related? Are they completely independent? 

I recognized once I deploy a new version to Azure, my teams app seems as well updated.
But in which case do I need to publish to Teams then? Is it only a one-time operation for the initial provisioning and after that its sufficient to deploy to Azure?

**Comment by Prasad-MSFT** [comment] 2023-01-23 08:08
We followed [this](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-notificationbot?tabs=vscode) guide and the sample worked properly.
Please refer below document which explains provisioning and publishing bot in Azure.
https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp

**Comment by AaronSchwarz0176** [comment] 2023-01-23 11:15
Thats not really answering my question.

**Whats the difference between "deploy to the cloud" and "publish to teams"?**

**Comment by ChetanSharma-msft** [comment] 2023-01-23 12:08
Hello @AaronSchwarz0176 - 
Hope you are doing well!!

Teams' toolkit is a quicker and zero-code way of creating and testing your apps locally and also allow you to deploy the app so that it will be available publicly.

We have 2 different ways to run and test the application.
1) If you are just clicking on debugging in Visual Studio Code, it is automatically creating the required resources internally and publishing your apps to Teams which is available for local testing and debugging.

2) But if you are deploying the app to azure, it will allow you to create new cloud resources to support your app. 
Also, you can further extend your apps like adding authentication for your bot etc.

Thanks!!

**Comment by AaronSchwarz0176** [comment] 2023-01-23 12:48
Thanks, that helped.

So deploying the App to Cloud/Azure is the right approach for updating business logic,
Publishing to teams is only updating metadata like version-number, app-name etc?

I guess the connection between these two is the teamsAppId in state.dev.json?
<img width="538" alt="image" src="https://user-images.githubusercontent.com/55433017/214042356-6a73daa9-cde8-4afc-8a63-7a2ea26f8a2a.png">

One more question:

My app is constantly showing 0 Bot-Installations, although I deployed/published/installed the latest version.

Any chance how this can happen? Is there some kind of caching when a new version is published? Any chance to debug/reset this bot-installations?

**Comment by AaronSchwarz0176** [comment] 2023-01-24 11:15
I read [here](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts%2Cjsts%2Cts4#add-storage) that the notifications connections should be stored at this place, when the bot is deployed:

[${process.env.TEMP}/.notification.localstore.json, if process.env.RUNNING_ON_AZURE is set to 1.
](url)

How can I access this file?

**Comment by Prasad-MSFT** [comment] 2023-01-24 12:02
Okay, @AaronSchwarz0176 - We are checking on it. We will get back to you if there is any update.

**Comment by AaronSchwarz0176** [comment] 2023-01-25 11:51
I added a Azure blob storage now, as described [here](https://github.com/OfficeDev/TeamsFx-Samples/blob/1e1c86c6f294012438474bb2f806e307d607c47b/adaptive-card-notification/README.md#optional-use-azure-blob-storage-to-persist-notification-connections).

My container is created successfully and I don't see error, but container stays empty and no bot installations seem to be  persisted.

**Comment by AaronSchwarz0176** [comment] 2023-01-27 09:06
Any Update on this?

I would like to go-live with my bot next month and at the moment I can't use it at all due to the missing persistence of the installations.

**Comment by ChetanSharma-msft** [comment] 2023-01-27 09:16
Hello @AaronSchwarz0176 - Sorry for delay in response.
Could you please share the error logs if any, so that we can investigate further on your issue?

**Comment by AaronSchwarz0176** [comment] 2023-01-27 09:19
So far I did not see any error logs, the storage is just never filled.

If there would be logs, where would I find them?

**Comment by ChetanSharma-msft** [comment] 2023-01-27 09:22
If you have deployed your application, could you please check if you see any log in your azure application insights?

**Comment by AaronSchwarz0176** [comment] 2023-01-27 09:31
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/55433017/215053645-55269a2c-23df-4060-9005-9c3e26280a3a.png">

Which table do you need? Exceptions is empty

**Comment by ChetanSharma-msft** [comment] 2023-01-27 09:45
Generally we see Exceptions table, but as per the above screeshots, it's returning result code as 401 which means unauthorized.

**Comment by AaronSchwarz0176** [comment] 2023-01-27 10:22
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/55433017/215062589-a661ef36-ded6-4ee7-a94c-0fa32e4df6cb.png">

Sorry the screenshot was a bit misleading.

As you can see the post-requests to /api/notification return status 200. 
/api/messages is not used/implemented. 


Why I believe there are no bot installations:

-  blob storage is empty 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/55433017/215063032-9b323c0b-ab72-491c-8ba5-eb2a0285790a.png">
- Post-Requests returns Code 200, and 0 Installations
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/55433017/215063204-3539af16-d687-4cef-9d9c-dca2472cdab5.png">
- Coding:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/55433017/215063490-182cb2cd-3712-411d-92d4-90e7cfda1e8b.png">

**Comment by ChetanSharma-msft** [comment] 2023-01-27 10:39
Thanks for sharing the details.
We are trying it from our end and let you know the updates.

**Comment by AaronSchwarz0176** [comment] 2023-01-31 10:02
@ChetanSharma-msft  Any update on this?

**Comment by ChetanSharma-msft** [comment] 2023-01-31 10:06
Hello @AaronSchwarz0176 - We have tried this sample but unfortunately facing issue while executing Windows PowerShell Command:
`Invoke-Webrequest -Method POST -URI http://localhost:3978/api/notification `

PS C:\WINDOWS\system32> Invoke-Webrequest -Method POST -URI http://localhost:3978/api/notification
Invoke-Webrequest : Unable to connect to the remote server

So, we are looking into it and once it is resolved we will let you know the further updates.

**Comment by AaronSchwarz0176** [comment] 2023-02-03 10:37
Thanks for the effort. 

Can you foresee when you can provide a solution?
We are currently planning the go-live of our notification-bot and currently we are fully blocked due to this.

**Comment by ChetanSharma-msft** [comment] 2023-02-03 12:23
Hello @AaronSchwarz0176 - Could you please confirm whether your app is working find locally and getting notifications with or without using storage connection?

Also, could you please try to install the app for different users and let us know if its working or not?

**Comment by AaronSchwarz0176** [comment] 2023-02-03 12:34
App is working fine locally, notification connections are stored in project root file: .notification.localstore.json. 

I tried as well for other users, there as well no connections are persisted.

**Comment by ChetanSharma-msft** [comment] 2023-02-03 15:25
Is it storing data in blob storage for locally running app?

**Comment by AaronSchwarz0176** [comment] 2023-02-03 15:26
No, blob storage is not filled at all.

**Comment by ChetanSharma-msft** [comment] 2023-02-06 07:26
Hello @AaronSchwarz0176 - Just wanted to inform your that we are still trying to repro this blob issue and let you know the updates.

**Comment by AaronSchwarz0176** [comment] 2023-02-07 10:31
Anything you need from me additionally? Also happy to jump on a debug session if that helps.

**Comment by ChetanSharma-msft** [comment] 2023-02-07 10:56
Hello @AaronSchwarz0176 - We are checking it from our end and facing different issues on multiple machines.
We will let you know for your help if needed.

**Comment by AaronSchwarz0176** [comment] 2023-02-08 12:47
Can you give any advice how to debug that blob storage connection?

I can see that the container is created, but it has public access level "private", might that be a problem? 
Is there a place where I can get logs for the blob storage connection? 

![image](https://user-images.githubusercontent.com/55433017/217533553-3ef48d0e-cdef-44eb-aca5-bbda21b66dc7.png)

**Comment by ChetanSharma-msft** [comment] 2023-02-08 13:10
Hello @AaronSchwarz0176 - Do you see any option to make it as public?
Regarding blob storage log, I will check and let you know.

**Comment by AaronSchwarz0176** [comment] 2023-02-10 12:56
Public blob storage is currently prohibited by my org policy...

But as I'm accessing through an connection-string, I think it should not need a public access, right?

I'm getting my connection-string from "Access keys" of my storage account, is that correct? Or do I need a shared access signtature (SAS)? 

<img width="986" alt="image" src="https://user-images.githubusercontent.com/55433017/218097186-3c305903-57a8-4470-9aa4-de2169a8e864.png">

**Comment by ChetanSharma-msft** [comment] 2023-02-10 15:43
Hello @AaronSchwarz0176 - This is the correct way of getting storage connection string.
Sorry for the delay, we are still checking on it from our end and let you know the updates.

**Comment by ChetanSharma-msft** [comment] 2023-02-13 05:06
Hello @AaronSchwarz0176 - We are also experiencing the behaviour where storage is always empty.

We will check other bot framework samples and let you know the updates.

**Comment by Prasad-MSFT** [comment] 2023-02-13 12:34
@AaronSchwarz0176 - We tried [this](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/45.state-management) bot-builder sample locally and noticed that user and conversation data in bot is getting stored in Azure blob storage.

` var storage = new AzureBlobStorage("<blob-storage-connection-string>", "bot-state");`

We will check your issue with engineering team, and we will inform you if there is any update. Thanks!

**Comment by AaronSchwarz0176** [comment] 2023-02-14 07:21
Thanks, that sounds promising.

so is that implementation something I can try for my notification bot as well?

**Comment by ChetanSharma-msft** [comment] 2023-02-20 03:33
Hello @AaronSchwarz0176 - We are checking the issue with engineering team.
Meanwhile, you can try to implement the notification bot.

**Comment by AaronSchwarz0176** [comment] 2023-02-20 09:19
okay, I can't find the source of the AzureBlobStorage class and it is csharp, can't use that ... 

So waiting for the engineering team, thanks.

**Comment by Prasad-MSFT** [comment] 2023-02-21 05:12
@AaronSchwarz0176 - This is in node JS. Please have a look.
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/45.state-management

**Comment by AaronSchwarz0176** [comment] 2023-02-22 09:20
Unfortunately I don't see how I can apply this to my project...

When can we expect answer from the engineering team?

**Comment by ChetanSharma-msft** [comment] 2023-02-22 12:54
Hello @AaronSchwarz0176 - We are checking with engineering team and let you know the updates.

**Comment by hund030** [comment] 2023-02-24 09:43
@AaronSchwarz0176 You get 401 when post `api/messages`, which means your bot is not setup correctly. I think that's why you can't receive notification from bot.
That's usually caused by wrong botId & botPassword. Could you check your app service app setting? The BOT_ID should be the client id of your AAD app, and the BOT_PASSWORD should be the client secret.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/26134943/221145785-d40db8be-990d-41d1-81b7-ac7d6f77758f.png">

**Comment by AaronSchwarz0176** [comment] 2023-02-24 10:52
@hund030 BOT_ID and BOT_PASSWORD are matching clientID and clientSecret of my AAD app registration.

What is this api/messages endpoint supposed to do? Do I really need it for sending notifications? 

I did not implement anything here, my code is listening to /api/notification.
![image](https://user-images.githubusercontent.com/55433017/221159482-051ee9b9-8a15-4441-888c-b5be2309d302.png)

These post-requests seemed to be automatically triggered, not by me. 

When I send a POST request with a valid access token and a empty JSON to /api/messages it returns Code 400 Bad Request "Error: validateAndFixActivity(): missing activity type."

Do you have sample payload for this endpoint to verify if it will return 401 as well?

**Comment by swatDong** [comment] 2023-02-28 03:49
@AaronSchwarz0176 `/api/messages`, `BOT_ID`, and `BOT_PASSWORD` are used to connect your bot code with Teams bot app. So 401 means your bot is not correctly connected.

As you mentioned you *reuse an existing AAD app*, do you also reuse the **bot registration (Azure Bot Service)**? If so, please make sure following IDs have the same value:
- The `bots.botId` in your teams app manifest.json
- The `Microsoft App ID` in your Azure Bot Service's configuration
- The `BOT_ID` in your app service app settings

In addition, you can directly log the request header/body of `/api/messages` to get sample payload:
``` typescript
server.post("/api/messages", async (req, res) => {
  /// add log here... e.g., req.header..., req.body...

  await bot.requestHandler(req, res);
});
```
You can manually trigger "/api/messages" by entering anything in the Teams chat with your bot.

cc @hund030

**Comment by AaronSchwarz0176** [comment] 2023-02-28 09:55
@swatDong thanks for the input.

I can verify that bots.botid, microsoft app id and bot_Id all have the same value. 

One more detail: I added my Azure IDP as authentication config in the app service: 
<img width="827" alt="Bildschirm­foto 2023-02-28 um 10 41 14" src="https://user-images.githubusercontent.com/55433017/221817650-b0377e67-e4c6-46ce-ab54-297ae1eb94d0.png">


When I disable this config, the requests to /api/messages/ are returning 200, however then my requests to /api/notifications are failing with the following error: 

"Error: Get Token request returned http error: 400 and server response: {\"error\":\"unauthorized_client\",\"error_description\":\"AADSTS700016: Application with identifier '2e4(...)' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant." 

Any ideas?

**Comment by AaronSchwarz0176** [comment] 2023-02-28 10:44
I changed my app config to "multitenant" and now the notifications are sent!

<img width="527" alt="image" src="https://user-images.githubusercontent.com/55433017/221831052-a711f3d4-c2ca-40fe-88da-93ccb3677429.png">

My admin told me that multi-tenant is not supported in general - **Is it really mandatory for the bot to work?**

**Comment by swatDong** [comment] 2023-03-01 06:55
@AaronSchwarz0176 

For the authentication part - it seems your authentication config on app service applies to both `/api/messages` and `/api/notification` APIs. I'd suggest to only add auth to `/api/notification`, not to `/api/messages`.
- `/api/messages` has its own auth logic in Bot Framework SDK, so your auth config may impact it.
- `/api/notification` by default is anonymous and you can add any auth config to it.

For the multi-tenant part - now bot supports both single-tenant and multi-tenant, but you need to update your code as well.
If your project is generated by latest Teams Toolkit, there should be a `MultiTenant` value in `initialize.js|ts`, and you need to update that value as well.
For example, our sample has the similar code - https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/stocks-update-notification-bot/bot/src/internal/initialize.ts#L11
And change it to:
``` javascript
  adapterConfig: {
    MicrosoftAppId: process.env.BOT_ID,
    MicrosoftAppPassword: process.env.BOT_PASSWORD,
    //MicrosoftAppType: "MultiTenant",
    MicrosoftAppType: "SingleTenant",
    MicrosoftAppTenantId: "your-tenant-id"
  },
```

Or, if your project is generated earlier, it only supports multi-tenant. Since old bot SDK only supports multi-tenant. More doc can be found at https://learn.microsoft.com/azure/bot-service/bot-service-quickstart-registration

**Comment by AaronSchwarz0176** [comment] 2023-03-01 09:23
I adapted the config in initialize.js to SingleTenant and switched the Azure AD App to SingleTenant and re-deployed. Getting unauthorized_client again. I gave the tenantID of my Azure AD directory, correct? 

Which version is supporting single tenancy?
I'm running with the following versions currently:   
 "@microsoft/teamsfx": "^2.0.0",      
 "botbuilder": "^4.18.0"

**Comment by swatDong** [comment] 2023-03-01 10:20
The `"botbuilder": "^4.18.0"` supports single tenant.

Yep you need to re-provision again, to make sure all resources are configured as single tenant:
- Your AAD app config (already done)
- Your bot code (already done)
- Your Azure Bot Service's configuration has `Bot Type: SingleTenant`
<img width="422" alt="image" src="https://user-images.githubusercontent.com/7642967/222110626-5c9204c1-16dd-48a5-83c7-023163133ce2.png">

Also, to ensure your Teams app is up-to-date, better to uninstall the app then re-add the app to Team again.

**Comment by AaronSchwarz0176** [comment] 2023-03-01 10:26
<img width="633" alt="image" src="https://user-images.githubusercontent.com/55433017/222112835-78e580c1-673c-4b78-8e07-16e08164b0d2.png">

I can't even see that bot type setting?!

Should I set it in the coding?

**Comment by swatDong** [comment] 2023-03-01 11:07
Tenant was set at the bot creation time, so you may need to re-create the Azure Bot Service.

If your Azure Bot Service was created via provision:
- Delete the Azure Bot Service
- Update `templates/azure/provision/botService.bicep` to add **msaAppType** and **msaAppTenantId**
```
  properties: {
    displayName: botDisplayName
    endpoint: uri(botEndpoint, '/api/messages')
    msaAppId: botAadAppClientId
    msaAppType: 'SingleTenant'
    msaAppTenantId: 'your-tenant-id'
  }
```
- Re-provision to re-create Azure Bot Service


In addition, after reinstall the teams app, please also clear old notification connections from your storage if you have your own storage. (Or restart the app service to make sure the temp storage is cleared as well)

**Comment by AaronSchwarz0176** [comment] 2023-03-01 12:03
Now we are back at the initial problem again, bot is not returning any installations, storage is empty.

I deleted the bot service, updated the .bicep file, "SingleTenant" is now visible in Azure Portal. 

I reprovisioned, redeployed, republished, reinstalled teams app, restarted the app service. 

Any ideas?

**Comment by AaronSchwarz0176** [comment] 2023-03-01 13:16
I disabled my app service auth config  - now I get the unauthorized_client again as earlier...

**Comment by swatDong** [comment] 2023-03-02 02:21
Per my test, `unauthorized_client` occurs when "SingleTenant" is not correctly set in the code `initialize.js`.
To support single tenant, need to use `CloudAdapter` and set `MicrosoftAppType: "SingleTenant"`. E.g.,
``` javascript
const { BotBuilderCloudAdapter } = require("@microsoft/teamsfx");
const ConversationBot = BotBuilderCloudAdapter.ConversationBot;
...

// Create bot.
const bot = new ConversationBot({
  // The bot id and password to create CloudAdapter.
  // See https://aka.ms/about-bot-adapter to learn more about adapters.
  adapterConfig: {
    MicrosoftAppId: config.botId,
    MicrosoftAppPassword: config.botPassword,
    MicrosoftAppType: "SingleTenant",
    MicrosoftAppTenantId: "{{your-tenant-id}}"
  },
...

```

Fine to have a call on this. Is it convenient to contact you on Teams? (I did not find any contact info from your github profile)

**Comment by AaronSchwarz0176** [comment] 2023-03-02 09:25
After upgrading to "@microsoft/teamsfx": "^2.2.0" this did the trick for me :) 

Thanks a lot for the great support @swatDong!

**Comment by Prasad-MSFT** [comment] 2023-03-27 11:39
We are closing this issue for now. Please feel free to reopen if required. Thanks!

**Closed by Prasad-MSFT** 2023-03-27 11:39 UTC
Labels: teams-developer-support
