### ISSUE TITLE
Can't create new app in App Studio

### ISSUE THREAD

**Issue by treyco** [MicrosoftDocs/msteams-docs#952] opened 2019-09-16 05:47 UTC
Whenever I go and create a new app from scratch, I get the error "Failed to create app." I've seen some of the issues raised here before but I don't know how they were fixed.

**Comment by Gousia-MSFT** [comment] 2019-09-16 06:54
@treyco Are you getting the error when you try to install the app? Can you please share a screenshot for a better understanding?

**Comment by treyco** [comment] 2019-09-16 07:17
This is the error I get when I create a new app.

![image](https://user-images.githubusercontent.com/8473380/64939895-0826d480-d895-11e9-8a20-ec24e4e4f8a6.png)

**Comment by Gousia-MSFT** [comment] 2019-09-16 07:33
@treyco  Thanks for sharing the screenshot. We are looking into it.

**Comment by Gousia-MSFT** [comment] 2019-09-19 04:01
Duplicate of [#955](https://github.com/MicrosoftDocs/msteams-docs/issues/955). Please refer this issue for the solution.

**Comment by Gousia-MSFT** [comment] 2019-09-30 11:30
Please re-open if you still face an issue.

**Closed by Gousia-MSFT** 2019-09-30 11:30 UTC
