### ISSUE TITLE
Message action not working on one specific message in a channel

### ISSUE THREAD

**Issue by tomqmr** [MicrosoftDocs/msteams-docs#6315] opened 2022-06-28 09:38 UTC
We found an issue on Teams with our messaging extension on ONE specific message in a channel : when clicking on a message action (... -> Other actions -> actions from our extension), nothing happens, and the request never reaches the bot framework. We didn't manage to reproduce this behavior on another message, the message content is not the problem here because we copy/paste it and even rewrite it manually and it works. But by using Teams on web (chrome) instead of desktop application, we found 2 things : 

- In html, the message has this class : `has-input-extensions-long` that other messages don't have.
- When clicking on our action, there is this error in the console (where the expression is the message content) :

```
Error: Syntax error, unrecognized expression: J'arrive pas a reproduire systématiquement mais des fois je fais la création du dossier et je n'ai pas la carte dans le champ de saisie
    at se.error (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-92954a0.js:1:13606)
    at se.tokenize (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-92954a0.js:1:21617)
    at se.select (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-92954a0.js:1:22444)
    at Function.se (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-92954a0.js:1:7089)
    at e.find (https://statics.teams.cdn.office.net/hashed/2-vendor.min-b9e4432.js:1:780879)
    at S.fn.init.find (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-92954a0.js:1:25014)
    at S.fn.init (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-92954a0.js:1:25503)
    at new e.fn.init (https://statics.teams.cdn.office.net/hashed/2-vendor.min-b9e4432.js:1:780476)
    at S (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-92954a0.js:1:1024)
    at e.forEachSemanticObject (https://statics.teams.cdn.office.net/hashed/3.2-app.min-82d71d5.js:1:9008150) undefined
(anonymous) @ 0.2-angular-jquery.min-92954a0.js:114
(anonymous) @ 0.2-angular-jquery.min-92954a0.js:85
(anonymous) @ 3.1-app.min-98827c1.js:1
f @ 0.2-angular-jquery.min-92954a0.js:127
(anonymous) @ 0.2-angular-jquery.min-92954a0.js:127
$eval @ 0.2-angular-jquery.min-92954a0.js:142
$digest @ 0.2-angular-jquery.min-92954a0.js:139
v.$digest @ 3.2-app.min-82d71d5.js:1
$apply @ 0.2-angular-jquery.min-92954a0.js:142
(anonymous) @ 0.2-angular-jquery.min-92954a0.js:270
dispatch @ 0.2-angular-jquery.min-92954a0.js:1
v.handle @ 0.2-angular-jquery.min-92954a0.js:1
```

The issue might not be easy to reproduce so I hope these 2 clues can help you to find what is the problem.

**Comment by sayali-MSFT** [comment] 2022-06-28 10:25
@tomqmr -We will look into it and get back to you.

**Comment by sayali-MSFT** [comment] 2022-06-29 13:46
@tomqmr -We are not able to reproduce the issue, Could you please share the Bot Id, timestamp, appId  for investigation purpose, so that we can check the error log.
We are referring following sample-
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/51.teams-messaging-extensions-action

**Comment by ChetanSharma-msft** [comment] 2022-07-11 16:15
We will check on the error logs & get back to you.

**Comment by sayali-MSFT** [comment] 2022-07-12 05:15
@tomqmr -We would need to debug the issue, is there a way to access the message?

**Comment by ChetanSharma-msft** [comment] 2022-07-25 07:11
@tomqmr - Since we are not able to repro your issue, shall we close it or please suggest here ?

**Closed** 2022-07-25 07:28 UTC
Labels: teams-developer-support, needs-author-feedback
