### ISSUE TITLE
[New Teams on Mac] window.open always returns NULL

### ISSUE THREAD

**Issue by tysoncai** [MicrosoftDocs/msteams-docs#10012] opened 2023-11-27 01:41 UTC
Hi team,

We found an issue when developing our MS Teams tab app on new Teams client on macOS.

**Steps to reproduce:**
1. Call window.open(url) in our app.
2. The new window with url will be opened, but the response of window.open is NULL.

<img width="591" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/146057762/e50777f6-0149-42ad-be5c-6d8e476f8f24">

**Expect:**
window.open should return the Window object.

**App version:**
<img width="284" alt="image" src="https://github.com/MicrosoftDocs/msteams-docs/assets/146057762/820f6ad2-378d-4417-8f45-f8e087947dd2">

**OS:** 
MacOS Big Sur Version 11.7

**Comment by Prasad-MSFT** [comment] 2023-11-27 05:50
@tysoncai - Thanks for raising your issue. We will check this at our end and will update you accordingly.

**Comment by Prasad-MSFT** [comment] 2023-11-28 10:44
Hi @tysoncai - We have raised a bug for the same. We will inform you once we get any further update from engineering team. Thanks!

**Comment by Prasad-MSFT** [comment] 2024-01-03 13:17
Hi @tysoncai - We got update from engineering team that, "this behaviour is by design. We do not allow apps to open windows in the Teams Desktop Client (both in T1 and T2.1) to protect our users from spoofing attacks. Any calls to window.open are blocked and the specified URL is launched in the user's default browser. We cannot provide a handle to the browser window since that runs in a completely different process."

The only exception to this rule is for authentication popups that need to be opened via a call to our authentication.authenticate API:
https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#@microsoft-teams-js-authentication-authenticate

**Comment by Prasad-MSFT** [comment] 2024-01-08 07:26
We are closing this issue for now. Please feel free to reopen if required. Thanks!

**Closed by Prasad-MSFT** 2024-01-08 07:26 UTC
Labels: teams-developer-support, bug, T2.1
