### ISSUE TITLE
Documentation for OnTeamsMessagingExtensionSelectItemAsync

### ISSUE THREAD

**Issue by dangaier** [MicrosoftDocs/msteams-docs#1222] opened 2019-12-13 19:20 UTC
There's no documentation for OnTeamsMessagingExtensionSelectItemAsync.  Yes, there's a sample, but that's it.

Does OnTeamsMessagingExtensionSelectItemAsync support returning an AdaptiveCard?  

It works when I return a ThumbnailCard or HeroCard as the MessagingExtensionAttachment.  In this case, Microsoft Teams properly inserts the card in the compose area.

But it doesn't seem to work when I return an Adaptive card as the MessagingExtensionAttachment.  In this case, Microsoft Teams does nothing.  The Adaptive Card is not inserted in the compose area.

If I take that same Adaptive Card and return it as part of OnTeamsMessagingExtensionQueryAsync, then everything works!

Here's what I'm trying to do:
1) In OnTeamsMessagingExtensionQueryAsync, return Thumbnail Cards as Preview Cards - they will have the following for the "Tap" property: Tap = new CardAction { Type = "invoke", Value = new { ID = ticket.ID} }
2) Once the user picks one, Teams will call OnTeamsMessagingExtensionSelectItemAsync.  In this method, I want to lookup the item by the passed in ID to get additional information and create a rich Adaptive Card to return to get inserted into the compose area.

**Comment by Trinetra-MSFT** [comment] 2019-12-16 06:16
@dangaier , The messaging extension does not allow sending adaptive cards like that. It requires using the `MessagingExtensionResult` of the framework and just the card sent in the response.

When you get a call from the messaging extension its action is of type `"composeExtension/query"`

Create a list 
```
var invokeResponse = new MessagingExtensionResponse();
var results = new MessagingExtensionResult
{
    AttachmentLayout = "list",
    Type = "result",
    Attachments = new List<MessagingExtensionAttachment>(),
};
```

Now create a MessagingExtensionAttachement
```
results.Attachments.Add(new MessagingExtensionAttachment
{
    ContentType = "application/vnd.microsoft.teams.card.adaptive",
    Content = JsonConvert.DeserializeObject(cardData),
    Preview = new Attachment
    {
        ContentType = "application/vnd.microsoft.card.thumbnail",
        Content = new AttachmentContent
        {
            text = "Project: " + task.ProjectName,
            title = task.Name,
        },
    }
});
```

send the invoke response
 ```
 return new InvokeResponse
            {
                Body = invokeResponse,
                Status = 200,
            };
```

All of the above is using Microsoft.Bot.Builder.Teams, Microsoft.Bot.Connector.Teams, Microsoft.Bot.Schema.Teams in the latest versions.

**Comment by dangaier** [comment] 2019-12-16 15:39
Yes, I know.  Obviously I'm using the Bot.Builder and Teams SDKs because I'm asking about OnTeamsMessagingExtensionSelectItemAsync!!!  

Yes, I'm returning a MessagingExtensionResult.  But it doesn't seem to work when I return a MessagingExtensionResult w/ Adaptive Card in OnTeamsMessagingExtensionSelectItemAsync.  Again, it works fine when I return the exact same thing in OnTeamsMessagingExtensionQueryAsync.

So again, my question:
Does OnTeamsMessagingExtensionSelectItemAsync support returning a MessagingExtensionResult with an AdaptiveCard attachment?  Again, I can get it to work when returning a Hero or Thumbnail, but not an Adaptive Card.

**Comment by clearab** [comment] 2019-12-17 18:24
This would be silly but, does your AdaptiveCard have a preview (even though at that point in the flow it would be pointless)?

**Comment by Trinetra-MSFT** [comment] 2019-12-18 18:21
@dangaier , @clearab , Sorry for the wrong understanding. Yes @clearab  is right, There should be preview property in your adaptive card attachment. You can display a preview of an Adaptive Card or Office 365 Connector card in the result list simply by its preview property.
Please take a look at [Response card types & Preview](https://docs.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/how-to/search-commands/respond-to-search?tabs=json#response-card-types-and-previews)

```
var attachment = new MessagingExtensionAttachment
                    {
                        ContentType = ,
                        Content = ,
                        Preview = card.ToAttachment()
                    };
```

**Comment by dangaier** [comment] 2019-12-18 18:48
You're not following...please have someone who understands Messaging Extensions in Teams take a look at this.
OnTeamsMessagingExtensionSelectItemAsync is invoked when you select a Messaging Extension preview item.   OnTeamsMessagingExtensionSelectItemAsync should return the full (not preview) card that you want to insert into the compose area.

Yes there's a sample app that shows how to use it: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/50.teams-messaging-extensions-search/Bots/TeamsMessagingExtensionsSearchBot.cs

But the sample returns a Thumbnail card in OnTeamsMessagingExtensionSelectItemAsync.  The Sample doesn't work if you return an Adaptive Card.  And that's what I'm asking.  Does OnTeamsMessagingExtensionSelectItemAsync support returning an Adaptive Card.  And if yes, then how can I achieve that?

**Comment by Trinetra-MSFT** [comment] 2019-12-19 12:22
This looks like a regression bug, this was working fine few weeks back. I have raised bug for this. I'll update you on this.

**Comment by Gousia-MSFT** [comment] 2020-02-28 09:27
The fix for a possible cause of this has been checked in. Could you please check this and re-open if you are still facing the issue.

**Closed by Gousia-MSFT** 2020-02-28 09:27 UTC
Labels: bug
