### ISSUE TITLE
How to remove Teams app top tab refresh, open in new window, open in browser

### ISSUE THREAD

**Issue by yoohyojun** [MicrosoftDocs/msteams-docs#10021] opened 2023-11-28 08:05 UTC
![1](https://github.com/MicrosoftDocs/msteams-docs/assets/80876813/2c8078a6-53da-4160-8611-5bf2d5d4b86f)

I would like to remove the icon in the part marked by the blue line. I searched to edit the manifest, but could not find it

![이미지 (1)](https://github.com/MicrosoftDocs/msteams-docs/assets/80876813/c1b6956e-438c-454b-a61f-5b5a07fa55ca)

There is no open new browser button in the teams sample app. I would like to change it to something like that.

**Comment by Prasad-MSFT** [comment] 2023-11-28 10:25
@yoohyojun - There isn't any way to remove the tab refresh/open in browser/open in new window icons from Teams app.
To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by yoohyojun** [comment] 2023-11-29 02:46
However, in the second picture, open in new window icons do not exist. Is there a way to remove this?

**Comment by yoohyojun** [comment] 2023-11-29 02:47
> @yoohyojun - There isn't any way to remove the tab refresh/open in browser/open in new window icons from Teams app. To achieve your requirements, we recommend you give your feedback in [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

However, in the second picture, open in new window icons do not exist. Is there a way to remove this?

**Comment by yoohyojun** [comment] 2023-11-29 02:48
@Prasad-MSFT 

However, in the second picture, open in new window icons do not exist. Is there a way to remove this?

**Comment by Prasad-MSFT** [comment] 2023-11-29 06:52
'Open tab in new window' only shows in Teams Desktop client. It is not available in Teams Web client. That is by design.
Teams Desktop:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/4178f5cb-0174-4ab0-aa42-091d12f9d3b6)
Teams Web:
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/3da9080b-7419-4f3f-b8b7-0ba63ba0f6af)

**Comment by Prasad-MSFT** [comment] 2023-12-01 06:45
We are closing this issue for now. Please feel free to reopen if required. Thanks!

**Closed by Prasad-MSFT** 2023-12-01 06:45 UTC
Labels: teams-developer-support
