### ISSUE TITLE
Web hook feature deprecation in Teams

### ISSUE THREAD

**Issue by benark** [MicrosoftDocs/msteams-docs#11224] opened 2024-07-08 15:10 UTC
### Type of issue

Outdated article

### Feedback

This entire feature is being removed in July-August 2024.
See: https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/webhooks-and-connectors/how-to/add-incoming-webhook.md

### Author

@surbhigupta

### Document Id

e3b53e27-2946-189c-623b-9df704ea8f12

**Comment by Prasad-MSFT** [comment] 2024-07-10 06:10
Duplicate of: https://github.com/MicrosoftDocs/msteams-docs/issues/11225

**Closed by Prasad-MSFT** 2024-07-10 06:10 UTC
Labels: needs-triage :mag:
