### ISSUE TITLE
Provide example on how to support SameSite cookie attribute

### ISSUE THREAD

**Issue by GFoley83** [MicrosoftDocs/msteams-docs#1262] opened 2020-01-10 02:10 UTC
Can you confirm that no other code is needed to make sure the approach covered above supports the SameSite cookie attribute?

Currently when testing in Chrome with the following flags enabled:
chrome://flags/#same-site-by-default-cookies
chrome://flags/#cookies-without-same-site-must-be-secure

I can see that cookies issued from http://login.microsoftonline.com are being blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e66ffa-ec00-4a84-a43d-d47e3c138b32
* Version Independent ID: 47e9a383-ac6a-dc7d-2d91-a9e09626fdab
* Content: [Silent authentication - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad?source=docs)
* Content Source: [msteams-platform/tabs/how-to/authentication/auth-silent-aad.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-silent-aad.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **anclear**

**Comment by Trinetra-MSFT** [comment] 2020-01-10 07:25
Closing this it is a duplicate of #1263 .

**Closed by Trinetra-MSFT** 2020-01-10 07:25 UTC
