### ISSUE TITLE
[Rendering] Incorrect rendering of element widths in ColumnSet on iOS

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4501] opened 2021-11-01 22:19 UTC
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6668 

**Details from original post:**
### Target Platforms

iOS

### SDK Version

1.4

### Application Name

Microsoft Teams

### Problem Description

In my application I am using Adaptive Card with **ColumnSet** which includes:
- button containing a large letter with the width set to: `auto`
- text with the width set to: `stretch`

This Adaptive Card is displayed correctly on all platforms except iOS, where the width of the buttons is cut off and the letter it contains is not visible.

### Screenshots

Adaptive Card displaying incorrectly on iOS:
![iOS](https://user-images.githubusercontent.com/89073193/139709873-c0e27bf8-bf3b-4b31-8dee-26b4fd96eda7.png)

Correct Adaptive Card on Windows:
![Windows](https://user-images.githubusercontent.com/89073193/139709927-212d20ad-a5dc-471a-ad07-a31c33df072b.PNG)

Correct Adaptive Card on Android:
![Android](https://user-images.githubusercontent.com/89073193/139709910-fee5165b-97fa-409e-94d8-d427f0ec1992.jpg)

### Card JSON

```JSON
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.4",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "text": "Lernpaket: All quiz types",
              "wrap": true,
              "fontType": "Default",
              "size": "Small"
            }
          ]
        },
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "TextBlock",
              "text": "2/5",
              "fontType": "Default",
              "size": "Small",
              "horizontalAlignment": "Right"
            }
          ]
        }
      ]
    },
    {
      "type": "TextBlock",
      "text": "What city do The Beatles come from?",
      "height": "stretch",
      "wrap": true
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "width": "auto",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "A",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "answerLetter",
                      "value": {
                        "action": "answerQuiz",
                        "previousQuizId": "question.id",
                        "previousQuizAnswerId": "answer.id",
                        "previousQuizAnswers": "question.id"
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "spacing": "Medium",
          "items": [
            {
              "type": "TextBlock",
              "text": "Liverpool",
              "wrap": true
            }
          ]
        }
      ],
      "style": "default",
      "spacing": "Medium"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "width": "auto",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "B",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "answerLetter",
                      "value": {
                        "action": "answerQuiz",
                        "previousQuizId": "question.id",
                        "previousQuizAnswerId": "answer.id",
                        "previousQuizAnswers": "question.id"
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "spacing": "Medium",
          "items": [
            {
              "type": "TextBlock",
              "text": "Edinburgh",
              "wrap": true
            }
          ]
        }
      ],
      "style": "default",
      "spacing": "Medium"
    },
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "auto",
          "items": [
            {
              "type": "ActionSet",
              "width": "auto",
              "actions": [
                {
                  "type": "Action.Submit",
                  "title": "C",
                  "data": {
                    "msteams": {
                      "type": "messageBack",
                      "displayText": "answerLetter",
                      "value": {
                        "action": "answerQuiz",
                        "previousQuizId": "question.id",
                        "previousQuizAnswerId": "answer.id",
                        "previousQuizAnswers": "question.id"
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        {
          "type": "Column",
          "width": "stretch",
          "spacing": "Medium",
          "items": [
            {
              "type": "TextBlock",
              "text": "London",
              "wrap": true
            }
          ]
        }
      ],
      "style": "default",
      "spacing": "Medium"
    }
  ]
}
```

### Sample Code

_No response_---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Prasad-MSFT** [comment] 2021-11-02 14:50
@MajaEffenberg 
We are trying to repro the issue. We will get back to you shortly

**Comment by Prasad-MSFT** [comment] 2021-12-06 07:57
@MajaEffenberg - The issue is fixed now. Please update your MS Teams app in iOS and check. `Version- 3.19.0`
Adding the screenshot for reference:
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/62237649/144808618-c0ac98fd-03f7-487f-878c-b730ac37061d.png)

**Comment by v-chetsh** [comment] 2021-12-09 05:47
@MajaEffenberg - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by MajaEffenberg** [comment] 2021-12-09 08:24
@v-chetsh - We updated our MS Teams app in iOS and tested it again and everything looks correct now, so I can confirm that the issue has been fixed.

Thanks! And feel free to close this issue

![MicrosoftTeams-image](https://user-images.githubusercontent.com/89073193/145359490-d7d273de-4c4c-4174-804c-701e2c04898c.png)

**Comment by Prasad-MSFT** [comment] 2021-12-09 08:27
@MajaEffenberg -Thanks for your confirmation. We are closing this issue. Please feel free to re-open if needed.

**Closed by Prasad-MSFT** 2021-12-09 08:27 UTC
Labels: teams-developer-support, needs-author-feedback
