### ISSUE TITLE
Code sample to be made available in the Office Dev repo.

### ISSUE THREAD

**Issue by v-pmuthyala** [MicrosoftDocs/msteams-docs#3135] opened 2021-04-19 09:32 UTC
Currently, the code sample is available in the developer's personal repo. It needs to be made available from the Office Dev repo for access by users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0307913-bb59-2ee4-112f-686ce3a4e959
* Version Independent ID: e83d245d-c51a-55c3-1607-78140dd54a7b
* Content: [Virtual Assistant for Microsoft Teams - Teams](https://review.docs.microsoft.com/en-us/microsoftteams/platform/samples/virtual-assistant?branch=master)
* Content Source: [msteams-platform/samples/virtual-assistant.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/samples/virtual-assistant.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by v-pmuthyala** [comment] 2021-04-19 09:35
@nebhagat, I've raised a Doc Bug, please update me once the code sample is available in the Office Dev repo.

**Comment by surbhigupta12** [comment] 2021-05-24 13:27
The issue is resolved in #3399

**Closed by surbhigupta12** 2021-05-24 13:27 UTC
Labels: doc-bug, needs-triage :mag:, teams-developer-support
