### ISSUE TITLE
microsoft teams js library has not been intialized

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#8782] opened 2023-06-05 06:20 UTC
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/8890 

**Details from original post:**
**microsoft teams js library has not been intialized**
we created tab app in teams , we need to authenticate tab app with third party oauth used documentation [refer link]( https://learn.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad?tabs=teamsjs-v2.)
For authentication i'm using "@microsoft/team-js" npm package, after authenticated successfully  while i calling authentication.notifySuccess(message)
to send response for success callback in that time i'm getting a grey screen with the error message of "the library has not been initialized".
For your reference here i'm attached the grey screen screenshots
![error image1](https://github.com/OfficeDev/TeamsFx/assets/131451049/b29274e3-8ff8-4d9c-a8fa-15decff21ab3)
![painted grey](https://github.com/OfficeDev/TeamsFx/assets/131451049/3a16f1a1-bdc2-47cc-ba8d-e448aaae0069)

some times it is working fine and most of time its not working .
thanks for advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Version Independent ID: b743e43d-95cc-3d1e-b142-31a16369f97e
* Content: [Teams Toolkit Overview - Teams](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teams-toolkit-fundamentals)
* Content Source: [msteams-platform/toolkit/teams-toolkit-fundamentals.md](https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/teams-toolkit-fundamentals.md)
* Service: **msteams**
* GitHub Login: @zyxiaoyuer
* Microsoft Alias: **zhany**

**Comment by sayali-MSFT** [comment] 2023-06-05 07:01
@integrationworktual - Thanks for reporting your issue.
We will check this at our end and will get back to you.

**Comment by integrationworktual** [comment] 2023-06-05 08:26
**@sayali-MSFT** - Thanks for responding to us.
we are awaiting for your response on the issue 
let us know if you have any further queries from our side.

Regrads,
IntegrationWorktual

**Comment by sayali-MSFT** [comment] 2023-06-05 10:15
@integrationworktual -Could you please share the TeamsJs library version?

**Comment by integrationworktual** [comment] 2023-06-05 10:24
@sayali-MSFT  
microsoft teamsjs  version: "@microsoft/teams-js": "^2.9.1"
react version :  "react": "^18.2.0"
node version : 16.15.0

regards,

**Comment by sayali-MSFT** [comment] 2023-06-05 11:30
@integrationworktual -We have test this scenario ,we are not able to repro the issue, it is working fine from our end.
microsoft teamsjs version: "@microsoft/teams-js": "^2.9.1"

We have tried with the below code-
```
 microsoftTeams.app.initialize().then((res)=>{
        microsoftTeams.app.getContext().then((context)=> {
        console.log("context-----",context);
        microsoftTeams.authentication.authenticate({
        url: window.location.origin+'/#/login',
        width: 800,
        height: 900,
        successCallback:((result)=> {
        console.log('success call back---',result);
        }),
        failureCallback:((err)=> {
        console.log("failure callback----------",err)
        })
        })       
        })
       .catch((err)=> {
        console.log("get context err",err);
           })
          });
```

![Screenshot 2023-06-05 162412](https://github.com/MicrosoftDocs/msteams-docs/assets/93527375/f127f808-c2cc-4679-95cc-813af16a6525)


As you mention above sometimes it is working sometime not. Could you please share network trace so that we can investigate further?

**Comment by sayali-MSFT** [comment] 2023-06-06 05:20
@integrationworktual -Thanks for providing information, we will check with the engineering team and let you know once we get any update.

**Comment by integrationworktual** [comment] 2023-06-06 06:33
@sayali-MSFT
Thanks .
we are waiting for the feedback

**Comment by integrationworktual** [comment] 2023-06-06 14:54
@sayali-MSFT 
thanks for advance 
any update on that issue

**Comment by nwojod-MSFT** [comment] 2023-06-06 19:12
@integrationworktual please can you share a snippet of your code on how you are initializing the SDK? This would help us investigate more to identify the root cause.

**Comment by integrationworktual** [comment] 2023-06-07 04:12
@nwojod-MSFT microsoft team has not been initialized  its happens only occassionly manner
here is my code - using teamjs library

    const openLoginPage=()=> {
        
        app.initialize().then((res)=> {
            
            app.getContext().then((context)=> {
                console.log("context-----",context);
                authentication.authenticate({   
                    url: window.location.origin+'/#/login',
                    width: 800,
                    height: 900,
                    successCallback:((result)=> {
                        console.log('success call back---',result);
                      
                    }),
                    failureCallback:((err)=> {
                     console.log("err-",err)
                        
                    })
                })


            })
            .catch((err)=> {
                console.log("get context err",err);
            })
        });

    }
after redirecting  page 

    const retrieve = async ()=> {

        console.log("retrieve -------------");
       let LogResp = new URLSearchParams(window.location.hash);
       let access_token = LogResp .get('access_token');
       if(access_token) {
        console.log("success fully redirected");
          authentication.notifySuccess(message);
       }
       else {
        console.log("not redirected");
        authentication.notifyFailure('failure');
       }
    
    }

    useEffect(()=> { retrieve();  },[]);
at redirecting page afer getting token  sometimes its not sending that authentication.notifysuccess() message so that only we are getting grey screen and window is not closing, unable to continue the application.

thanks for advance.

**Comment by integrationworktual** [comment] 2023-06-08 06:32
@nwojod-MSFT  
any update on that?

**Comment by nwojod-MSFT** [comment] 2023-06-08 16:32
Hi @integrationworktual apologies for the delay response. We were looking at this to understand where the issue may be coming from since it happens occasionally. To further help us investigate, can you give us a minimum repro scenario and what functions you are calling. 
One suggestion is to add two "consol.log" statements, one before the initialize and one before the authentication call. This will help us identify what part of the code gets executed and where the error is coming from.

**Comment by integrationworktual** [comment] 2023-06-09 04:22
@nwojod-MSFT  
this issue coming occasionally in web and mobile platform. could you please tell what log have do then() statement and authentication() call.

Thanks for advance,

**Comment by maglims** [comment] 2023-06-09 20:10
@integrationworktual 
For the cases that fail, when you click on the login button, does the sign-in pop-up window ever show up? If you add a log statement under this line 
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/8062622/d0e6699e-68e3-456f-a684-d32379e386bf)
 , do you see that log statement always being hit?

From the message, normally it indicates that either something wrong with app.initialize call, or the authentication.notifySuccess call is triggered before app.initialize finishes. If you add the logging statement under "
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/8062622/1fbd6998-70d3-4326-8fc9-ce6c4f837f59)
" when the scenario fails, could you check the sequence of the three logging statement ?
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/8062622/f4b242e1-7289-4a34-93da-5b4b10639604)

**Comment by integrationworktual** [comment] 2023-06-10 11:49
@maglims thanks for the response.
   window is showing whenever clicking the login button and  log are all is hitting.

 during failed scenarios also we getting those logs
console.log("retrieve");
console.log("success fully redirected");
console.log("you new loggin statement under app.initalize().then() call")

**Comment by maglims** [comment] 2023-06-12 16:43
@integrationworktual , thanks for the testing.

From the logging, it shows that authentication.notifySuccess is kicked off before app.initialize call is complete. In your code, please make sure authentication.notifySuccess awaits properly and gets kicked off after app.initialize completes 

Let us know if it resolves. Thanks.

**Comment by integrationworktual** [comment] 2023-06-15 03:56
@maglims, thanks for the feedback.

I agree your comment but this follow we are starting authenticating itself we calling app.initalize() after that only we call authenticate.notifysuccess().
In code wise how to change the authentication,notifysuccess() kickoff after completion of app.initialize()

Thanks.

**Comment by nwojod-MSFT** [comment] 2023-06-21 20:51
@integrationworktual your follow up question seems to be a general programming question and not about teams-js. Maybe try posting on StackOverflow, there are lots of helpful web programming tips over there. We will be closing this issue as it is not a sdk bug or question. Thanks

**Closed by nwojod-MSFT** 2023-06-21 20:51 UTC
Labels: teams-developer-support
