### ISSUE TITLE
Cannot install a Teams package with RSC definition anymore

### ISSUE THREAD

**Issue by timoleo23** [MicrosoftDocs/msteams-docs#1923] opened 2020-07-25 15:04 UTC
Following the online documentation, I managed to create and install a Teams app package to activate RSC permissions.
https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent

Everything worked nicely but when I now try to install a new package or even the initial one, the process to add the app to the Teams catalog fails with error "Something went wrong, please try again later." I tried different option but none succeeded.
I started to face this issue today (everything was fine on the 21st of July)

The process fails as soon as I set a permission in the "applicationpermissions" list
Is there an issue with this feature ?

Here is my app package

```
{
    "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
    "manifestVersion": "devPreview",
    "version": "1.0.0",
    "id": "af7c9b35-6087-XXXX-XXXX-1d61eb5e2edf",
    "packageName": "demo.teamsadoption.azurelogicapp",
    "developer": {
        "name": "GTCSM",
        "websiteUrl": "https://myapp",
        "privacyUrl": "https://myapp/privacy",
        "termsOfUseUrl": "https://myapp/tou"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "LogicApp-Analytics",
        "full": "Azure Logic App Analytics"
    },
    "description": {
        "short": "Azure Logic App used to collect Teams analytics",
        "full": "Connect Azure Logic App to collect your Microsoft Teams project analytics"
    },
    "accentColor": "#FFFFFF",
    "configurableTabs": [
        {
            "configurationUrl": "https://myapp/config.html",
            "canUpdateConfiguration": false,
            "scopes": [
                "team"
            ]
        }
    ],
    "webApplicationInfo": {
        "id": "af7c9b35-6087-XXXX-XXXX-1d61eb5e2edf",
        "resource": "https://RscBasedStoreApp",
        "applicationPermissions": [
            "TeamSettings.Read.Group",
            "ChannelMessage.Read.Group",
            "ChannelSettings.Read.Group",
            "Member.Read.Group",
            "Owner.Read.Group"
        ]
    },
    "validDomains": [
        "myappdomain"
    ]
}
```

**Comment by Gousia-MSFT** [comment] 2020-07-27 05:31
@timoleo23 Do you see any error message while installing the app? What changes did you make in the app permissions list? Could you please check if you are able to install it in any other test team?

**Comment by timoleo23** [comment] 2020-07-27 18:07
Hi Gousia - I made no changes to my app manifest or the list of RSC permissions.
I tried to install it on other Teams and it always fails with the same error message.
Is there a way to get a "verbose" version to get more details on this error ? It doesn't say a lot.
I can share the code of my app manifest if needed - I'm a MSFT here is my alias if you want to chat in person : aleki

**Comment by AkJo** [comment] 2020-07-30 07:50
@timoleo23 we have a change rolling out that should give a more verbose version of the error. In the meanwhile can you please try  load up the web client of MS Teams at https://teams.microsoft.com, press Ctrl+Shift+I to open the browser debugger, start network recording, and retry the installation flow that fails.  On failure, you would see one of the network calls fail. It should provide exact reason for failure as well as a request correlation id that we can use to follow up on our end.

**Comment by AkJo** [comment] 2020-07-30 07:50
You can also reach me at anandjo@microsoft.com

**Comment by Gousia-MSFT** [comment] 2020-08-21 06:42
FYI.. This is resolved internally. The cause of the issue was that RSC was disabled in the user's tenant.

**Closed by Gousia-MSFT** 2020-08-21 06:42 UTC
Labels: needs-author-feedback, teams-developer-support
