### ISSUE TITLE
Not able to click the button on MS Teams in Android devices

### ISSUE THREAD

**Issue by Shashank130700** [MicrosoftDocs/msteams-docs#10386] opened 2024-02-14 11:35 UTC
Hi Team,

The attached payload is working as expected in both the Microsoft Teams Web app and the iOS application, the message is correctly posted back and a response is received.
However, when the same button is clicked in the Teams Android app, nothing happens the first time. When clicked again, it appears that the message is posted back, however there's no response received.

The same message if typed works fine on all the platforms.

Android Product Name: Galaxy M52 5G
Current Android Version: M526BXX54CWL2/ M526BODMCWL2/ M526BXX54CWL1

Kindly refer to the attached payload for better understanding:
[simple_adaptive_card_payload.json](https://github.com/MicrosoftDocs/msteams-docs/files/14278848/simple_adaptive_card_payload.json)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55c5e4a1-6116-ec92-36e9-b94097bd83c7
* Version Independent ID: fd843eef-73e2-7a7e-9ac4-5c20fcf1fa2f
* Content: [Invoke and dismiss task modules - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules)
* Content Source: [msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/task-modules/invoking-task-modules.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment] 2024-02-14 12:38
Hi @Shashank130700 - Thanks for raising this issue. There is already an ICM raised for this, and engineering team is working on it. We will inform you once we have further update on the progress.


Thanks again!

**Comment by Shashank130700** [comment] 2024-02-16 05:55
Hi @Prasad-MSFT - Do we have any update on the raised issue?

**Comment by Prasad-MSFT** [comment] 2024-02-16 06:57
@Shashank130700 - Apologies. Currently there is no ETA to share. We are following up with engineering team about this issue. We will update this thread once we hear from them. Thanks!

**Comment by Prasad-MSFT** [comment] 2024-04-12 10:07
@Shashank130700 - The issue is fixed. We verified with below MS Teams version in Android device and it works fine. 
Please do verify.
![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/7bd10583-7f73-47be-a378-248b59ade5fd)

**Comment by Prasad-MSFT** [comment] 2024-04-15 14:46
We are closing this issue for now. Please feel free to reopen if required. Thanks!

**Closed by Prasad-MSFT** 2024-04-15 14:46 UTC
Labels: teams-developer-support, bug
