### ISSUE TITLE
Mistake in the message in french asking the user to log in in a messaging extension search command

### ISSUE THREAD

**Issue by jouhami** [MicrosoftDocs/msteams-docs#4651] opened 2021-11-18 15:11 UTC
In a search command if the user is not logged in the message in french asking him to log in is incorrect.

![image](https://user-images.githubusercontent.com/12663150/142440952-7e053b40-9785-4b42-96a3-dbdd0d2acbe7.png)

A correct message would be something like :  **Vous devez vous connecter pour utiliser cette application**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9549caa9-99a2-2568-19a5-f21a79292e2f
* Version Independent ID: f2100d03-b88a-34b2-44a2-935231e89db0
* Content: [Single sign-on support for bots - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/auth-aad-sso-bots)
* Content Source: [msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/bots/how-to/authentication/auth-aad-sso-bots.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Prasad-MSFT** [comment] 2021-11-19 06:55
@jouhami , Could you please provide more details or share repro steps on this?

**Comment by jouhami** [comment] 2021-11-19 09:20
Requirements : 

- A bot with SSO authentication enabled
- A Teams application with a messaging extension search command

Actions : 
 - Install the Teams application
 - From compose message area : clic on the applicaiton icon to run a search
 - If the user is not logged in you should see the message

**Comment by Prasad-MSFT** [comment] 2021-11-22 09:18
@jouhami , We have repro for this issue. We are checking this internally. We will get back to you real quick.
Thanks!

**Comment by Prasad-MSFT** [comment] 2021-11-26 09:41
@jouhami , We have raised a bug for this and Engineering Team is looking into it. We will inform you once we get any update. Thanks!

**Comment by Prasad-MSFT** [comment] 2022-01-18 05:47
@jouhami - The issue is resolved. So closing it. Please feel free to reopen if required.

**Closed by Prasad-MSFT** 2022-01-18 05:47 UTC
Labels: teams-developer-support, bug
