### ISSUE TITLE
Developer Portal - App validation fails because `defaultGroupCapability` has non valid properties names.

### ISSUE THREAD

**Issue by jouhami** [MicrosoftDocs/msteams-docs#4300] opened 2021-10-06 10:34 UTC
The validation of the app fails because `defaultGroupCapability` has capitalized names of properties of "defaultGroupCapability"

![image](https://user-images.githubusercontent.com/12663150/136186306-79cdf035-e217-4463-b5c1-1c0ffa36c025.png)

I fixed the issue by renaming (uncapitalizing) the properties names in the manifest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7da63b6f-15d7-a6dd-82fc-d183afaeb816
* Version Independent ID: 82d1ca83-28dd-220e-ab0c-a4833f8f8143
* Content: [Manage your apps with the Developer Portal - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal)
* Content Source: [msteams-platform/concepts/build-and-test/teams-developer-portal.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/build-and-test/teams-developer-portal.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **surbhigupta**

**Comment by Meghana-MSFT** [comment] 2021-10-14 12:38
Closing this issue as the issue has been resolved and the manifest schema has valid properties names for defaultGroupCapability.

**Comment by Meghana-MSFT** [comment] 2021-11-01 07:21
@martingjaldbaek - Could you please share your manifest so that it will help us to repro the issue?

**Comment by martingjaldbaek** [comment] 2021-11-01 10:53
@Meghana-MSFT Thanks for looking into it, here is my schema: (Pretty printed and IDs stripped - if you need the original, let me know and I can send privately)

```
{
   "$schema":"https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
   "version":"1.0.0",
   "manifestVersion":"1.11",
   "id":"ID_HERE",
   "packageName":"com.example.teams.app",
   "name":{
      "short":"Example",
      "full":""
   },
   "developer":{
      "name":"Acme Inc",
      "mpnId":"MPN_ID_HERE",
      "websiteUrl":"https://www.example.com/",
      "privacyUrl":"https://www.example.com/privacy",
      "termsOfUseUrl":"https://www.example.com/terms"
   },
   "description":{
      "short":"Short description",
      "full":"Full description"
   },
   "icons":{
      "outline":"outline.png",
      "color":"color.png"
   },
   "accentColor":"#029AC5",
   "staticTabs":[
      {
         "entityId":"conversations",
         "scopes":[
            "personal"
         ]
      },
      {
         "entityId":"about",
         "scopes":[
            "personal"
         ]
      }
   ],
   "bots":[
      {
         "botId":"BOT_ID_HERE",
         "scopes":[
            "team",
            "personal"
         ],
         "commandLists":[
            {
               "commands":[
                  {
                     "title":"MyCommand",
                     "description":"'MyCommand foo', 'MyCommand bar' or similar"
                  }
               ],
               "scopes":[
                  "personal"
               ]
            }
         ],
         "isNotificationOnly":false,
         "supportsFiles":false
      }
   ],
   "validDomains":[
      "*.example.com"
   ],
   "defaultInstallScope":"team",
   "defaultGroupCapability":{
      "Team":"bot",
      "Groupchat":"bot",
      "Meetings":"bot"
   }
}
```
I've been working with the hypothesis that the issue is the uppercase "Team", "Groupchat" and "Meetings" keys in defaultGroupCapability - since the [docs say they should be valid properties if they are lowercase](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#defaultgroupcapability). But like I mentioned, if I download the app package from Developer Portal and edit the keys to lowercase in the schema, then re-upload, I get the same 3 errors, and if I then download again, I can see that the properties have been changed back to uppercase.

**Comment by Meghana-MSFT** [comment] 2021-11-01 11:32
We are able to repro this issue. We are checking this internally.

**Comment by martingjaldbaek** [comment] 2021-11-01 11:37
Great, thank you for the quick update :)

**Comment by martingjaldbaek** [comment] 2021-11-05 16:34
Hey, is there any news regarding a fix for this? (also just pinging to to keep the issue from being auto-closed by the bot)

**Comment by Meghana-MSFT** [comment] 2021-11-09 06:55
@martingjaldbaek, @jouhami - We got an update from the engineering team that the developer portals doesn't support the defaultGroupCapability yet.

**Comment by v-chetsh** [comment] 2021-11-24 05:08
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed** 2021-11-24 08:08 UTC
Labels: teams-developer-support

**Comment by Meghana-MSFT** [comment] 2021-11-26 06:49
@martingjaldbaek, @jouhami - This issue has been fixed, We tested and it is working fine now.
