### ISSUE TITLE
Project Oakdale still mentioned

### ISSUE THREAD

**Issue by manuelap-msft** [MicrosoftDocs/msteams-docs#2751] opened 2021-02-05 12:15 UTC
This page still mentions Project Oakdale, which is no longer the name. It's now called Dataverse for Teams

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4461ec7-b1c7-9cd9-c2c9-a308e46182f7
* Version Independent ID: c7fbd95d-d337-35a3-ea7d-c22176a863b5
* Content: [Low code solutions for Teams custom apps - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/samples/teams-low-code-solutions)
* Content Source: [msteams-platform/samples/teams-low-code-solutions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/samples/teams-low-code-solutions.md)
* Product: **msteams**
* GitHub Login: @laujan
* Microsoft Alias: **lajanuar**

**Comment by Nikitha-MSFT** [comment] 2021-02-08 08:23
Thank you for bringing this issue to our attention. Tech writing team will update the document accordingly.

**Comment by Josverl** [comment] 2021-02-09 13:17
duplicate of #2753

**Closed** 2021-02-10 19:00 UTC
Labels: doc-enhancement, duplicate
