### ISSUE TITLE
Microsoft Teams Connectors giving 503 - Something went wrong :'(

### ISSUE THREAD

**Issue by apatils** [MicrosoftDocs/msteams-docs#1032] opened 2019-10-10 05:54 UTC
I am getting this error when I am trying to add new connector in Microsoft teams, also my pre-configured Incoming Webhooks are not working. 
<img width="594" alt="connector_issue" src="https://user-images.githubusercontent.com/41283108/66542562-8a32b200-eb50-11e9-859e-2a75c9922421.PNG">

**Comment by Gousia-MSFT** [comment] 2019-10-10 11:08
Duplicate of #1034

**Closed by Gousia-MSFT** 2019-10-10 11:08 UTC
