### ISSUE TITLE
Date Input selecting a date prior to the selected date on Adaptive Card Version 1.2

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#4355] opened 2021-10-11 17:42 UTC
Copied bug from: https://github.com/microsoft/AdaptiveCards/issues/6529 

**Details from original post:**
### Target Platforms

NodeJS

### SDK Version

1.2

### Application Name

MS Teams

### Problem Description

We found that recently, without any changes in our existing code, we see that now the date which is selected on the calender is one day ealier than the selected date.

Is there any issue already open on this. Attaching the details for reference.

On Button submission, the value received from the context ( context.activity.value.) comes a day earlier to the selected date.

Regards
Smitha

### Screenshots

<img width="351" alt="date issue" src="https://user-images.githubusercontent.com/64223805/136342677-a78210ef-97d9-49f1-b18a-37c4caa19fd0.PNG">
But value received is "2021-10-15"

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "body": [
        {
            "type": "Input.Date",
            "id": "date1"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.Submit",
                    "title": "Submit",
                    "data": {
                        "Action": "selectDate"
                    }
                }
            ]
        }
    ]
}
```

### Sample Code Language

Nodejs

### Sample Code

console.log(context.activity.value.date1);---
#### Document Details

⚠ *Do not edit this section.It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb4394d-25b1-8752-3996-fe3a2934732d
* Version Independent ID: 6d391381-89d0-117c-27cc-00043bd26a36
* Content: [Cards reference - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference)
* Content Source: [msteams-platform/task-modules-and-cards/cards/cards-reference.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/task-modules-and-cards/cards/cards-reference.md)
* Product: **msteams**
* GitHub Login: @surbhigupta12
* Microsoft Alias: **surbhigupta12**

**Comment by Meghana-MSFT** [comment] 2021-10-13 05:54
We are looking into the issue. We will update you.

**Comment by Meghana-MSFT** [comment] 2021-11-12 17:04
@astuj, @snandaku - This issue has been fixed. We have tested and it is working fine.

**Comment by schneika** [comment] 2021-12-08 15:10
When is Rollout of the Fix for General Availability? 
Not fixed in my Production Tenant...

**Comment by prasun113** [comment] 2021-12-08 18:19
still not fixed

**Comment by Meghana-MSFT** [comment] 2021-12-09 11:23
We have informed the engineering team and the team is working on it.

**Comment by nsarris** [comment] 2021-12-13 09:31
We checked this on the web app and tracked the calls to the server. This seems to be like a javascript timezone convertion bug. When the user's local timezone is UTC or earlier it works properly. When it's UTC+1 or greater the form submits the previous date. My guess is that the standalone date translates to a javascript Date object which is then converted to UTC and it's date part is submitted. This causes the utc offset to be subtraced from the original input date, which in turn takes it to the previous day if the offset is greated than zero. This is a very common type of bug when working with standalone dates in progamming languages that dont natively support plain dates like js or c#. Hope this helps.

**Comment by schneika** [comment] 2021-12-16 14:04
Is a fix from the Teams Service or for Teams App prospected?

**Comment by devfolorunso** [comment] 2022-01-04 11:42
Hi @Meghana-MSFT, is there any update on on this?

**Comment by Meghana-MSFT** [comment] 2022-01-04 12:28
Currently we do not have any update to share. We will let you know.

**Comment by Meghana-MSFT** [comment] 2022-01-07 12:41
This issue has been fixed. We have checked and its working fine.

**Comment by schneika** [comment] 2022-01-12 12:50
When do you deploy the fix to all Tenants? Not fixed in my Tenants yet...

**Comment by Meghana-MSFT** [comment] 2022-01-13 08:17
the fix has reached R4, so these issues should not be happening anymore. We checked in Teams version 1.4.00.35564 and its fixed. Could you please let us know your version?

**Comment by Meghana-MSFT** [comment] 2022-01-24 07:41
Could you please confirm if this is fixed at your end?

**Comment by schneika** [comment] 2022-01-25 14:17
The Issue is fixed on our sides...thanks!

**Comment by devfolorunso** [comment] 2022-01-26 08:20
@schneika, Did you upgrade your Teams version to 1.4.00.35564?
I'm asking so I can recommend a version upgrade to my Organization.

**Comment by bws10** [comment] 2022-01-26 08:51
It’s all fixed and working on our end too. 
We are on version 1.4.00.32771 (64 bit).

**Comment by Meghana-MSFT** [comment] 2022-01-27 13:39
Closing this issue. Please feel free to reopen this issue if you need any help.

**Closed by Meghana-MSFT** 2022-01-27 13:39 UTC
Labels: teams-developer-support, bug
