### ISSUE TITLE
Click card to show hide content tips:'Something went wrong. Please try again.'

### ISSUE THREAD

**Issue by KaratLee** [MicrosoftDocs/msteams-docs#7626] opened 2022-12-06 08:33 UTC
All these cards were issued a few months ago. Clicking to show and hide Microsoft prompts an error message, but the hidden content is still displayed. Note: All these cards were available before, but suddenly they are no longer available, we have not made any changes

**Comment by Meghana-MSFT** [comment] 2022-12-06 10:12
@KaratLee - We tried this at our end by sending the above JSON via bot and incoming webhook, and we do not see any error. It works fine. Attaching a video of the same.

https://user-images.githubusercontent.com/81138249/205882560-a9858bb0-92b4-4f4a-a1ff-eddd9dfc2b74.mp4

It is working fine on both desktop and web.

Can you please share any additional details that could help us in getting a repro locally? Are you seeing any console errors while clicking on participants/view meeting information.

**Comment by jeremy613** [comment] 2022-12-07 01:54
My customer encountered same issue from yesterday, and I could also reproduce in my lab, attached JSON file for your reference
[samplecard.txt](https://github.com/MicrosoftDocs/msteams-docs/files/10172072/samplecard.txt)

**Comment by joshatrezolveai** [comment] 2022-12-07 04:13
We're having the same issue across multiple cards.

**Comment by Meghana-MSFT** [comment] 2022-12-07 07:08
We tested this again today on Desktop client in personal scope. We are also able to repro this issue. We have raised a bug for the same. We will keep you posted on the updates.

**Comment by kaneg** [comment] 2022-12-09 05:52
We have met the similar issue which is related to 'Action.ToggleVisibility'.

**Comment by jonbagg** [comment] 2022-12-15 14:11
We've now also observed this issue in the Teams web app.  Previously we only saw the error message in the Teams desktop app.

Is there any update on if a fix is coming?  We are getting user complaints

**Comment by cedricske** [comment] 2022-12-15 22:01
Thank goodness I found this thread, I have been having the same issue on desktop, web, and mobile, the mobile issue went away when I switched version to 1.2

**Comment by Meghana-MSFT** [comment] 2022-12-16 11:51
Engineering team has pushed the fix. It would generally take a couple of weeks for the fix to be available publicly. Please be assured that we will update you once the fix is available publicly.

**Comment by AlexanderPBrown** [comment] 2022-12-21 16:18
We are having this same issue, and the project lead is DELAYING the release until it is fixed.  
This is HIGH PRIORITY.

**Comment by joshatrezolveai** [comment] 2022-12-21 19:21
I've been quiet as I know that it's being worked on - but we use this feature for over 200,000 customers. Please address as a high priority - echoing AlexanderPBrown.

**Comment by Meghana-MSFT** [comment] 2022-12-23 05:19
@AlexanderPBrown, @joshatrezolveai - The fix has been pushed already but it takes some time for the fix to be available publicly.

**Comment by surajmusmade** [comment] 2023-01-04 07:17
Hi @Meghana-MSFT, I am facing the same issue. Does the fix is published? or do you have any updates on this issue?

**Comment by Meghana-MSFT** [comment] 2023-01-04 08:02
@surajmusmade - The fix has not reached the public rings yet. Please be assured that we will update you once the fix is available publicly.

**Comment by adityarana420** [comment] 2023-01-09 13:06
@Meghana-MSFT How much more time will it take for the fix to get published?

**Comment by Meghana-MSFT** [comment] 2023-01-10 06:37
Engineering team has mentioned that as per latest updates the fix is expected to reach public rings by end of January.

**Comment by Meghana-MSFT** [comment] 2023-02-07 12:40
The issue is fixed, we have tested this issue in Desktop Teams Version 1.6.00.3071 (64-bit). It is working fine now.

**Closed** 2023-02-22 02:41 UTC
Labels: teams-developer-support, bug, needs-author-feedback
