### ISSUE TITLE
Teams App install on teams is not triggering any bot events.

### ISSUE THREAD

**Issue by coolanz** [MicrosoftDocs/msteams-docs#5713] opened 2022-04-12 08:18 UTC
Once we install a teams' app in a team, via graph API. (POST https://graph.microsoft.com/v1.0/teams/2395e2cd-3425-408d-930c-c6c4fcedcbe8/installedApps) we are not getting app installed event in the callback service.

onInstallationUpdateAdd is the one we are expecting, with channel id and service URL.

We used to get the event but now, the events are not triggered.

Bot Id : 6e2c4995-f170-4ba3-9a0b-aefd4c87dfa5

**Comment by Prasad-MSFT** [comment] 2022-04-12 08:50
We are checking the issue

**Comment by Prasad-MSFT** [comment] 2022-04-12 10:47
@coolanz - We tried to repro the issue by installing an app via Graph API to any team and we are able to get bot events being fired.

```
POST  https://graph.microsoft.com/v1.0/teams/{teamId}/installedApps

{
    "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/{externalId}"
}
```
```
{
    "action": "add",
    "type": "installationUpdate",
    "timestamp": "2022-04-12T10:32:51.011Z",
    "id": "f:a961ad7c-27ce-506d-a5e5-bfe69xxxxc4",
    "channelId": "msteams",
    "serviceUrl": "https://smba.trafficmanager.net/amer/",
    "from": {
        "id": "29:1GdHzmtVE_hN2wPrVQSb0fdMuI-HG8_kDOUXSNcf1pCKVxxxxxaAVUlNYy7BzXbQc1dg38oMTNnKOg",
        "aadObjectId": "4exxxx291b-4154-a85f-a89cd77aefa8"
    },
    "conversation": {
        "isGroup": true,
        "conversationType": "channel",
        "tenantId": "36a70xxxxxd-4d60-9de0-0a5f7b7693df",
        "id": "19:344e2bexxxxx4922167353e0a7778@thread.tacv2"
    },
    "recipient": {
        "id": "28:448ec8xxxxxf80-b5a1-cd3bdefd1f5b",
        "name": "xxxPSD"
    },
    "channelData": {
        "settings": {
            "selectedChannel": {
                "id": "19:344xxxxx44922167353e0a7778@thread.tacv2"
            }
        },
        "channel": {
            "id": "19:344e2bxxxxxxxxx67353e0a7778@thread.tacv2"
        },
        "team": {
            "aadGroupId": "2693xxxxxxxx2-ba50-4ec85e5b67c7",
            "name": "SOC Team",
            "id": "19:344xxxxxxx2167353e0a7778@thread.tacv2"
        },
        "tenant": {
            "id": "36a70xxxxxx-9de0-0a5f7b7693df"
        },
        "source": {
            "name": "message"
        }
    }
}
```

**Comment by Prasad-MSFT** [comment] 2022-04-12 12:41
@coolanz - We have also used the catalog app's generated app ID (different from the developer-provided ID in the [Microsoft Teams zip app package](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-package).

**Comment by coolanz** [comment] 2022-04-12 12:56
Alright, so why this bot is not receiving any installupdate event? @Prasad-MSFT

**Comment by Prasad-MSFT** [comment] 2022-04-12 12:59
Is the bot getting added successfully to the team?

**Comment by coolanz** [comment] 2022-04-12 13:34
Yes @Prasad-MSFT

**Comment by coolanz** [comment] 2022-04-12 14:08
@Prasad-MSFT But we are receiving user app installed and member removed events

**Comment by Prasad-MSFT** [comment] 2022-04-13 10:37
@coolanz - Ok, we are checking with engineering team what could be the root cause for this. We will get back to you once we get any update. Thanks!

**Comment by coolanz** [comment] 2022-04-19 05:06
Any updates @Prasad-MSFT ?

**Comment by Prasad-MSFT** [comment] 2022-04-19 06:58
@coolanz -Engineering team is looking into the issue. We will get back to you once we get any update. Thanks!

**Comment by tsrivishnu** [comment] 2022-04-23 10:01
@Prasad-MSFT We are facing the same issue with our Microsoft Teams app. We use Graph API to install the app into a Team and rely on the `installationUpdate` activity on the Bot's Botframework endpoint to fetch the channel (team) id and service URL. The events are sent if the app is manually installed into a Team. However, if the app is installed via GraphAPI, the events are not sent to the endpoint. 
I have this issue posted on Stackoverflow already and I'm not getting any useful responses: https://stackoverflow.com/questions/71943420/not-receiving-botframework-installationupdate-when-app-is-added-via-graphapi/

We noticed that this is broken after we have submitted our app for verification via the Partner centre. From around 2022-04-12.  In fact, when the Verification team performed the testing, we notice that the events have worked. Our app didn't pass the verification for different technical reasons which we have now addressed. However, ever since the validation team responded saying that the validation has failed, we notice that the installation events are being sent to the endpoint for this app. 

We have other apps that are not submitted for verification and their events work completely fine. So, I'm assuming that this has to do something with the verification process.

I hope this helps debug this a little more.

Ever since we submitted the app for validation, we are unable to serve our new customers. Even worse, we can't resubmit the app for validation because this flow is not broken. We are stick in a limbo state now. 

@coolanz Did your app also go through a verification process by Microsoft before you started facing this issue?

**Comment by yong-sea** [comment] 2022-04-23 14:22
get out!
dont steal my email anymore!
________________________________
发件人: Sri Vishnu Totakura ***@***.***>
发送时间: 2022年4月23日 10:01
收件人: MicrosoftDocs/msteams-docs ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [MicrosoftDocs/msteams-docs] Teams App install on teams is not triggering any bot events. (Issue #5713)


@Prasad-MSFT<https://github.com/Prasad-MSFT> We are facing the same issue with our Microsoft Teams app. We use Graph API to install the app into a Team and rely on the installationUpdate activity on the Bot's Botframework endpoint to fetch the channel (team) id and service URL. The events are sent if the app is manually installed into a Team. However, if the app is installed via GraphAPI, the events are not sent to the endpoint.
I have this issue posted on Stackoverflow already and I'm not getting any useful responses: https://stackoverflow.com/questions/71943420/not-receiving-botframework-installationupdate-when-app-is-added-via-graphapi/

We noticed that this is broken after we have submitted our app for verification via the Partner centre. From around 2022-04-12. In fact, when the Verification team performed the testing, we notice that the events have worked. Our app didn't pass the verification for different technical reasons which we have now addressed. However, ever since the validation team responded saying that the validation has failed, we notice that the installation events are being sent to the endpoint for this app.

We have other apps that are not submitted for verification and their events work completely fine. So, I'm assuming that this has to do something with the verification process.

I hope this helps debug this a little more.

Ever since we submitted the app for validation, we are unable to serve our new customers. Even worse, we can't resubmit the app for validation because this flow is not broken. We are stick in a limbo state now.

@coolanz<https://github.com/coolanz> Did your app also go through a verification process by Microsoft before you started facing this issue?

―

**Comment by coolanz** [comment] 2022-04-24 16:02
No @tsrivishnu, we haven't submitted the app for verification. But the issue started somewhere around the same timeframe as yours.

**Comment by Prasad-MSFT** [comment] 2022-04-27 15:11
@tsrivishnu - There is an issue raised for this and engineering team is investigating it. We will inform you once we get any further update. Thanks!

**Comment by tsrivishnu** [comment] 2022-05-09 13:43
@Prasad-MSFT Any updates?

**Comment by Prasad-MSFT** [comment] 2022-05-09 13:49
The fix is in internal stage. The fix will be deployed to production in one to two weeks. We will update you once its done.
Thanks for understanding!

**Comment by tsrivishnu** [comment] 2022-05-23 14:40
@Prasad-MSFT hi, are there any updates on the deployment?

**Comment by Prasad-MSFT** [comment] 2022-05-24 04:53
@tsrivishnu - We got info from engineering team that this issue is fixed. Please do verify

**Closed** 2022-05-25 11:19 UTC
Labels: teams-developer-support

**Comment by tsrivishnu** [comment] 2022-05-26 14:24
I can confirm that this is fixed and is working for our own tenant and our developer tenant. I will need sometime to verify if this is working for our customers’ tenant. I will post an update if I have any. Thank you.

**Comment by coolanz** [comment] 2022-06-02 06:59
The fix works!
