### ISSUE TITLE
Error code 404 "V3 agent not found."

### ISSUE THREAD

**Issue by Leks12lk** [MicrosoftDocs/msteams-docs#838] opened 2019-07-26 14:55 UTC
I have a messaging extension (compose extension) app and a bot app. Both of them have the same Azure Bot Channels Registration resource (the value of botId in manifest.json is the same).

Messaging extension returns an adaptive card which contains the button with "Action.Submit" type. The request to the bot should be sent after clicking on that button. But instead of request to the bot I got the error with the **code 404 and the message "V3 agent not found."**
The issue is reproduced for both team chat and personal chat.

Also please note that this issue is reproduced only when triggering Action.Submit from a card returned by ME app. If Bot returns the card this issue is not reproduced and request is sent to the bot successfully.

**Comment by Wajeed-msft** [comment] 2019-07-29 13:13
We are looking into this issue.

**Comment by tdwhite0** [comment] 2019-07-31 13:06
I'm seeing this too. Looks like it has something undefined when constructing the url to invoke:
![image](https://user-images.githubusercontent.com/2566323/62214154-77427b00-b372-11e9-966d-2f9a6f2d0cb7.png)

**Comment by Leks12lk** [comment] 2019-08-02 10:32
> I'm seeing this too. Looks like it has something undefined when constructing the url to invoke:
> ![image](https://user-images.githubusercontent.com/2566323/62214154-77427b00-b372-11e9-966d-2f9a6f2d0cb7.png)

Actually I don't have undefined in this url but this issue is still reproduced.

**Comment by tdwhite0** [comment] 2019-08-02 15:12
@Leks12lk This issue basically prevents my whole app from working, have you found any workarounds?

**Comment by Leks12lk** [comment] 2019-08-05 08:24
@tdwhite0  actually I haven't found any workarounds yet.

**Comment by VKAlwaysWin** [comment] 2019-08-06 10:10
FYI, I also seeing this issue. When trying to click on card from ME:

![image](https://user-images.githubusercontent.com/14337164/62531499-40c1a000-b84b-11e9-9de2-cbeba553969f.png)

But when using same card from Bot. I see:
![image](https://user-images.githubusercontent.com/14337164/62531675-8bdbb300-b84b-11e9-87e9-e7d731343489.png)

**Comment by Leks12lk** [comment] 2019-08-07 12:03
@Wajeed-msft did you have a chance to look into this issue? Are there any updates?

**Comment by Wajeed-msft** [comment] 2019-08-07 12:08
We are able to repro this. I'll update this post as soon as I have updates.

**Comment by Gousia-MSFT** [comment] 2019-09-04 04:47
This has been fixed now. Please try out and re-open if you still face any issues.

**Closed by Gousia-MSFT** 2019-09-04 04:47 UTC
Labels: bug, teams-developer-support

**Comment by VKAlwaysWin** [comment] 2019-09-05 08:34
@Gousia-MSFT I can confirm that it is working fine for me. Thank you for all your help.

**Comment by Leks12lk** [comment] 2019-09-06 15:02
Hi @Gousia-MSFT it works for me as well. Thanks.
