### ISSUE TITLE
Personal tab with SharePoint URL not working on IOS

### ISSUE THREAD

**Issue by sortegamartin** [MicrosoftDocs/msteams-docs#4110] opened 2021-09-07 12:21 UTC
I have a Teams application that has the url of a SharePoint site configured as a personal tab. This tab works fine on web, desktop and android, but it doesn't work in the Teams app on the iPhone.

The configuration of the application manifest is as follows:

Manifest version:

`  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
  "manifestVersion": "1.8",`

Personal tab:

`"staticTabs": [
{
      "entityId": "tab1",
      "name": "Home",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/sites/community",
      "scopes": ["personal"]
  }
]`

This same configuration, before if it worked on iPhone, could it be a bug in the latest versions of the Teams app for iPhone?

Thanks!

**Comment by Prasad-MSFT** [comment] 2021-09-09 12:00
Hi @sortegamartin ,
Could you please try adding following in your App Manifest as workaround and let us know if you are facing any issue?
```
"staticTabs": [
    {
      "entityId": "tab1",
      "name": "Home",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/sites/community",
      "scopes": ["personal"],
      "websiteUrl": "https://{teamSiteDomain}/sites/community"
    }
  ],
  "validDomains": [
    "*.login.microsoftonline.com",
    "microsoft.sharepoint.com",
    "microsoft.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com"
  ],
  "webApplicationInfo": {
    "resource": "https://microsoft.sharepoint.com",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }
```

**Comment by sortegamartin** [comment] 2021-09-10 09:31
Hi @Prasad-MSFT, 
I have tried with the configuration of the manifest that you tell me, but it does not work either. On web, desktop and android it does work, it only doesn't work for iPhone

**Comment by oyvindam** [comment] 2021-09-10 12:10
+1 on this error. 
Not a personal tab in our case, but Team tabs (_configurableTabs_). 
Apps have been working fine for months until now.
Teams-client stopped loading the apps after users updated the Teams app on iOS to build 3.14.77.2021143601/0831 (general).
Works fine in browser (teams.microsoft.com), desktop clients and on Android.

**Comment by Prasad-MSFT** [comment] 2021-09-14 07:14
Hi @sortegamartin , We are not able to reproduce the issue at our end. Everything is working fine. Could you please share the manifest and the demo creds, so that we will be able to repro? 
_Mail Id:_ microsoftteamsdev@microsoft.com, v-prdas2@microsoft.com

**Comment by harshdamaniahd** [comment] 2021-09-14 12:56
I have found a solution to make it work for now. Same issue is raised on reddit forum has well https://www.reddit.com/r/MicrosoftTeams/comments/pmvg91/spfx_teams_personal_app_ios_issue/

add the webpart on a sharepoint page first, then in manifest do the following 
![image](https://user-images.githubusercontent.com/11780473/133261245-10a70e07-9050-4ce9-8994-b907ad3cc016.png)

![image](https://user-images.githubusercontent.com/11780473/133261297-f75f3446-c521-4fb6-b889-467ecce89ef0.png)

**Comment by harshdamaniahd** [comment] 2021-09-14 12:59
> +1 on this error.
> Not a personal tab in our case, but Team tabs (_configurableTabs_) deployed using SPFx (SharePoint Framework).
> Apps have been working fine for months until now.
> Teams-client stopped loading the apps after users updated the Teams app on iOS to build 3.14.77.2021143601/0831 (general).
> Works fine in browser (teams.microsoft.com), desktop clients and on Android.

We are facing issue for same in personal app. I have tested in 4 enviornment and same issue

**Comment by Prasad-MSFT** [comment] 2021-09-23 06:25
@harshdamaniahd @oyvindam ,
We had raised this issue with concerned team and according to the feedback, the issue is fixed now and fix will start rolling out to all users real soon mostly by end of this month.
Thanks!

**Comment by Prasad-MSFT** [comment] 2021-09-28 08:15
We are closing this issue for now. Please feel free to re-open if needed.

**Closed by Prasad-MSFT** 2021-09-28 08:15 UTC
