### ISSUE TITLE
[Teams SDK - Context] The tenantSKU prop is null inside a mobile environment, should return a string

### ISSUE THREAD

**Issue by Wajeed-msft** [MicrosoftDocs/msteams-docs#3809] opened 2021-07-13 05:11 UTC
Copied issue from: [teams-sdk-context-the-tenantsku-prop-is-null](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/43780587--teams-sdk-context-the-tenantsku-prop-is-null-i)

Posted by: @StefanoA1

 I was using microsoft teams' sdk (js) to get a Context inside my app, and specifically the tenantSKU prop ( as seen in -> https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.context?view=msteams-client-js-latest#tenantSKU) happens to be null Only when I test the app in a mobile environment, for other envs it is ok.
Tested on an Android device (Samsung S20+, latest OS version available)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dfa1a29-bcf4-0cc5-ae3a-b185a00fd7bc
* Version Independent ID: c68181e1-151b-fc78-2671-fe9b397b702e
* Content: [Get context for your tab - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context)
* Content Source: [msteams-platform/tabs/how-to/access-teams-context.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/access-teams-context.md)
* Product: **msteams**
* GitHub Login: @surbhigupta
* Microsoft Alias: **lajanuar**

**Comment by Wajeed-msft** [comment] 2021-07-13 05:12
@StefanoA1 - FYI - Tracking your issue here.

**Comment by HunaidHanfee-MSFT** [comment] 2021-07-13 17:39
@StefanoA1 - I have tried doing same and I am able to get the tenantSKU. 
Can you please share the repro steps? 

Please confirm : 
1. Version of Microsoft Teams' SDK?
2. How are you referencing it? via NPM or CDN or copied locally?

Thanks

**Comment by HunaidHanfee-MSFT** [comment] 2021-07-19 05:04
Let us know if you are still facing this issue.

**Comment by StefanoA1** [comment] 2021-07-19 09:14
> @StefanoA1 - I have tried doing same and I am able to get the tenantSKU.
> Can you please share the repro steps?
> 
> Please confirm :
> 
> 1. Version of Microsoft Teams' SDK?
> 2. How are you referencing it? via NPM or CDN or copied locally?
> 
> Thanks

Hello @HunaidHanfee-MSFT @Wajeed-msft sorry, I was off-office, just read the notifications, I'm referencing using NPM, as for the version I'm using 1.8.0 
`"@microsoft/teams-js": "^1.8.0",`
And I'm accessing the property from the context just as I access any other property from the sdk context (I get the other props, it's just the SKU one I don't get on mobile)

**Comment by HunaidHanfee-MSFT** [comment] 2021-07-19 10:06
Hey,
Can you please try updating "_@microsoft/teams-js_" to "1.10.0" and see if you are still having the issue? 
Are you facing this on android or iOS?
Also you can try re-login from mobile sometimes it helps.

Thanks

**Comment by StefanoA1** [comment] 2021-07-19 13:16
> Hey,
> Can you please try updating "_@microsoft/teams-js_" to "1.10.0" and see if you are still having the issue?
> Are you facing this on android or iOS?
> Also you can try re-login from mobile sometimes it helps.
> 
> Thanks

Thanks for your response, I've updated it to "1.10.0" and now I get `unknown` which _this time_ is mentioned as a possible output for the prop in the docs but still doesn't address the lack of a SKU context in the mobile environment.

**Comment by HunaidHanfee-MSFT** [comment] 2021-07-20 00:15
Hey, 
What is your current SKU? It seems like for other than enterprise, free, edu it come as unknown.

Thanks

**Comment by StefanoA1** [comment] 2021-07-20 07:44
On teams desktop version and on web version it is enterprise, on teams (mobile app) it becomes unknown

**Comment by HunaidHanfee-MSFT** [comment] 2021-07-20 10:55
Hello,
We have tested on Teams Mobile client v1416/1.0.0.2021093701 and Android v10.

Thanks

**Comment by StefanoA1** [comment] 2021-07-21 08:20
Teams Mobile client v1416/1.0.0.2021083801/0624 & Android v11, I'll try with the latest mobile client version you specify to see if I get a different result.
Thanks

**Comment by StefanoA1** [comment] 2021-07-23 08:19
You can close the issue, the problem is solved with the latest version

**Comment by StefanoA1** [comment] 2021-07-23 08:22
Although I'd recommend that the value unknown is set as a string "unknown" or indicate that the unknown value isn't a string but the primitive unknown type in the docs (for parsing purposes)

**Comment by HunaidHanfee-MSFT** [comment] 2021-07-29 17:10
Hey, 
Please try out this app at your end(Attaching a manifest). Let me know if you can see the tenant SKU with this one.
[TestTenant.zip](https://github.com/MicrosoftDocs/msteams-docs/files/6902231/TestTenant.zip)
This is a simple tab : 
![image](https://user-images.githubusercontent.com/64194049/127534323-58e4062d-deda-49ab-8b3e-ea67a04c5e9e.png)

> No free account can't get the unknown value?

 I need to confirm with team when exactly unknown come.
Thanks

**Comment by HunaidHanfee-MSFT** [comment] 2021-08-02 08:44
Hello @StefanoA1,
Did you get a chance to install and check the manifest I shared?
Thanks

**Comment by StefanoA1** [comment] 2021-08-02 09:21
Hello @HunaidHanfee-MSFT thanks for the info, I'm going to test it today/tomorrow

**Comment by StefanoA1** [comment] 2021-08-04 09:20
Hello @HunaidHanfee-MSFT , I tested the manifest and I get unknown for the tenantSKU, were you able to confirm if the unknown value never shows in any case for a free account? I'm backing on that info to address a publication requirement of the TeamsStore validation team, which is to give a meaningful error message in case a free teams account tries to access the app (an error will still be thrown if I can't identify the user as a free one but it will be less precise)

**Comment by HunaidHanfee-MSFT** [comment] 2021-08-12 10:55
Hello,
I confirmed, For free users SKU value would be _free_.
Thanks

**Closed by HunaidHanfee-MSFT** 2021-08-12 10:55 UTC
Labels: teams-developer-support, needs-triage :mag:
