### ISSUE TITLE
Url in Text sent with Adaptive Card Carousel not clickable

### ISSUE THREAD

**Issue by JordyGit** [MicrosoftDocs/msteams-docs#4582] opened 2021-11-15 06:42 UTC
Next to #4539 we have also found that URL's in the Text sent with an adaptive card carousel are rendered but not clickable on the Teams Desktop client.

It renders like a URL and seems to be clickable but it is not (it is working fine on Android, IOS the text doesn’t appear (original issue) so not possible to check this yet). When clicking on the URL nothing happens.

Any url like this in the text field if also sending a adaptive card carousel:
`[url text](https://google.com)`

As a temporary workaround we’ve just changed to send two messages at once, first the text, then the carousel adaptive card. That way it works fine on all clients (text visible and url clickable).

**Comment by Meghana-MSFT** [comment] 2021-11-15 10:30
@JordyGit - We are able to repro this issue.

**Comment by Meghana-MSFT** [comment] 2021-11-15 12:59
We have raised a bug and the concerned team is looking into it.

**Comment by robin-liao** [comment] 2021-11-15 19:26
@JordyGit can you share card payload? I use my own bot to test a simple carousel of 2 adaptive cards containing `[url text](https://google.com)` as `TextBlock`, but I can not repro this issue.

**Comment by JordyGit** [comment] 2021-11-15 19:32
Hi, the card payload doesn’t make any difference. It’s the text put in the activity next to the attachments. 

Activity contains:
-> Text
-> Attachments
-> …

The attachment is the carousel of adaptive cards which works perfectly. But the text displayed above the carousel (not displayed on IOS, that is the other tagged issue) displays the URL, but it is not clickable.

Is this explanation more clear?

**Comment by robin-liao** [comment] 2021-11-18 10:15
@JordyGit This is the payload I tested and it works perfect for me (as below). Can you share yours? 

```
{
  "attachmentLayout": "carousel",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "body": [
          {
            "type": "TextBlock",
            "text": "[url text](https://google.com)"
          }
        ]
      }
    },
    {
      "contentType": "application/vnd.microsoft.card.adaptive",
      "content": {
        "body": [
          {
            "type": "TextBlock",
            "text": "[url text](https://google.com)"
          }
        ]
      }
    }
  ]
}
```

**Comment by JordyGit** [comment] 2021-11-18 10:45
Yes because that Text is in the adaptive card. I am trying to tell you the text should be next to (above) the attachments. 

See in the next example a message json I copied from the Bot Emulator which includes the text and attachement.
The Text contains the url, the content of the carousel attachment doesn't matter, the Url is never clickable.

`{
    "type": "message",
    "serviceUrl": "https://9e7a-194-78-124-243.ngrok.io",
    "channelId": "emulator",
    "from": {
        "id": "b6c63a20-406d-11ec-815d-ad41c66a9f38",
        "name": "Bot",
        "role": "bot"
    },
    "conversation": {
        "id": "a64eb4f0-415e-11ec-815d-ad41c66a9f38|livechat"
    },
    "recipient": {
        "id": "d8584435-23d4-4c41-acfb-c29a45d49fcd",
        "role": "user"
    },
    "attachmentLayout": "carousel",
    "locale": "en-US",
    "text": "I've listed the first 10 found elements below. Try to be more specific or view all your elements with [Remote Access](https://escape-bot.local.dataminer.services:3001/monitoring/view/-1/elements).",
    "inputHint": "acceptingInput",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "size": "Medium",
                        "weight": "Bolder",
                        "text": "Element AMS_IRD02"
                    },
                    {
                        "type": "TextBlock",
                        "spacing": "None",
                        "text": "The element is Active.",
                        "isSubtle": true,
                        "wrap": true
                    },
                    {
                        "type": "FactSet",
                        "facts": [
                            {
                                "title": "Alarm Level:",
                                "value": "Major"
                            },
                            {
                                "title": "Alarms:",
                                "value": "1"
                            }
                        ]
                    }
                ],
                "actions": [
                    {
                        "type": "Action.OpenUrl",
                        "title": "Open",
                        "url": "https://escape-bot.local.dataminer.services:3001/monitoring/element/3/1"
                    },
                    {
                        "type": "Action.Submit",
                        "title": "Alarms",
                        "data": {
                            "CustomActionId": "GetAlarmsForElementId",
                            "ElementId": "1",
                            "DataMinerId": "3",
                            "ElementName": "AMS_IRD02"
                        }
                    }
                ],
                "msteams": {
                    "width": "Full"
                },
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.2"
            }
        },
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "type": "AdaptiveCard",
                "body": [
                    {
                        "type": "TextBlock",
                        "size": "Medium",
                        "weight": "Bolder",
                        "text": "Element TOR-6 Uplink Power Control"
                    },
                    {
                        "type": "TextBlock",
                        "spacing": "None",
                        "text": "The element is Paused.",
                        "isSubtle": true,
                        "wrap": true
                    },
                    {
                        "type": "FactSet",
                        "facts": [
                            {
                                "title": "Alarm Level:",
                                "value": "Normal"
                            },
                            {
                                "title": "Alarms:",
                                "value": "10"
                            }
                        ]
                    }
                ],
                "actions": [
                    {
                        "type": "Action.OpenUrl",
                        "title": "Open",
                        "url": "https://escape-bot.local.dataminer.services:3001/monitoring/element/3/10"
                    },
                    {
                        "type": "Action.Submit",
                        "title": "Alarms",
                        "data": {
                            "CustomActionId": "GetAlarmsForElementId",
                            "ElementId": "10",
                            "DataMinerId": "3",
                            "ElementName": "TOR-6 Uplink Power Control"
                        }
                    }
                ],
                "msteams": {
                    "width": "Full"
                },
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "version": "1.2"
            }
        }
    ],
    "entities": [],
    "replyToId": "d0cb0f70-415f-11ec-9ca9-67404865d900",
    "id": "d40a5bf0-415f-11ec-9ca9-67404865d900",
    "localTimestamp": "2021-11-09T14:20:37+01:00",
    "timestamp": "2021-11-09T13:20:37.679Z"
}`

**Comment by JordyGit** [comment] 2021-12-21 12:05
@robin-liao Do you understand the example/issue?

**Comment by Prasad-MSFT** [comment] 2021-12-23 12:01
@JordyGit - The issue is currently fixed and merged. We will update you once it gets rolled out publicly. Thanks!

**Comment by Prasad-MSFT** [comment] 2022-01-18 07:08
@JordyGit - We checked the issue in `Microsoft Teams Version 1.4.00.35564 (64-bit). It was last updated on 07-01-2022` and it seems to be fixed. Please do verify by updating your Microsoft Teams desktop version.

**Closed by Prasad-MSFT** 2022-01-18 07:08 UTC
Labels: teams-developer-support, bug

**Comment by JordyGit** [comment] 2022-01-18 07:19
As long as issue https://github.com/MicrosoftDocs/msteams-docs/issues/4539 is not fixed, we won't remove the workaround in our app/bot. Only then we'll check if this all got resolved.
