### ISSUE TITLE
Issue with full width rendering in MS Teams Group Channel with Adaptive cards

### ISSUE THREAD

**Issue by srikanth2042** [MicrosoftDocs/msteams-docs#7468] opened 2022-11-17 12:15 UTC
Since from couple of days, though the `width: full` property is set, the Adaptive Cards rendered are not fully occupying width. Can someone please look into this issue? They previously used to occupy full width btw.
```
{
   "type": "AdaptiveCard", 
   "$schema": "http://adaptivecards.io/schemas/adaptive-card.json", 
    "version": "1.3", 
    "msTeams": {
         "width": "full"
    }
    .....
```
Rendered card in MS Teams App:
![image](https://user-images.githubusercontent.com/33093586/202443419-cd809be2-c75b-4ba4-a48e-4ddff085e53d.png)

**Comment by Nivedipa-MSFT** [comment] 2022-11-17 12:48
@srikanth2042 - We have tested this using below card and its working fine at our end.
I have send both card with full width and without width property.
![image](https://user-images.githubusercontent.com/92150070/202450399-9ab65ca0-7b4c-404c-8282-85ece996eee6.png)




Its showing correctly at your end also. Please refer below document and check width of cards in document.
https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#full-width-adaptive-card

**Comment by srikanth2042** [comment] 2022-11-21 13:16
@Nivedipa-MSFT it looks fine 1-1 chat but if the same card is posted in a group channel, it looks weird. Please take look at the following screenshot:
![image](https://user-images.githubusercontent.com/33093586/203064097-b38e044f-a269-40d9-9fee-652d4bb7e896.png)
I had to hide some sensitive info of my organization and also card is wrapped with the following border:
```
<div style="margin-top:-40px; background-color:red;"><attachment id="{content}"></attachment></div>
```

**Comment by Nivedipa-MSFT** [comment] 2022-11-22 12:30
@srikanth2042  - We will test this in group channel and update you soon.

**Comment by srikanth2042** [comment] 2022-11-23 11:41
@Nivedipa-MSFT I don't know if the issue has something to do with the way we post the card, I used the same adaptive body which you have mentioned  here https://github.com/MicrosoftDocs/msteams-docs/issues/7468#issuecomment-1323606087

[Graph API](https://learn.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=http) we are using with POST call:
```
https://graph.microsoft.com/v1.0/teams/{team_id}/channels/{channel_id}/messages
```
Post body:
```
{
	"body": {
		"contentType": "html",
		"content": "<div style=\"margin-top:-40px;\"><attachment id=\"c2c2e0e3-6d39-46c0-9f73-b2ec8b521df2\"></attachment></div>"
	},
	"attachments": [
		{
			"id": "c2c2e0e3-6d39-46c0-9f73-b2ec8b521df2",
			"contentType": "application/vnd.microsoft.card.adaptive",
			"content": "{\"$schema\":\"http://adaptivecards.io/schemas/adaptive-card.json\",\"type\":\"AdaptiveCard\",\"version\":\"1.3\",\"msTeams\":{\"width\":\"full\"},\"body\":[{\"type\":\"TextBlock\",\"wrap\":true,\"text\":\"Cardscanhaveactionsetsinthemiddleoftheirbody.\"},{\"type\":\"ActionSet\",\"actions\":[{\"type\":\"Action.ShowCard\",\"title\":\"ShowCard\",\"card\":{\"type\":\"AdaptiveCard\",\"body\":[{\"type\":\"TextBlock\",\"text\":\"Thisisashowcard\"}]}},{\"type\":\"Action.OpenUrl\",\"title\":\"OpenUrl\",\"url\":\"https://adaptivecards.io\"}]},{\"type\":\"TextBlock\",\"wrap\":true,\"text\":\"Therearealsostill\\\"actions\\\"atthebottomofthecard\"}],\"actions\":[{\"type\":\"Action.ShowCard\",\"title\":\"ShowCard\",\"card\":{\"type\":\"AdaptiveCard\",\"body\":[{\"type\":\"TextBlock\",\"text\":\"Thisisashowcard\"}]}},{\"type\":\"Action.OpenUrl\",\"title\":\"OpenUrl\",\"url\":\"https://adaptivecards.io\"}]}"
		}
	]
}
```

Rendered card(I have tested it as the main card as well as a reply card):
![image](https://user-images.githubusercontent.com/33093586/203536804-f9d4240a-59b7-4dc7-bd13-a9981872140c.png)

**Comment by Nivedipa-MSFT** [comment] 2022-11-23 12:06
@srikanth2042 - We have tested this using graph API and from graph API also we are getting full width card.
![image](https://user-images.githubusercontent.com/92150070/203542532-8d19b453-2e94-4137-8112-de994f499f5e.png)


![image](https://user-images.githubusercontent.com/92150070/203542633-983b826a-8c80-4e80-a2c9-2608c12e941b.png)

Are you testing this in public version of Teams?

**Comment by srikanth2042** [comment] 2022-11-23 13:07
@Nivedipa-MSFT Nope, I am using Teams client issued by my organization with a windows laptop. It's running on:
```
You have Microsoft Teams Version 1.5.00.32083 (64-bit). It was last updated on 11/18/2022.
```
I think the issue started from the last update on Nov 18th.

**Comment by Nivedipa-MSFT** [comment] 2022-11-24 06:29
@srikanth2042 - Could you please share your Teams client version. Click on 3 dots on right corner of Teams and then click on version like below:
![image](https://user-images.githubusercontent.com/92150070/203710031-fc8c7267-61fb-4bb2-87fd-75c240764bfe.png)

**Comment by srikanth2042** [comment] 2022-11-24 06:41
@Nivedipa-MSFT here is the info:
![image](https://user-images.githubusercontent.com/33093586/203711752-9c710ab3-4037-46cc-91f2-740242393768.png)

Result:
![image](https://user-images.githubusercontent.com/33093586/203711928-6d88ccf8-3c8c-4657-93e0-8a9734f5e6f8.png)

**Comment by Nivedipa-MSFT** [comment] 2022-11-24 08:34
@srikanth2042 - Could you please switch Teams to public preview and test this again? Please let us know if you are facing any further issue. thanks.

**Comment by srikanth2042** [comment] 2022-11-24 12:31
@Nivedipa-MSFT its the same issue even if I switch to Public Preview: (I tried restarting Teams client as well)
![image](https://user-images.githubusercontent.com/33093586/203784686-ca484c8f-1ecb-4f5b-a879-dbd03be3d572.png)

![image](https://user-images.githubusercontent.com/33093586/203784846-ac91dccc-a68b-4a4f-9929-40642575a135.png)

**Comment by Nivedipa-MSFT** [comment] 2022-11-29 12:22
@srikanth2042 - We are not able to repro your issue. We are checking this with engineering team. We will let you know the updates.

**Comment by srikanth2042** [comment] 2022-12-01 15:09
Any update on this @Nivedipa-MSFT @Wajeed-msft?

**Comment by Nivedipa-MSFT** [comment] 2022-12-01 15:15
@srikanth2042 - Apologies for the delay. We are still checking this with engineering team. We will let you know once we get any updates from them.

**Comment by srikanth2042** [comment] 2022-12-22 10:27
Checking if there is any update here, the adaptive cards we posting are still being affected by this issue. @Wajeed-msft @Nivedipa-MSFT

**Comment by Nivedipa-MSFT** [comment] 2023-01-04 12:27
@srikanth2042 - Apologies for the delay response. We are still checking this with engineering team for card which we send via graph API. We will inform you once we get any updates from them.

We are able to repro when the card was sent by incoming webhook connector. We have already raised a bug for the same. We will inform you once we get any updates on the bug.

**Comment by beanaroo** [comment] 2023-01-08 17:47
We can confirm the same behaviour when using the `/activities` Bot API.

Comparison below as rendered on the latest MacOS desktop client:

![image](https://user-images.githubusercontent.com/1748909/211211060-67b72508-82fe-4b3f-867f-0fd4f9320bbd.png)

**Comment by ChetanSharma-msft** [comment] 2023-01-16 08:26
Hello Everyone,
We are actively checking the updates with engineering team and will inform you once we get any update.

**Comment by srikanth2042** [comment] 2023-04-06 14:14
Confirming that the fix mentioned [here](https://github.com/MicrosoftDocs/msteams-docs/issues/7638#issuecomment-1473697497) is rolled in our organization tenant, this issue is solved now for us. But its concerning that it took 6 months to release a fix for a simple issue.

**Comment by Prasad-MSFT** [comment] 2023-05-24 07:21
The issue is fixed now. Tested in MS Teams Desktop `(Microsoft Teams Version 1.6.00.13566)` and Web version in channel scope.

![image](https://github.com/MicrosoftDocs/msteams-docs/assets/62237649/f2c3a554-cde9-4875-9bec-ba42e90fc622)

**Comment by Nivedipa-MSFT** [comment] 2023-05-24 07:51
We are closing this issue for now, Please feel free to reopen it, if required.

**Closed by Nivedipa-MSFT** 2023-05-24 07:51 UTC
Labels: teams-developer-support, bug, needs-attention
