### ISSUE TITLE
Search Query Invoke Task Module

### ISSUE THREAD

**Issue by 01** [MicrosoftDocs/msteams-docs#580] opened 2019-04-20 20:05 UTC
Is it possible when user chooses a result from the list to have it invoke a task module instead of creating a card and putting it in the message box? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ff3777-49c4-8cdc-089e-8612a8774ffb
* Version Independent ID: 0d927000-0b55-2129-cbbb-6630c1ec481e
* Content: [Search with messaging extensions - Teams](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/messaging-extensions/search-extensions)
* Content Source: [msteams-platform/concepts/messaging-extensions/search-extensions.md](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/concepts/messaging-extensions/search-extensions.md)
* Product: **msteams**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by 01** [comment] 2019-04-20 22:20
Found the answer, to anyone else wondering you need to add a tap Card Action to the preview card

**Comment by 01** [comment] 2019-04-22 20:14
So For the life of me I dont understand why componseExtension/selectItem can only return a type result. I am trying to have a messaging extension that does a search and on on tap opens up a task module. Is there any work around for this?

**Comment by Gousia-MSFT** [comment] 2019-05-02 12:17
duplicate of https://github.com/OfficeDev/BotBuilder-MicrosoftTeams/issues/189

**Closed** 2019-06-26 10:53 UTC
Labels: duplicate, teams-developer-support
