### ISSUE TITLE
Invalid url reference

### ISSUE THREAD

**Issue by divya-akula** [MicrosoftDocs/msteams-docs#2859] opened 2021-03-05 06:34 UTC
![image](https://user-images.githubusercontent.com/9211327/110076604-c81a2100-7daa-11eb-84e4-c5527cfa2830.png)
The url for the highlighted link is navigating to 404 not found

![image](https://user-images.githubusercontent.com/9211327/110076682-ebdd6700-7daa-11eb-9bd4-bf3e9071d734.png)

**Comment by Mamatha-MSFT** [comment] 2021-03-08 13:07
Hi @divya-akula, I am unable to repro the issue. I think the issue is fixed now. Please check and let us know if the issue still persists.

**Closed** 2021-03-15 19:00 UTC
Labels: needs-author-feedback, status-no-recent-activity, teams-developer-support
